### ISSUE TITLE
lgb.LightGBMTunerCV: TrialState.FAIL because the returned value from the objective function cannot be casted to float

### ISSUE THREAD

**Issue by konradsemsch** [optuna/optuna#1500]
The lgb.LightGBMTuner seems to run for a number of trials and then breaks unexpectedly. The strange thing is that it runs without problems for a number of steps before the error occurs.

## Expected behavior

This is my code piece:

```python
self._parameters_set_2 = {
                "objective": "regression",
                "metric": "rmse", 
                "verbosity": -1,
                "boosting_type": "gbdt"
}

data_train_lgb = lgb.Dataset(
                self._pipeline_prepare.fit_transform(self._data["training"]["X"]), 
                label = self._data["training"]["y"]
)

tuner_lgb = lgb.LightGBMTunerCV(
                    self._parameters_set_2, 
                    data_train_lgb,  
                    verbose_eval = 1,
                    num_boost_round = 100, 
                    early_stopping_rounds = 10, 
                    time_budget = 10,
                    folds = self._data["validation_time_cv"]
                )
```

## Environment

- Optuna version: 1.5.0  
- Python version: 3.7
- OS: MacOS 10.15.3 (19D76)

## Error messages, stack traces, or logs

```
[I 2020-07-09 11:33:03,956] Finished trial#29 with value: 0.07808463369078895 with parameters: {'bagging_fraction': 0.9527650536197096, 'bagging_freq': 2}. Best is trial#29 with value: 0.07808463369078895.
bagging, val_score: 0.078085:  30%|######################################1                                                                                        | 3/10 [00:01<00:02,  2.38it/s][1]     cv_agg's rmse: 0.0783785 + 0.039904
[2]     cv_agg's rmse: 0.0783836 + 0.0398658
[3]     cv_agg's rmse: 0.0783535 + 0.0397835
[4]     cv_agg's rmse: 0.0783261 + 0.0398097
[5]     cv_agg's rmse: 0.0783087 + 0.0398446
[6]     cv_agg's rmse: 0.0782265 + 0.0396464
[7]     cv_agg's rmse: 0.0783195 + 0.0393913
[8]     cv_agg's rmse: 0.0783578 + 0.0392715
[9]     cv_agg's rmse: 0.0783393 + 0.0391258
[10]    cv_agg's rmse: 0.0784091 + 0.0390127
[11]    cv_agg's rmse: 0.0785363 + 0.0389685
[12]    cv_agg's rmse: 0.0785213 + 0.0386974
[13]    cv_agg's rmse: 0.0784512 + 0.0386922
[14]    cv_agg's rmse: 0.0784105 + 0.0385913
[15]    cv_agg's rmse: 0.0784307 + 0.0385545
[16]    cv_agg's rmse: 0.078539 + 0.0384206
bagging, val_score: 0.078085:  40%|##################################################8                                                                            | 4/10 [00:01<00:02,  2.44it/s][I 2020-07-09 11:33:04,344] Finished trial#30 with value: 0.07822653355517642 with parameters: {'bagging_fraction': 0.5620285231108505, 'bagging_freq': 2}. Best is trial#29 with value: 0.07808463369078895.
bagging, val_score: 0.078085:  40%|##################################################8                                                                            | 4/10 [00:01<00:02,  2.44it/s][1]     cv_agg's rmse: 0.0783772 + 0.0399073
[2]     cv_agg's rmse: 0.0783782 + 0.0398754
[3]     cv_agg's rmse: 0.0781955 + 0.0395771
[4]     cv_agg's rmse: 0.0782144 + 0.0395464
[5]     cv_agg's rmse: 0.0782016 + 0.0395846
[6]     cv_agg's rmse: 0.0781716 + 0.0395182
[7]     cv_agg's rmse: 0.0782204 + 0.0394778
[8]     cv_agg's rmse: 0.0782837 + 0.039339
[9]     cv_agg's rmse: 0.0783296 + 0.0392405
[10]    cv_agg's rmse: 0.0783967 + 0.0391217
[11]    cv_agg's rmse: 0.0786546 + 0.0390099
[12]    cv_agg's rmse: 0.078685 + 0.0387856
[13]    cv_agg's rmse: 0.0786055 + 0.0387932
[14]    cv_agg's rmse: 0.0785633 + 0.0386666
[15]    cv_agg's rmse: 0.0784939 + 0.0384941
[16]    cv_agg's rmse: 0.0785136 + 0.0383061
bagging, val_score: 0.078085:  50%|###############################################################5                                                               | 5/10 [00:02<00:01,  2.52it/s][I 2020-07-09 11:33:04,711] Finished trial#31 with value: 0.0781716160037223 with parameters: {'bagging_fraction': 0.5886098133062734, 'bagging_freq': 4}. Best is trial#29 with value: 0.07808463369078895.
bagging, val_score: 0.078085:  50%|###############################################################5                                                               | 5/10 [00:02<00:01,  2.52it/s][1]     cv_agg's rmse: 0.078378 + 0.0399054
[2]     cv_agg's rmse: 0.0783789 + 0.0398714
[3]     cv_agg's rmse: 0.0783394 + 0.0398052
[4]     cv_agg's rmse: 0.0783081 + 0.0398094
[5]     cv_agg's rmse: 0.0782946 + 0.0398459
[6]     cv_agg's rmse: 0.0782345 + 0.0396868
[7]     cv_agg's rmse: 0.0782768 + 0.0394813
[8]     cv_agg's rmse: 0.0783277 + 0.0393536
[9]     cv_agg's rmse: 0.0783678 + 0.0392847
[10]    cv_agg's rmse: 0.0784627 + 0.0391973
[11]    cv_agg's rmse: 0.0785918 + 0.0391482
[12]    cv_agg's rmse: 0.0785799 + 0.0388465
[13]    cv_agg's rmse: 0.0785052 + 0.0388237
[14]    cv_agg's rmse: 0.0785005 + 0.0387125
[15]    cv_agg's rmse: 0.078562 + 0.0386594
[16]    cv_agg's rmse: 0.0786887 + 0.0385622
bagging, val_score: 0.078085:  60%|############################################################################2                                                  | 6/10 [00:02<00:01,  2.56it/s][I 2020-07-09 11:33:05,084] Finished trial#32 with value: 0.07823448856454775 with parameters: {'bagging_fraction': 0.5748529547945029, 'bagging_freq': 2}. Best is trial#29 with value: 0.07808463369078895.
bagging, val_score: 0.078085:  60%|############################################################################2                                                  | 6/10 [00:02<00:01,  2.42it/s]
  0%|                                                                                                                                                                      | 0/6 [00:00<?, ?it/s]
  0%|                                                                                                                                                                     | 0/20 [00:00<?, ?it/s]
  0%|                                                                                                                                                                      | 0/5 [00:00<?, ?it/s]
Best score: 0.07808463369078895
Best params: {'objective': 'regression', 'metric': 'rmse', 'verbosity': -1, 'boosting_type': 'gbdt', 'lambda_l1': 0.0, 'lambda_l2': 0.0, 'num_leaves': 101, 'feature_fraction': 0.5, 'bagging_fraction': 0.9527650536197096, 'bagging_freq': 2, 'min_child_samples': 20}
  Params: 
    objective: regression
    metric: rmse
    verbosity: -1
    boosting_type: gbdt
    lambda_l1: 0.0
    lambda_l2: 0.0
    num_leaves: 101
    feature_fraction: 0.5
    bagging_fraction: 0.9527650536197096
    bagging_freq: 2
    min_child_samples: 20
[W 2020-07-09 11:33:05,134] Setting status of trial#9 as TrialState.FAIL because the returned value from the objective function cannot be casted to float. Returned value is: {'objective': 'regression', 'metric': 'rmse', 'verbosity': -1, 'boosting_type': 'gbdt', 'lambda_l1': 0.0, 'lambda_l2': 0.0, 'num_leaves': 101, 'feature_fraction': 0.5, 'bagging_fraction': 0.9527650536197096, 'bagging_freq': 2, 'min_child_samples': 20}
Traceback (most recent call last):
    print(f"Second stage | best parameters are: {self._study_stage_2.best_params}")
  File "/Users/konradsemsch/.local/share/virtualenvs/Package-21BxfxdE/lib/python3.7/site-packages/optuna/study.py", line 72, in best_params
    return self.best_trial.params
  File "/Users/konradsemsch/.local/share/virtualenvs/Package-21BxfxdE/lib/python3.7/site-packages/optuna/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/Users/konradsemsch/.local/share/virtualenvs/Package-21BxfxdE/lib/python3.7/site-packages/optuna/storages/in_memory.py", line 293, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
```

## Steps to reproduce

Not sure if it can be fully reproduced as I can't share the data that I'm using for this. Into which direction is this error pointing so that I could further validate?

**Comment by toshihikoyanase** [comment]
Thank you for your report. I've never seen this phenomenon.
I'm wondering why the 9th trial finished later than 29th trial.
I guess lightgbm stalled and crashed in the `LightGBMTunerCV.run`  and somehow returned the lightgbm params instead of objective values. I created a [notebook](https://colab.research.google.com/drive/1mRLM6DSxkAInKR6MMJUUFFobSqDqKgWD#scrollTo=WXg38c0f3zHG) based on the scenario, but I couldn't reproduce the error based on the scenario.

Could you give us more information?
- LightGBM version
- single worker or multiple workers?
- frequency of bugs

**Comment by konradsemsch** [comment]
HI @toshihikoyanase ! Sorry for a late reply. I agree it's quite a strange one...

- LightGBM version - lightgbm==2.3.1
- single worker or multiple workers? - single
- frequency of bugs - every time I run the script

How could I further assist you in debugging this?

**Comment by konradsemsch** [comment]
Hi @toshihikoyanase! How should we proceed with this issue? I just updated to the latest version of Optuna and was surprised to see that the error persists.

**Comment by toshihikoyanase** [comment]
@konradsemsch I'm sorry for the delayed response.
I couldn't reproduce your failure even if I use `lightgbm==2.3.1`.
If possible, could you share executable code to reproduce the failure?

BTW, I some developer reported that LightGBM Dataset also has tuning parameters, and it may cause errors if we repeatedly train models with the same dataset. It may be related to your issue, and I created a draft PR #1805 . If you have time, please try it with your code.

**Comment by konradsemsch** [comment]
Hi @toshihikoyanase - we can close the issue. The problem was on my end.

The above code was wrapped into something a function and called within something like this:

```python
        self._study_stage_1 = optuna.create_study(direction = "maximize")
        self._study_stage_1.optimize(
            self._objective_stage_1,
            **self._tuning_params_stage_1
        )
```

The reason for this was this was that the model is part of a larger python package, where in one stage I do not use the tuner and later use the tuner (hence the confusion about using or not using the study method itself). All in all, I can confirm that everything is working now as expected!
