### ISSUE TITLE
ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets

### ISSUE THREAD

**Issue by bhishanpdl** [optuna/optuna#1604]
When using optuna with lightgbm multiclass classification, I got the following error. This might be a bug in optuna or in my code, so I decided to ask for help in this issue tracker.

# Code
```python
# load the libraries
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
import lightgbm as lgb
import optuna

print(optuna.__version__) # 2.0.0

# data
df = sns.load_dataset('iris')
df = df.sample(frac=1)
df['species'] = df['species'].replace({'setosa':0, 'versicolor':1, 'virginica':2})
t = df.pop('species')

target = 'species'
df_Xtrain,ser_ytrain = df[:50], t[:50]
df_Xvalid, ser_yvalid = df[50:100], t[50:100]
df_Xtest, ser_ytest = df[100:], t[100:]

ytrain = np.array(ser_ytrain)
yvalid = np.array(ser_yvalid)
ytest = np.array(ser_ytest)

dtrain = lgb.Dataset(df_Xtrain, label=ser_ytrain)
dvalid = lgb.Dataset(df_Xvalid, label=ser_yvalid, reference=dtrain)
dtest = lgb.Dataset(df_Xtest)

# lightgbm HPO
def objective(trial):

    params = {"objective": "multiclass",
              "boosting_type": "gbdt",
              'num_class':3,
              "metric": "multi_logloss",
              "verbose": 0}

    params["learning_rate"] = trial.suggest_uniform('learning_rate',1e-5, 1.0)
    params["num_leaves"]= trial.suggest_int('num_leaves', 10, 500)
    params["feature_fraction"] = trial.suggest_uniform('feature_fraction',0.0, 1.0)
    params["bagging_fraction"] = trial.suggest_uniform('bagging_fraction', 0.0, 1.0)
    params["bagging_freq"] = trial.suggest_int('bagging_freq', 5, 100)
    params["max_depth"] = trial.suggest_int('max_depth', 5, 20)

    pruning_callback = optuna.integration.LightGBMPruningCallback(trial,
                                                             "multi_logloss")
    

    model = lgb.train(params, dtrain,
                      num_boost_round=1000,
                      early_stopping_rounds=30,
                      valid_sets=dvalid,
                      callbacks=[pruning_callback]
                     )

    vd_preds = model.predict(df_Xvalid, num_iteration=model.best_iteration)
    acc = accuracy_score(yvalid,vd_preds)

    return 1 - acc # we need to minimize


study = optuna.create_study()
study.optimize(objective, n_trials=1)
```

# Error
```
[W 2020-08-06 19:36:29,002] Trial 0 failed because of the following error: ValueError("Classification metrics can't handle a mix of multiclass and continuous-multioutput targets")
Traceback (most recent call last):
  File "/Users/poudel/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/optuna/study.py", line 709, in _run_trial
    result = func(trial)
  File "<ipython-input-2-992a83133a8f>", line 58, in objective
    acc = accuracy_score(yvalid,vd_preds)
  File "/Users/poudel/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/Users/poudel/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 187, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/Users/poudel/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 91, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-992a83133a8f> in <module>
     62 
     63 study = optuna.create_study()
---> 64 study.optimize(objective, n_trials=1)

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    290             if n_jobs == 1:
    291                 self._optimize_sequential(
--> 292                     func, n_trials, timeout, catch, callbacks, gc_after_trial, None
    293                 )
    294             else:

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/optuna/study.py in _optimize_sequential(self, func, n_trials, timeout, catch, callbacks, gc_after_trial, time_start)
    652                     break
    653 
--> 654             self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
    655 
    656             self._progress_bar.update((datetime.datetime.now() - time_start).total_seconds())

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/optuna/study.py in _run_trial_and_callbacks(self, func, catch, callbacks, gc_after_trial)
    683         # type: (...) -> None
    684 
--> 685         trial = self._run_trial(func, catch, gc_after_trial)
    686         if callbacks is not None:
    687             frozen_trial = copy.deepcopy(self._storage.get_trial(trial._trial_id))

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/optuna/study.py in _run_trial(self, func, catch, gc_after_trial)
    707 
    708         try:
--> 709             result = func(trial)
    710         except exceptions.TrialPruned as e:
    711             message = "Trial {} pruned. {}".format(trial_number, str(e))

<ipython-input-2-992a83133a8f> in objective(trial)
     56 
     57     vd_preds = model.predict(df_Xvalid, num_iteration=model.best_iteration)
---> 58     acc = accuracy_score(yvalid,vd_preds)
     59 
     60     return 1 - acc # we need to minimize

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/metrics/_classification.py in accuracy_score(y_true, y_pred, normalize, sample_weight)
    185 
    186     # Compute accuracy for each possible representation
--> 187     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    188     check_consistent_length(y_true, y_pred, sample_weight)
    189     if y_type.startswith('multilabel'):

~/opt/miniconda3/envs/dataSc/lib/python3.7/site-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     89     if len(y_type) > 1:
     90         raise ValueError("Classification metrics can't handle a mix of {0} "
---> 91                          "and {1} targets".format(type_true, type_pred))
     92 
     93     # We can't have more than one value on y_type => The set is no more needed

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets
```

**Comment by HideakiImamura** [comment]
Thanks for the question. It looks not for Optuna errors. 

I tried your script and have noticed that your `vd_preds` is not 1d-array. According to the reference of `[sklearn.metrics.accuracy_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)`, the inputs of this function should be 1d-array. I think you should take `argmax` after the prediction.
```python
vd_preds = model.predict(df_Xvalid, num_iteration=model.best_iteration).argmax(axis=1)
```

**Comment by bhishanpdl** [comment]
This was a problem of sklearn, it returns (N,3) matrix and I need to get the argmax of the matrix.

I fixed the code by adding this line:
```python
vd_preds = np.argmax(vd_preds,axis=1)
```

I am closing the issue.

**Comment by qaixerabbas** [comment]
thank god I came across this thread. Thanks for the help mate @HideakiImamura and @bhishanpdl
