### ISSUE TITLE
CmaEsSampler.infer_relative_search_space is missing required positional argument: 'trial'

### ISSUE THREAD

**Issue by rbelew** [optuna/optuna#1645]
Use of CmaEsSampler throws an exception, 
`infer_relative_search_space is missing required positional argument: 'trial'`

## Expected behavior

Below is code that contrasts use of CmaEsSampler vs. the default sampler

## Environment

- Optuna version: 2.0
- Python version: 3.7.7
- OS: MacOSX 10.15
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
[I 2020-08-17 09:23:18,345] A new study created with name: cmaesTst
Traceback (most recent call last):
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/src/cmaesTst.py", line 82, in <module>
    study.optimize(op_objective, n_trials=20)
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/study.py", line 292, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/study.py", line 654, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/study.py", line 685, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/study.py", line 705, in _run_trial
    trial = trial_module.Trial(self, trial_id)
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/trial/_trial.py", line 65, in __init__
    self._init_relative_params()
  File "/Users/Shared/Relocated Items/Security/Data/virtualenv/covasim/lib/python3.7/site-packages/optuna/trial/_trial.py", line 74, in _init_relative_params
    self.relative_search_space = self.study.sampler.infer_relative_search_space(study, trial)
TypeError: infer_relative_search_space() missing 1 required positional argument: 'trial'
```

## Steps to reproduce

1. Run code, observe error using CmaEsSampler
2. Comment out call to `make_study()` using CmaEsSampler
3. Un-comment line below using  call to `make_study()` with default sampler

## Reproducible examples (optional)

```python
import numpy as np
import optuna as op
import sciris as sc

from optuna.samplers import CmaEsSampler

def objective(trial):
	x = trial[0]
	y = trial[1]
	return x ** 2 + y



def op_objective(trial):

	SIMparam = dict(beta = dict(lb=0.003, ub=0.008),
		 		    pop_infected = dict(lb=1000,   ub=10000) )

	x = np.zeros(len(SIMparam))
	for k,key in enumerate(SIMparam.keys()):
		lb = SIMparam[key]['lb']
		ub = SIMparam[key]['ub']
		x[k] = trial.suggest_uniform(key, lb, ub )

	return objective(x)

def make_study(storage,name,sampler=None):
	try: 
		op.delete_study(storage=storage, study_name=name)
	except: 
		pass
	if sampler == None:
		return op.create_study(storage=storage, study_name=name)
	else:
		return op.create_study(storage=storage, study_name=name,sampler=sampler)


if __name__ == '__main__':
	
	name = 'cmaesTst'
	storage   = f'sqlite:///{name}.db'
	study = make_study(storage, 'cmaesTst', sampler=CmaEsSampler)
	# study = make_study(storage,'cmaesTst')
	study.optimize(op_objective, n_trials=20)
```

**Comment by rbelew** [comment]
Note,  I just tried the same experiment importing CmaEsSampler
from optuna.integration (vs. optuna.samplers): same error.

**Comment by c-bata** [comment]
Hi @rbelew. You need to instantiate an object of CmaEsSampler.

```diff
...
	
	name = 'cmaesTst'
	storage   = f'sqlite:///{name}.db'
-	study = make_study(storage, 'cmaesTst', sampler=CmaEsSampler)
+	study = make_study(storage, 'cmaesTst', sampler=CmaEsSampler())
	# study = make_study(storage,'cmaesTst')
	study.optimize(op_objective, n_trials=20)
```

**Comment by rbelew** [comment]
ah, of course!  thanks very much.
