### ISSUE TITLE
[Bug] Early stopping not working in OptunaSearchCV

### ISSUE THREAD

**Issue by rohan-gt** [optuna/optuna#1651]
`max_iter` in `OptunaSearchCV` doesn't work with LightGBM because there's no `partial_fit`. [This](https://github.com/microsoft/LightGBM/issues/2718) could be a potential fix

**Comment by toshihikoyanase** [comment]
Thank you for your bug report. I think I can reproduce this issue. 

Code:
```python
import lightgbm as lgb
from sklearn.datasets import load_iris

import optuna

if __name__ == "__main__":
    clf = lgb.LGBMClassifier()


    param_distributions = {
        "max_depth": optuna.distributions.IntUniformDistribution(3, 15),
    }

    optuna_search = optuna.integration.OptunaSearchCV(
        clf, param_distributions, n_trials=100, timeout=600, verbose=2, max_iter=10, enable_pruning=True,
    )

    X, y = load_iris(return_X_y=True)
    optuna_search.fit(X, y)

    print("Best trial:")
    trial = optuna_search.study_.best_trial

    print("  Value: ", trial.value)
    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

```

Output:
```console
examples/optuna_search_cv_simple.py:27: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  clf, param_distributions, n_trials=100, timeout=600, verbose=2, max_iter=10, enable_pruning=True,
Traceback (most recent call last):
  File "examples/optuna_search_cv_simple.py", line 31, in <module>
    optuna_search.fit(X, y)
  File "/Users/yanase/pfn/code/my-gh-optuna/optuna/integration/sklearn.py", line 839, in fit
    self._check_params()
  File "/Users/yanase/pfn/code/my-gh-optuna/optuna/integration/sklearn.py", line 768, in _check_params
    raise ValueError("estimator must support partial_fit.")
ValueError: estimator must support partial_fit.
```

https://github.com/microsoft/LightGBM/issues/2718 suggested that we should add a code for `LightGBM` to `OptunaSearchCV`.  The `init_model` argument of `LightGBMClassifier.fit` enable us to train the `LightGBMClassifier` step by step like `partial_fit`. 

Please let me know if my understanding is wrong.

**Comment by rohan-gt** [comment]
Sounds right
