### ISSUE TITLE
ubuntu pip install error

### ISSUE THREAD

**Issue by Jie-Yuan** [optuna/optuna#1739]
![image](https://user-images.githubusercontent.com/20265321/91530606-fa4f4f80-e93d-11ea-9653-946a3c7e653e.png)

**Comment by hvy** [comment]
Given my very shallow understanding, does it happen to be a duplicate of https://github.com/iterative/dvc/issues/1995 (https://github.com/iterative/dvc/issues/1995#issuecomment-540259645)?

**Comment by Jie-Yuan** [comment]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting optuna
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/06/b0/9a6313c78bca92abfacc08a2ad8b27bfe845256f615786ee2b6452ae1978/optuna-2.0.0.tar.gz (226 kB)
     |████████████████████████████████| 226 kB 21.2 MB/s eta 0:00:01
Collecting alembic
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/60/1e/cabc75a189de0fbb2841d0975243e59bde8b7822bacbb95008ac6fe9ad47/alembic-1.4.2.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 51.8 MB/s eta 0:00:01
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5ipz5ku3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 22, in <module>
      from pip._internal.req.constructors import (
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 10, in <module>
      from .req_install import InstallRequirement
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 10, in <module>
      import uuid
    File "/usr/local/lib/python3.6/dist-packages/uuid.py", line 138
      if not 0 <= time_low < 1<<32L:
                                  ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5ipz5ku3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by spikefairway** [comment]
I had faced the same issue in installing optuna via pip. I tried to fix with removing enum34 library as suggested. However, now I'm facing another error for typing library as below. We cannot remove typing library because this library is required from optuna. I would appreciate it if some experts help me for this issue. Thanks in advance.

The followings are the error message I faced:

```
  ERROR: Command errored out with exit status 1:
   command: /opt/Frameworks/2.1/python/3.7.7/bin/python /opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k64616d1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/opt/python/3.7.7/base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/python/3.7.7/base/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/opt/python/3.7.7/base/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/opt/python/3.7.7/base/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/typing.py", line 1356, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/typing.py", line 1004, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/Frameworks/2.1/python/3.7.7/bin/python /opt/Frameworks/2.1/python/3.7.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k64616d1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by toshihikoyanase** [comment]
@spikefairway Thank you for your report with the detailed log messages.
I think you don't need the `typing` library because you use Python 3.7, which includes the `typing` module by default.

**Comment by spikefairway** [comment]
@toshihikoyanase Thank you for your suggestion for this issue. I removed the typing library as you suggested.
Then, I faced and fixed another error for setuptools as https://github.com/pypa/setuptools/issues/2353. 
For now, I have succeeded to install optuna. Thank you very much for your advice again.

**Comment by toshihikoyanase** [comment]
@spikefairway Thank you for your feedback. I'm glad to hear that.
Let me summarize your solution.

1. Uninstall the backport libraries (i.e., `enum34` and `typing`) that are not required for Python 3.6+.
2. Resolve the issue related to `setuptools==50` mentioned in https://github.com/pypa/setuptools/issues/2353.

Please add comments if you have further steps to resolve your installation problem.

@Jie-Yuan I think the above solution is also effective for your issue. Please take a look.

**Comment by spikefairway** [comment]
@toshihikoyanase Thank you for your reply. I'm sure that your summary is corresponding to my solution.

**Comment by varunlakshmanan** [comment]
> @spikefairway Thank you for your feedback. I'm glad to hear that.
> Let me summarize your solution.
> 
> 1. Uninstall the backport libraries (i.e., `enum34` and `typing`) that are not required for Python 3.6+.
> 2. Resolve the issue related to `setuptools==50` mentioned in [pypa/setuptools#2353](https://github.com/pypa/setuptools/issues/2353).
> 
> Please add comments if you have further steps to resolve your installation problem.
> 
> @Jie-Yuan I think the above solution is also effective for your issue. Please take a look.

Uninstalling `enum34` fixed this error for me. Thanks for the solution.
