### ISSUE TITLE
optuna_pruner not in acceptable choices for epoch callbacks (AllenNLP)

### ISSUE THREAD

**Issue by cjber** [optuna/optuna#1845]
Running the AllenNLP jsonnet example from [here](https://github.com/optuna/optuna/tree/master/examples/allennlp) gives the error: 

```
allennlp.common.checks.ConfigurationError: optuna_pruner not in acceptable choices for trainer.epoch_callbacks.0.type: ['null', 'track_epoch_callback']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

## Expected behavior

This callback is registered [here](https://github.com/optuna/optuna/blob/9d4dbb07063d0ae68f71b5f49dacccc048881472/optuna/integration/allennlp.py#L368) using `@EpochCallback.register("optuna_pruner")`.

So adding it as an epoch callback to the jsonnet should work but doesn't for me:

```
    epoch_callbacks: [
      {
        type: 'optuna_pruner',
      },
    ],
```

Sorry is this is more of an AllenNLP issue, I thought is ask here since it's reproducible using the optuna example.

## Environment

- Optuna version: 2.1.0
- Python version: 3.8.5
- OS: Arch Linux
- (Optional) Other libraries and their versions:

- Allennlp version: 1.1.0

## Error messages, stack traces, or logs

```
[W 2020-09-17 11:04:05,065] Trial 0 failed because of the following error: ConfigurationError()
Traceback (most recent call last):
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "test_op.py", line 41, in objective
    return executor.run()
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/integration/allennlp.py", line 145, in run
    allennlp.commands.train.train_model(params, self._serialization_dir)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 224, in train_model
    model = _train_worker(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 417, in _train_worker
    train_loop = TrainModel.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 576, in from_params
    return retyped_subclass.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 611, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 670, in from_partial_objects
    trainer_ = trainer.construct(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/lazy.py", line 46, in construct
    return self._constructor(**kwargs)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 446, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 576, in from_params
    return retyped_subclass.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 180, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 463, in construct_arg
    value = construct_arg(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 557, in from_params
    choice = params.pop_choice(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/params.py", line 351, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: optuna_pruner not in acceptable choices for trainer.epoch_callbacks.0.type: ['null']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
Traceback (most recent call last):
  File "test_op.py", line 53, in <module>
    study.optimize(objective, n_trials=50, timeout=600)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/study.py", line 327, in optimize
    self._optimize_sequential(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/study.py", line 726, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/study.py", line 755, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "test_op.py", line 41, in objective
    return executor.run()
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/optuna/integration/allennlp.py", line 145, in run
    allennlp.commands.train.train_model(params, self._serialization_dir)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 224, in train_model
    model = _train_worker(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 417, in _train_worker
    train_loop = TrainModel.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 576, in from_params
    return retyped_subclass.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 611, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/commands/train.py", line 670, in from_partial_objects
    trainer_ = trainer.construct(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/lazy.py", line 46, in construct
    return self._constructor(**kwargs)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 446, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 576, in from_params
    return retyped_subclass.from_params(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 609, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 180, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 287, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 463, in construct_arg
    value = construct_arg(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 321, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/from_params.py", line 557, in from_params
    choice = params.pop_choice(
  File "/home/cjber/.pyenv/versions/py3nvim/lib/python3.8/site-packages/allennlp/common/params.py", line 351, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: optuna_pruner not in acceptable choices for trainer.epoch_callbacks.0.type: ['null']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.
```

## Reproducible examples (optional)

See https://github.com/optuna/optuna/tree/master/examples/allennlp

**Comment by toshihikoyanase** [comment]
Thank you for your detailed report.
The `optuna_pruner` callback is merged seven hours ago (c.f., #1772) and it is not included in the latest Optuna release (i.e., v2.1.0). Could you install Optuna from the master branch to try it?

```console
$ pip install git+https://github.com/optuna/optuna.git
```

**Comment by cjber** [comment]
Thank you! That was it. Sorry I didn't realise how recently this was implemented.
