### ISSUE TITLE
Raise KeyError when fobj is passed to lgb.train

### ISSUE THREAD

**Issue by Y-oHr-N** [optuna/optuna#1854]
## Environment

- Optuna version: 2.1.0
- Python version: Python 3.8.2

## Error messages, stack traces, or logs

```
[I 2020-09-22 21:07:32,840] A new study created in memory with name: no-name-7c57d5c3-27a8-4238-8846-6acf2c0faf1d
feature_fraction, val_score: inf:   0%|                                                                | 0/7 [00:00<?, ?it/s][LightGBM] [Warning] Unknown parameter: feature_pre_filter
[LightGBM] [Warning] Unknown parameter: feature_pre_filter
[LightGBM] [Warning] Using self-defined objective function
[LightGBM] [Info] Total Bins 4266
[LightGBM] [Info] Number of data: 426, number of used features: 30
[LightGBM] [Warning] Unknown parameter: feature_pre_filter
[LightGBM] [Warning] Using self-defined objective function
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[W 2020-09-22 21:07:32,850] Trial 0 failed because of the following error: KeyError('binary_logloss')
Traceback (most recent call last):
  File "/home/yohori/optuna/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "/home/yohori/optuna/optuna/integration/_lightgbm_tuner/optimize.py", line 237, in __call__
    val_score = self._get_booster_best_score(booster)
  File "/home/yohori/optuna/optuna/integration/_lightgbm_tuner/optimize.py", line 114, in _get_booster_best_score
    val_score = booster.best_score[valid_name][metric]
KeyError: 'binary_logloss'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-52c3726d7cbf> in <module>
     24 dvalid = lgb.Dataset(X_valid, y_valid)
     25 
---> 26 booster = lgb.train(params, dtrain, valid_sets=dvalid, num_boost_round=10, fobj=loglikelihood)

~/optuna/optuna/integration/_lightgbm_tuner/__init__.py in train(*args, **kwargs)
     31 
     32     auto_booster = LightGBMTuner(*args, **kwargs)
---> 33     auto_booster.run()
     34     return auto_booster.get_best_booster()

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in run(self)
    472         self.sample_train_set()
    473 
--> 474         self.tune_feature_fraction()
    475         self.tune_num_leaves()
    476         self.tune_bagging()

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in tune_feature_fraction(self, n_trials)
    497 
    498         sampler = optuna.samplers.GridSampler({param_name: param_values})
--> 499         self._tune_params([param_name], len(param_values), sampler, "feature_fraction")
    500 
    501     def tune_num_leaves(self, n_trials: int = 20) -> None:

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in _tune_params(self, target_param_names, n_trials, sampler, step_name)
    825     ) -> _OptunaObjective:
    826 
--> 827         objective = super(LightGBMTuner, self)._tune_params(
    828             target_param_names, n_trials, sampler, step_name
    829         )

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in _tune_params(self, target_param_names, n_trials, sampler, step_name)
    573             _timeout = None
    574         if _n_trials > 0:
--> 575             study.optimize(
    576                 objective,
    577                 n_trials=_n_trials,

~/optuna/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    325         try:
    326             if n_jobs == 1:
--> 327                 self._optimize_sequential(
    328                     func, n_trials, timeout, catch, callbacks, gc_after_trial, None
    329                 )

~/optuna/optuna/study.py in _optimize_sequential(self, func, n_trials, timeout, catch, callbacks, gc_after_trial, time_start)
    724                     break
    725 
--> 726             self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
    727 
    728             self._progress_bar.update((datetime.datetime.now() - time_start).total_seconds())

~/optuna/optuna/study.py in _run_trial_and_callbacks(self, func, catch, callbacks, gc_after_trial)
    753     ) -> None:
    754 
--> 755         trial = self._run_trial(func, catch, gc_after_trial)
    756         if callbacks is not None:
    757             frozen_trial = copy.deepcopy(self._storage.get_trial(trial._trial_id))

~/optuna/optuna/study.py in _run_trial(self, func, catch, gc_after_trial)
    776 
    777         try:
--> 778             result = func(trial)
    779         except exceptions.TrialPruned as e:
    780             message = "Trial {} pruned. {}".format(trial_number, str(e))

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in __call__(self, trial)
    235         booster = lgb.train(self.lgbm_params, self.train_set, **self.lgbm_kwargs)
    236 
--> 237         val_score = self._get_booster_best_score(booster)
    238         elapsed_secs = time.time() - start_time
    239         average_iteration_time = elapsed_secs / booster.current_iteration()

~/optuna/optuna/integration/_lightgbm_tuner/optimize.py in _get_booster_best_score(self, booster)
    112             raise NotImplementedError
    113 
--> 114         val_score = booster.best_score[valid_name][metric]
    115         return val_score
    116 

KeyError: 'binary_logloss'
```

## Reproducible examples (optional)

```python
# success
# import lightgbm as lgb
# failure
import optuna.integration.lightgbm as lgb
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split


def loglikelihood(preds, train_data): 
    labels = train_data.get_label() 
    preds = 1. / (1. + np.exp(-preds)) 
    grad = preds - labels 
    hess = preds * (1. - preds) 
    return grad, hess


params = {"n_jobs": 1, "objective": "binary", "seed": 0} 

X, y = load_breast_cancer(return_X_y=True)
X, X_valid, y, y_valid = train_test_split(X, y)

dtrain = lgb.Dataset(X, y)
dvalid = lgb.Dataset(X_valid, y_valid)

booster = lgb.train(params, dtrain, valid_sets=dvalid, num_boost_round=10, fobj=loglikelihood)
```

**Comment by toshihikoyanase** [comment]
Thank you for your detailed report with the reproducible code.

When I use `fobj` with the original `lgb`, I still couldn't get the best score with `booster.best_score` at the last line of your code example. I guess the booster cannot find the evaluation function which corresponds to the given `fobj` function. Next, I specified the following `feval` function, and got the best score successfully. The tuner also worked as expected, and I think we should add `feval` when we use `fobj`. I'm not familiar with these options of the lightgbm, but does it make sense?

```python
def feval(preds, train_data):
    return "binary_logloss", sklearn.metrics.log_loss(train_data.get_label(), preds), False
```

**Comment by toshihikoyanase** [comment]
Let's come back to this issue after resolving #1351.

**Comment by Y-oHr-N** [comment]
Oh, my point seems to have been ridiculous. I'm closing this issue.
