### ISSUE TITLE
RuntimeError('Trial#0 [or 1, etc.] has already finished and can not be updated.',)

### ISSUE THREAD

**Issue by brethvoice** [optuna/optuna#1946]
Trial 1 [or 2, etc.] in study (indexed with first trial as 0) fails to complete when test object not instantiated within objective function.

## Expected behavior
Each trial, once begun, completes successfully and/or is pruned.

## Environment
- Optuna version:  2.2
- Python version:  3.6.9
- OS: Ubuntu (NVIDIA docker)
- Tensorflow: 2.3

## Error messages and stack traces
```
Trial 2 failed because of the following error: RuntimeError('Trial#1 has already finished and can not be updated.',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 799, in _run_trial
    result = func(trial)
  File "simple_study_mnist_classifier_settings.py", line 110, in objective
    batch_size=standard_object.batch_size,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/usr/local/lib/python3.6/dist-packages/optuna/integration/tfkeras.py", line 51, in on_epoch_end
    self._trial.report(float(current_score), step=epoch)
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial/_trial.py", line 579, in report
    self.storage.set_trial_intermediate_value(self._trial_id, step, value)
  File "/usr/local/lib/python3.6/dist-packages/optuna/storages/_in_memory.py", line 332, in set_trial_intermediate_value
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/usr/local/lib/python3.6/dist-packages/optuna/storages/_base.py", line 676, in check_trial_is_updatable
    "Trial#{} has already finished and can not be updated.".format(trial.number)
RuntimeError: Trial#1 has already finished and can not be updated.
Traceback (most recent call last):
  File "simple_study_mnist_classifier_settings.py", line 135, in <module>
    gc_after_trial=True,
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 339, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 747, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 776, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 799, in _run_trial
    result = func(trial)
  File "simple_study_mnist_classifier_settings.py", line 110, in objective
    batch_size=standard_object.batch_size,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/usr/local/lib/python3.6/dist-packages/optuna/integration/tfkeras.py", line 51, in on_epoch_end
    self._trial.report(float(current_score), step=epoch)
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial/_trial.py", line 579, in report
    self.storage.set_trial_intermediate_value(self._trial_id, step, value)
  File "/usr/local/lib/python3.6/dist-packages/optuna/storages/_in_memory.py", line 332, in set_trial_intermediate_value
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/usr/local/lib/python3.6/dist-packages/optuna/storages/_base.py", line 676, in check_trial_is_updatable
    "Trial#{} has already finished and can not be updated.".format(trial.number)
RuntimeError: Trial#1 has already finished and can not be updated.
```

## Steps to reproduce
1. Install plotly, optuna, and tensorflow
2. Run `simple_study_mnist_settings.py` from https://github.com/brethvoice/optuna_demo_MNIST (also requires EvaluateMNIST.py from https://github.com/brethvoice/optuna_demo_MNIST

## Reproducible example
```
CUDA_VISIBLE_DEVICES='0' TF_FORCE_GPU_ALLOW_GROWTH='false' python simple_study_mnist_settings.py
```

**Comment by brethvoice** [comment]
Note that some of the line numbers in the traceback may now be out of date.  I have tried several things to get past this error, and if any of them work I will update here in the comments.  My repo at https://github.com/brethvoice/optuna_demo_MNIST has the code I am running to replicate the problem tonight (United States Eastern time).

**Comment by brethvoice** [comment]
> We were using EvaluateMNIST.py as a singleton class; Prunable version is not a singleton. Run `study_mnist_settings.py` to see the difference; no error occurs.

An obvious solution would be to not use a singleton class and/or not instantiate it outside of the objective function.  Will test to make sure this is not a problem.

**Comment by hvy** [comment]
Thanks for the very detailed report. I'm not sure I've understood the intent behind the following logic, and whether this really is a bug. Please correct me if I'm wrong.

As seen [here](https://github.com/brethvoice/optuna_demo_MNIST/blob/main/simple_study_mnist_classifier_settings.py#L90-L94) (and in the copied objective function snippet below), you're appending `TFKerasPruningCallback` callback objects to the global `EvaluateMNIST` object. A `TFKerasPruningCallback` is only associated with a single trial (as can be seen from the trial object passed to its `__init__`) and the lifetime of this callback is only meant to span a single trial, not the entire study. I think the error stems from the fact that you're calling these callback objects on trials that's already been finished. Could you for instance instead only pass the last callback object to `fit`/`evaluate`, and store the callback object history if that's needed solely for bookkeeping.

```python
    keras_pruner = optuna.integration.TFKerasPruningCallback(
        trial,
        'val_categorical_accuracy',
    )
    standard_object.callbacks.append(keras_pruner)  # Append to callbacks list
```

**Comment by brethvoice** [comment]
@hvy You are correct.  This is not a bug and I am closing the issue; thank you for your diligent investigation and response!

**Comment by hvy** [comment]
Great, I hope you'll get it working. Thanks for the status update!
