### ISSUE TITLE
Can I use Optuna for LightGBM with Scikit-Learn api?

### ISSUE THREAD

**Issue by michael135** [optuna/optuna#2048]
#### I've tried the following but got an error:

```
import optuna
from optuna.integration.lightgbm import LGBMRegressor



def objective(trial):


    min_child_samples = trial.suggest_int('min_child_samples', 5, 100)
    num_leaves = trial.suggest_int('num_leaves', 2, 256)
    learning_rate = trial.suggest_uniform('learning_rate', 0.05, .7)
    n_estimators = trial.suggest_int('n_estimators', 2, 100),

    clf = LGBMRegressor(num_leaves=num_leaves,
                        objective = 'mape',
                        learning_rate=learning_rate,
                        n_estimators=n_estimators,
                        min_child_samples=min_child_samples,
                        n_jobs=-1
                       )
    

    clf.fit(train_x, train_y)
    y_pred = clf.predict(test_x, num_iteration=clf.best_iteration_)



    return mape(test_y, y_pred)



study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=10)
print(study.best_trial)
```

#### The final error has ended with this:
```
RuntimeError: scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class 'optuna.integration._lightgbm_tuner.sklearn.LGBMRegressor'> with constructor (self, *args: Any, **kwargs: Any) -> None doesn't  follow this convention
```

**Comment by crcrpar** [comment]
Hi @michael135, 

What if you import `LGBMRegressor` from lightgbm rather than optuna?

**Comment by michael135** [comment]
If run following, there is no errors:


`
from lightgbm import LGBMRegressor



min_child_samples = 10
num_leaves = 10
learning_rate = .1
n_estimators = 20

clf = LGBMRegressor(num_leaves=num_leaves,
                    objective = 'mape',
                    learning_rate=learning_rate,
                    n_estimators=n_estimators,
                    min_child_samples=min_child_samples,
                    n_jobs=-1,
                    verbosity=1
                   )


clf.fit(train_x, train_y,
        eval_set=[(test_x, test_y)],
        eval_metric='mape',
        early_stopping_rounds=10)
# clf.fit(train_x, train_y)
y_pred = clf.predict(test_x, num_iteration=clf.best_iteration_)`

**Comment by crcrpar** [comment]
The cause of the error is `n_estimators` being a tuple in your lightgbm.LGBMRegressor and Optuna snippet.
If you add a trailing comma after some value in variable definition or value assignment, the variable becomes a tuple, see: https://docs.python.org/3.8/library/stdtypes.html?highlight=tuple#tuples.

So, once you remove the trailing comma of `n_estimators = trial.suggest_int('n_estimators', 2, 100),`, the program will work.

**Comment by michael135** [comment]
@crcrpar  THANK YOU!
Maybe I should swith back from Jupyter to Pycharm.
(In Pycharm, It would show up such case...)

**Comment by crcrpar** [comment]
My pleasure :)

**Comment by michael135** [comment]
@crcrpar ,

I noticed something unexpected if I import

```
from lightgbm import LGBMRegressor
```
But if I import:

```
from optuna.integration.lightgbm import LGBMRegressor
```
it still has the error:
```
[I 2020-11-29 12:39:50,569] A new study created in memory with name: no-name-43117684-8cc7-4839-b0e2-f4eea05e699b
[W 2020-11-29 12:39:50,571] Trial 0 failed because of the following error: RuntimeError("scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class 'optuna.integration._lightgbm_tuner.sklearn.LGBMRegressor'> with constructor (self, *args: Any, **kwargs: Any) -> None doesn't  follow this convention.")
Traceback (most recent call last):
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/optuna/_optimize.py", line 189, in _run_trial
    value = func(trial)
  File "<ipython-input-52-f108f145cc35>", line 24, in objective
    clf.fit(train_x, train_y)
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py", line 779, in fit
    callbacks=callbacks, init_model=init_model)
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py", line 489, in fit
    params = self.get_params()
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py", line 343, in get_params
    params = super(LGBMModel, self).get_params(deep=deep)
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/sklearn/base.py", line 205, in get_params
    for key in self._get_param_names():
  File "/Users/md/virtualenvs/default/lib/python3.7/site-packages/sklearn/base.py", line 185, in _get_param_names
    % (cls, init_signature))
RuntimeError: scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class 'optuna.integration._lightgbm_tuner.sklearn.LGBMRegressor'> with constructor (self, *args: Any, **kwargs: Any) -> None doesn't  follow this convention.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-f108f145cc35> in <module>
     37 
     38 study = optuna.create_study(direction="minimize")
---> 39 study.optimize(objective, n_trials=100)
     40 print(study.best_trial)

~/virtualenvs/default/lib/python3.7/site-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    313             callbacks=callbacks,
    314             gc_after_trial=gc_after_trial,
--> 315             show_progress_bar=show_progress_bar,
    316         )
    317 

~/virtualenvs/default/lib/python3.7/site-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     63                 reseed_sampler_rng=False,
     64                 time_start=None,
---> 65                 progress_bar=progress_bar,
     66             )
     67         else:

~/virtualenvs/default/lib/python3.7/site-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    154 
    155         try:
--> 156             trial = _run_trial(study, func, catch)
    157         except Exception:
    158             raise

~/virtualenvs/default/lib/python3.7/site-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    187 
    188     try:
--> 189         value = func(trial)
    190     except exceptions.TrialPruned as e:
    191         # Register the last intermediate value if present as the value of the trial.

<ipython-input-52-f108f145cc35> in objective(trial)
     22 
     23 
---> 24     clf.fit(train_x, train_y)
     25 #     clf.fit(train_x, train_y,
     26 #         eval_set=[(test_x, test_y)],

~/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks, init_model)
    777                                        verbose=verbose, feature_name=feature_name,
    778                                        categorical_feature=categorical_feature,
--> 779                                        callbacks=callbacks, init_model=init_model)
    780         return self
    781 

~/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks, init_model)
    487             self._fobj = None
    488         evals_result = {}
--> 489         params = self.get_params()
    490         # user can set verbose with kwargs, it has higher priority
    491         if not any(verbose_alias in params for verbose_alias in _ConfigAliases.get("verbosity")) and self.silent:

~/virtualenvs/default/lib/python3.7/site-packages/lightgbm/sklearn.py in get_params(self, deep)
    341             Parameter names mapped to their values.
    342         """
--> 343         params = super(LGBMModel, self).get_params(deep=deep)
    344         params.update(self._other_params)
    345         return params

~/virtualenvs/default/lib/python3.7/site-packages/sklearn/base.py in get_params(self, deep)
    203         """
    204         out = dict()
--> 205         for key in self._get_param_names():
    206             try:
    207                 value = getattr(self, key)

~/virtualenvs/default/lib/python3.7/site-packages/sklearn/base.py in _get_param_names(cls)
    183                                    " %s with constructor %s doesn't "
    184                                    " follow this convention."
--> 185                                    % (cls, init_signature))
    186         # Extract and sort argument names excluding 'self'
    187         return sorted([p.name for p in parameters])

RuntimeError: scikit-learn estimators should always specify their parameters in the signature of their __init__ (no varargs). <class 'optuna.integration._lightgbm_tuner.sklearn.LGBMRegressor'> with constructor (self, *args: Any, **kwargs: Any) -> None doesn't  follow this convention.
```

**Does it makes sense ?**

**Comment by crcrpar** [comment]
Ah, I'm sorry, but I misunderstood your intent and how Optuna's LightGBMTuner is implemented.
The error makes sense to me partially but how the error appears is a bit weird to me at the same time.

1. If you want to use `LightGBMTuner`, follow [the example code](https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_simple.py) and [this official post](https://tech.preferred.jp/en/blog/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization/). Also, scikit learn API is not almost available as https://github.com/optuna/optuna/blob/master/optuna/integration/_lightgbm_tuner/sklearn.py. In this case, the code will look different from normal Optuna hyperparameter optimization programs.
2. If you want to use scikit-learn API and enable pruning, https://github.com/optuna/optuna/blob/master/examples/pruning/lightgbm_integration.py would be what you want.

Side note: The results and the time programs take might be different.

**Comment by michael135** [comment]
1. If I understand you correct it's better not to use a Scikit-Learn Api with Optuna LightGBMTuner?

2. Why it was working fine, when I was using a `from lightgbm import LGBMRegressor` ?

**Comment by crcrpar** [comment]
>     1. If I understand you correct it's better not to use a Scikit-Learn Api with Optuna LightGBMTuner?

Yes. Rather scikit-learn API of Optuna LightGBMTuner is unavailable unfortunately.

>     2. Just curious, why  it was working fine, when I was using a `from lightgbm import LGBMRegressor` ?

It might sound confusing but the goal of [`optuna.integration.lightgbm.train`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.train.html) is slightly different from that of [`optuna.integration.lightgbm.LightGBMPruningCallback`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.LightGBMPruningCallback.html#optuna-integration-lightgbmpruningcallback).
[`optuna.integration.lightgbm.train`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.train.html) tunes hyperparameters of lgbm in a stepwise manner and it's drop-in replacement for `lightgbm.train` while [`optuna.integration.lightgbm.LightGBMPruningCallback`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.LightGBMPruningCallback.html#optuna-integration-lightgbmpruningcallback) aims at enabling pruning of trials that use lightgbm inside `objective` function.

**Comment by michael135** [comment]
Thank you again @crcrpar!
