### ISSUE TITLE
Document more about the behavior of `add_trial` and `enque_trial`

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2131]
TLDR: The documentation of the both API mentioned above is poor.

## Environments
- Optuna: `-e git+ssh://git@github.com/optuna/optuna@7968f31b0331eabd48c19509ebf9e373a4da503e#egg=optuna`
- Python: `3.7.9`

### Code

```python
import optuna


def objective(trial: optuna.trial.Trial) -> float:
    x = trial.suggest_float("x", low=-10.0, high=10.0)

    return abs(x / 2)


def main():
    study = optuna.create_study(direction="minimize")

    study.enqueue_trial({"x": 10.0})  # Ignored due to being out of range
    study.optimize(objective, n_trials=10)
    print(f"#trials: {len(study.trials)}")

    study.enqueue_trial({"x": 10.0})  # Ignored due to being out of range
    study.optimize(objective, n_trials=10)
    print(f"#trials: {len(study.trials)}")

    created_trial: optuna.trial.FrozenTrial = optuna.trial.create_trial(
            value=45, params={"x": 90}, distributions={"x": optuna.distributions.UniformDistribution(0, 100)})
    study.add_trial(created_trial)  # this trial is registered
    print(f"#trials: {len(study.trials)}")

    # this `create_trial` fails because "x" of 25 is out of range [10, 12.5).
    created_trial: optuna.trial.FrozenTrial = optuna.trial.create_trial(
            value=12.5, params={"x": 25}, distributions={"x": optuna.distributions.UniformDistribution(10, 12.5)})
    study.add_trial(created_trial)
    print(f"#trials: {len(study.trials)}")


if __name__ == "__main__":
    main()
```

### Messages

```
[I 2020-12-21 14:53:24,906] A new study created in memory with name: no-name-dc249ffa-7848-4978-91ac-c7b225af66b7
optuna_enque_trial.py:13: ExperimentalWarning: enqueue_trial is experimental (supported from v1.2.0). The interface can change in the future.
  study.enqueue_trial({"x": 10.0})
/home/masaki/ghq/github.com/optuna/optuna-1/optuna/study.py:508: ExperimentalWarning: create_trial is experimental (supported from v2.0.0). The interface can change in the future.
  create_trial(state=TrialState.WAITING, system_attrs={"fixed_params": params})
/home/masaki/ghq/github.com/optuna/optuna-1/optuna/study.py:508: ExperimentalWarning: add_trial is experimental (supported from v2.0.0). The interface can change in the future.
  create_trial(state=TrialState.WAITING, system_attrs={"fixed_params": params})
/home/masaki/ghq/github.com/optuna/optuna-1/optuna/trial/_trial.py:722: UserWarning: Fixed parameter 'x' with value 10.0 is out of range for distribution UniformDistribution(high=10.0, low=-10.0).
  "for distribution {}.".format(name, param_value, distribution)
[I 2020-12-21 14:53:24,908] Trial 0 finished with value: 4.256559233250073 and parameters: {'x': 8.513118466500146}. Best is trial 0 with value: 4.256559233250073.
[I 2020-12-21 14:53:24,909] Trial 1 finished with value: 3.488933323854152 and parameters: {'x': 6.977866647708304}. Best is trial 1 with value: 3.488933323854152.
[I 2020-12-21 14:53:24,909] Trial 2 finished with value: 1.3455788710416483 and parameters: {'x': 2.6911577420832966}. Best is trial 2 with value: 1.3455788710416483.
[I 2020-12-21 14:53:24,909] Trial 3 finished with value: 4.830891314161699 and parameters: {'x': -9.661782628323397}. Best is trial 2 with value: 1.3455788710416483.
[I 2020-12-21 14:53:24,910] Trial 4 finished with value: 3.5705145785856534 and parameters: {'x': 7.141029157171307}. Best is trial 2 with value: 1.3455788710416483.
[I 2020-12-21 14:53:24,910] Trial 5 finished with value: 3.3258106936840726 and parameters: {'x': -6.651621387368145}. Best is trial 2 with value: 1.3455788710416483.
[I 2020-12-21 14:53:24,910] Trial 6 finished with value: 0.005783954765097299 and parameters: {'x': 0.011567909530194598}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,911] Trial 7 finished with value: 4.1973437134341065 and parameters: {'x': 8.394687426868213}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,911] Trial 8 finished with value: 3.1145417102211006 and parameters: {'x': 6.229083420442201}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,911] Trial 9 finished with value: 2.6246967472930125 and parameters: {'x': 5.249393494586025}. Best is trial 6 with value: 0.005783954765097299.
#trials: 10
optuna_enque_trial.py:17: ExperimentalWarning: enqueue_trial is experimental (supported from v1.2.0). The interface can change in the future.
  study.enqueue_trial({"x": 10.0})
[I 2020-12-21 14:53:24,915] Trial 10 finished with value: 1.530986944051545 and parameters: {'x': -3.06197388810309}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,918] Trial 11 finished with value: 0.8162051678739417 and parameters: {'x': 1.6324103357478834}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,922] Trial 12 finished with value: 0.9711382119399752 and parameters: {'x': -1.9422764238799504}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,925] Trial 13 finished with value: 0.9127388412302655 and parameters: {'x': 1.825477682460531}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,927] Trial 14 finished with value: 0.8186470377419653 and parameters: {'x': -1.6372940754839307}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,930] Trial 15 finished with value: 1.032836673909391 and parameters: {'x': 2.065673347818782}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,933] Trial 16 finished with value: 2.344104167281403 and parameters: {'x': -4.688208334562806}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,936] Trial 17 finished with value: 0.11390406934796382 and parameters: {'x': 0.22780813869592764}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,939] Trial 18 finished with value: 1.9238645679333635 and parameters: {'x': 3.847729135866727}. Best is trial 6 with value: 0.005783954765097299.
[I 2020-12-21 14:53:24,942] Trial 19 finished with value: 0.05845397139511127 and parameters: {'x': -0.11690794279022254}. Best is trial 6 with value: 0.005783954765097299.
#trials: 20
optuna_enque_trial.py:22: ExperimentalWarning: create_trial is experimental (supported from v2.0.0). The interface can change in the future.
  value=45, params={"x": 90}, distributions={"x": optuna.distributions.UniformDistribution(0, 100)})
optuna_enque_trial.py:23: ExperimentalWarning: add_trial is experimental (supported from v2.0.0). The interface can change in the future.
  study.add_trial(created_trial)
#trials: 21
optuna_enque_trial.py:27: ExperimentalWarning: create_trial is experimental (supported from v2.0.0). The interface can change in the future.
  value=12.5, params={"x": 25}, distributions={"x": optuna.distributions.UniformDistribution(10, 12.5)})
Traceback (most recent call last):
  File "optuna_enque_trial.py", line 33, in <module>
    main()
  File "optuna_enque_trial.py", line 27, in main
    value=12.5, params={"x": 25}, distributions={"x": optuna.distributions.UniformDistribution(10, 12.5)})
  File "/home/masaki/ghq/github.com/optuna/optuna-1/optuna/_experimental.py", line 68, in new_func
    return func(*args, **kwargs)  # type: ignore
  File "/home/masaki/ghq/github.com/optuna/optuna-1/optuna/trial/_frozen.py", line 538, in create_trial
    trial._validate()
  File "/home/masaki/ghq/github.com/optuna/optuna-1/optuna/trial/_frozen.py", line 332, in _validate
    "{}.".format(param_value, param_name, distribution)
ValueError: The value 25 of parameter 'x' isn't contained in the distribution UniformDistribution(high=12.5, low=10).
```

**Comment by rsnitsch** [comment]
Yes, the docs should mention this. Not only the docs should be improved in this regard, but also the Warning that is issued, should emphasize that fixed/manual hyperparameter values provided by `enqueue_trial` are simply **discarded**. Actually, I think this is better handled by raising a `ValueError`. As it stands, the Warning just says "Value outside of distribution". It does not tell the user that the value is discarded _because of that_, although that's kinda important.

Then, again, I question if the current behavior shouldn't be regarded as a bug altogether. Not only is it not documented, it makes little sense to begin with, in my opinion. Why should the user not be able to specify fixed parameters outside of the usual distribution?

I tracked this behavior to the first commit that introduced the enqueue_trial feature. There, in the function _is_manual_param (since renamed to _is_fixed_param), it is checked whether the value is within the distribution: https://github.com/optuna/optuna/commit/5e36be52f6cbcdd677ad5d490715085997970303#diff-ad34e431ae3b554b537c040b232f54f4f4831cea3c20df279ccb9539560b5a81R484

The result of this check is returned by the function and then used by _suggest to decide whether the fixed value is used or discarded and replaced by a randomly sampled value: https://github.com/optuna/optuna/commit/5e36be52f6cbcdd677ad5d490715085997970303#diff-ad34e431ae3b554b537c040b232f54f4f4831cea3c20df279ccb9539560b5a81R448

I recommend to
- either raise a `ValueError` or similar if a fixed value is provided that is outside of distribution, and mention this restriction in the docs of `enqueue_trial`. This is much better than the current behavior (incomplete Warning and silently replacing the value with a randomly sampled one).
- or allow values outside of the distribution, but keep the current Warning, which would be totally appropriate and sufficient in this case.
