### ISSUE TITLE
Tensorboard integration breaks when using suggest_float with step parameter

### ISSUE THREAD

**Issue by SammyRamone** [optuna/optuna#2334]
The tensorboard integration throws an error if the `trial.suggest_float()` method is used with a `step` parameter. If no step parameter is given, it works fine.

## Expected behavior
Should not throw an error.

## Environment

- Optuna version: 2.5.0
- Python version: 3.6
- OS: Ubuntu 18.04
- (Optional) Other libraries and their versions: tensorboard 2.4.1, tensorflow 2.4.1

## Error messages, stack traces, or logs

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    study.optimize(objective, n_trials=10, timeout=600, callbacks=[tensorboard_callback])
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/_optimize.py", line 178, in _optimize_sequential
    callback(study, frozen_trial)
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/integration/tensorboard.py", line 41, in __call__
    self._initialization(study)
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/integration/tensorboard.py", line 102, in _initialization
    self._add_distributions(trial.distributions)
  File "/home/marc/.local/lib/python3.6/site-packages/optuna/integration/tensorboard.py", line 70, in _add_distributions
    param_name, hp.Discrete(param_distribution.low, param_distribution.high)
  File "/home/marc/.local/lib/python3.6/site-packages/tensorboard/plugins/hparams/summary_v2.py", line 500, in __init__
    self._values = list(values)
TypeError: 'float' object is not iterable

## Steps to reproduce

1. Use example from here https://github.com/optuna/optuna/blob/master/examples/tensorboard_simple.py
2. Change line 33 to `dropout_rate = trial.suggest_float("DROPOUT_RATE", 0.1, 0.2, step=0.001)`
3. Run and error is thrown
4. Remove `step=0.001`
5. Run and no error is thrown

**Comment by nzw0301** [comment]
I could reproduce the bug you reported. Indeed, when we use `trial.suggest_float` with the `step` argument, optuna evaluates `param_name, hp.Discrete(param_distribution.low, param_distribution.high)` in [TFboard integration](https://github.com/optuna/optuna/blob/master/optuna/integration/tensorboard.py). However, `hp.Discrete` takes only one argument: `values`, rather than two float values. I'm not familiar with this API, but i think that 

- `hp.Discrete(range(param_distribution.low, param_distribution.high, param_distribution.step))`
- `hp. RealInterval(param_distribution.low, param_distribution.high)`

can solve this issue instead of the current implementation.

**Comment by nzw0301** [comment]
Hi, @SammyRamone. If you use the master branch of optuna, the reported error does not appear :)
