### ISSUE TITLE
Tensorboard integration with integers for parameter boundaries

### ISSUE THREAD

**Issue by timonegk** [optuna/optuna#2337]
When using the `optuna.integration.tensorboard.TensorBoardCallback` with integer parameters for `suggest_uniform`, a `TypeError` is raised.

## Expected behavior
No TypeError should be raised, instead the integer should be casted to a float.

## Environment

- Optuna version: 2.5.0
- Python version: 3.7.5
- OS: Debian Testing
- (Optional) Other libraries and their versions: Tensorboard 2.4.1

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "tensorboard_test.py", line 13, in <module>
    study.optimize(objective, n_trials=10, timeout=600, callbacks=[tensorboard_callback])
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/_optimize.py", line 178, in _optimize_sequential
    callback(study, frozen_trial)
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/integration/tensorboard.py", line 41, in __call__
    self._initialization(study)
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/integration/tensorboard.py", line 102, in _initialization
    self._add_distributions(trial.distributions)
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/optuna/integration/tensorboard.py", line 62, in _add_distributions
    param_name, hp.RealInterval(param_distribution.low, param_distribution.high)
  File "/home/timon/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tensorboard/plugins/hparams/summary_v2.py", line 444, in __init__
    raise TypeError("min_value must be a float: %r" % (min_value,))
TypeError: min_value must be a float: 0
```

## Steps to reproduce

1. Execute the example below

## Reproducible examples (optional)

```python
import optuna
from optuna.integration.tensorboard import TensorBoardCallback

def objective(trial: optuna.trial.Trial) -> float:
    param = trial.suggest_uniform("param", 0, 1)
    return param**2

tensorboard_callback = TensorBoardCallback("logs/", metric_name="value")

study = optuna.create_study()
study.optimize(objective, n_trials=10, callbacks=[tensorboard_callback])
```

**Comment by himkt** [comment]
Thank you @timonegk for raising the issue. I reproduced the error and opened the PR #2343.
If you have some comments for the PR, please put them to the PR. 😸

**Comment by timonegk** [comment]
Thanks @himkt, the patch works for me.

**Comment by himkt** [comment]
Thank you @timonegk for raising the issue!
