### ISSUE TITLE
StorageInternalError (data exceeding max length) with TPESampler

### ISSUE THREAD

**Issue by ironv** [optuna/optuna#2462]
Using the following Optuna code

```
sampler = optuna.samplers.TPESampler(n_startup_trials=5)
pruner = optuna.pruners.MedianPruner(n_warmup_steps=10, interval_steps=4)
study = optuna.create_study(storage=f"sqlite:///{clargs['CHKPT_DIR']}/example.db", study_name="test"
                            , load_if_exists=True, sampler=sampler, pruner=pruner, direction="maximize")
```

I get the following error in one of the terminals when running in parallel.  I see a similar error here #2331  but here I am using the `sqlite`, `TPESampler` and it happens much sooner (neither of which may be relevant for fixing!).  Is there a programmatic way of doing the fix suggested there and will that even work here? 

```
[W 2021-03-10 06:23:17,129] Trial 6 failed because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ')
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 52, in _create_scoped_session
    yield session
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 643, in _update_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 242, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (7,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "mlp-sqlite.py", line 158, in __call__
    trainer.fit(FFNPL(params))
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 578, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 100, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1101, in call_hook
    trainer_hook(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 185, in on_validation_end
    callback.on_validation_end(self, self.lightning_module)
  File "/anaconda3/lib/python3.7/site-packages/optuna/integration/pytorch_lightning.py", line 49, in on_validation_end
    self._trial.report(current_score, step=epoch)
  File "/anaconda3/lib/python3.7/site-packages/optuna/trial/_trial.py", line 594, in report
    self.storage.set_trial_intermediate_value(self._trial_id, step, value)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 308, in set_trial_intermediate_value
    self._flush_trial(trial_id)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 427, in _flush_trial
    datetime_complete=updates.datetime_complete,
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 739, in _update_trial
    session.add(trial_model)
  File "/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 70, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 52, in _create_scoped_session
    yield session
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 643, in _update_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 242, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (7,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mlp-sqlite.py", line 187, in <module>
    study.optimize(obj, callbacks=[max_trial_callback])
  File "/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/anaconda3/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/anaconda3/lib/python3.7/site-packages/optuna/_optimize.py", line 164, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/anaconda3/lib/python3.7/site-packages/optuna/_optimize.py", line 262, in _run_trial
    raise func_err
  File "/anaconda3/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "mlp-sqlite.py", line 158, in __call__
    trainer.fit(FFNPL(params))
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 578, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 100, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1101, in call_hook
    trainer_hook(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 185, in on_validation_end
    callback.on_validation_end(self, self.lightning_module)
  File "/anaconda3/lib/python3.7/site-packages/optuna/integration/pytorch_lightning.py", line 49, in on_validation_end
    self._trial.report(current_score, step=epoch)
  File "/anaconda3/lib/python3.7/site-packages/optuna/trial/_trial.py", line 594, in report
    self.storage.set_trial_intermediate_value(self._trial_id, step, value)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 308, in set_trial_intermediate_value
    self._flush_trial(trial_id)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 427, in _flush_trial
    datetime_complete=updates.datetime_complete,
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 739, in _update_trial
    session.add(trial_model)
  File "/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda3/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 70, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
```

**Comment by nzw0301** [comment]
I think this is a known issue for distributed optimisation with SQLite. Optuna does not recommend SQLite for distributed optimisation:

> We do not recommend SQLite for distributed optimizations at scale because it may cause deadlocks and serious performance issues. Please consider to use another database engine like PostgreSQL or MySQL.
