### ISSUE TITLE
Kubernetes + MLflow example fails due to the MNIST download error 

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2513]
If we follow the instructions in `examples/kubernetes/mlflow/README.md` with current master (https://github.com/optuna/optuna/commit/bffdbdcd32cb88e2d886f3860b6bbfd85cb52565), the worker pods fail due to the MNIST download error like https://github.com/optuna/optuna/issues/2469. 

## Expected behavior

The worker pods succeed if we follow the instructions in `examples/kubernetes/mlflow/README.md`.

## Environment

- Optuna version: current master (https://github.com/optuna/optuna/commit/bffdbdcd32cb88e2d886f3860b6bbfd85cb52565)
- OS: macOS Catalina 10.15.7
- docker for mac 20.10.5
- kubernetes: minikube 1.18.1

## Error messages, stack traces, or logs
If we follow the instructions in `examples/kubernetes/mlflow/README.md` and check the log message, we get the following errors.
```
mamu@HideakinoMacBook-puro mlflow % kubectl logs worker-kg66q
/usr/local/lib/python3.7/site-packages/optuna/_experimental.py:83: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  ExperimentalWarning,
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
/usr/local/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:25: DeprecationWarning: Argument `val_percent_check` is now set by `limit_val_batches` since v0.8.0 and this argument will be removed in v0.10.0
  warnings.warn(*args, **kwargs)

  | Name  | Type       | Params
-------------------------------------
0 | model | Sequential | 72 K  
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /usr/src/MNIST/raw/train-images-idx3-ubyte.gz
0it [00:00, ?it/s][W 2021-03-23 11:49:21,342] Setting status of trial#4 as TrialState.FAIL because of the following error: <HTTPError 522: 'Origin Connection Time-out'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/optuna/study.py", line 734, in _run_trial
    result = func(trial)
  File "pytorch_lightning_distributed.py", line 110, in objective
    trainer.fit(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in fit
    results = self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1185, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 343, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 270, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, f'{mode}_dataloader'))
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 364, in request_dataloader
    dataloader = dataloader_fx()
  File "pytorch_lightning_distributed.py", line 91, in val_dataloader
    datasets.MNIST(DIR, train=False, download=True, transform=transforms.ToTensor()),
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
    self.download()
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 137, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 83, in download_url
    raise e
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 71, in download_url
    reporthook=gen_bar_updater()
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 522: Origin Connection Time-out
Traceback (most recent call last):
  File "pytorch_lightning_distributed.py", line 128, in <module>
    callbacks=[MLflowCallback(tracking_uri="http://mlflow:5000/", metric_name="val_accuracy")],
  File "/usr/local/lib/python3.7/site-packages/optuna/study.py", line 339, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/usr/local/lib/python3.7/site-packages/optuna/study.py", line 682, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/usr/local/lib/python3.7/site-packages/optuna/study.py", line 713, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/usr/local/lib/python3.7/site-packages/optuna/study.py", line 734, in _run_trial
    result = func(trial)
  File "pytorch_lightning_distributed.py", line 110, in objective
    trainer.fit(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in fit
    results = self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1185, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 343, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 270, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, f'{mode}_dataloader'))
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 364, in request_dataloader
    dataloader = dataloader_fx()
  File "pytorch_lightning_distributed.py", line 91, in val_dataloader
    datasets.MNIST(DIR, train=False, download=True, transform=transforms.ToTensor()),
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
    self.download()
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 137, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 83, in download_url
    raise e
  File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 71, in download_url
    reporthook=gen_bar_updater()
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 522: Origin Connection Time-out
0it [00:31, ?it/s]
```

## Steps to reproduce

Follow the instructions in `examples/kubernetes/mlflow/README.md`.

## Additional context (optional)

This bug was found in the discussion in https://github.com/optuna/optuna/pull/2472. Thanks @0x41head!

**Comment by 0x41head** [comment]
Issue fixed with PR #2514. Can be closed.
