### ISSUE TITLE
optuna/optuna/blob/master/examples/rl/sb3_simple.py AttributeError: 'DummyVecEnv' object has no attribute 'venv'

### ISSUE THREAD

**Issue by patterntrade** [optuna/optuna#2580]
### 🐛 Bug

In optuna/optuna/blob/master/examples/rl/sb3_simple.py

CartPole-type envs working, but not Atari envs. 

Only change: Line 30 changed to `ENV_ID = "AirRaid-v4"`

Complains: `AttributeError: 'DummyVecEnv' object has no attribute 'venv'`
(Also: `UserWarning: Training and eval env are not of the same type)`

```
 A new study created in memory with name: no-name-ce409574-70b2-4e87-bafa-e7064d74d8f0
/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/optuna/study.py:393: FutureWarning: `n_jobs` argument has been deprecated in v2.7.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.7.0.
  warnings.warn(
/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x7f70b3ee8ee0> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f70b248d7c0>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x7f70b3efddf0> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f70b248d940>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
[W 2021-04-11 19:00:38,748] Trial 0 failed because of the following error: AttributeError("'DummyVecEnv' object has no attribute 'venv'")
Traceback (most recent call last):
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "/home/usr/v_env/opt_uni_gpu.py", line 129, in objective
    model.learn(N_TIMESTEPS, callback=eval_callback)
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 190, in learn
    return super(A2C, self).learn(
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 227, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 174, in collect_rollouts
    if callback.on_step() is False:
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py", line 88, in on_step
    return self._on_step()
  File "/home/usr/v_env/opt_uni_gpu.py", line 102, in _on_step
    super()._on_step()
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py", line 358, in _on_step
    sync_envs_normalization(self.training_env, self.eval_env)
  File "/home/usr/.virtualenvs/v_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/__init__.py", line 69, in sync_envs_normalization
    eval_env_tmp = eval_env_tmp.venv
AttributeError: 'DummyVecEnv' object has no attribute 'venv'
```

### Expected behavior

Atari and custom env's to work just as well as EG CartPole

### System Info

* Ubuntu desktop
* All installed with pip
* 2x RTX 2070
* 48 GB RAM
* Python 3.8.5 64-bit
* Pytorch 1.8.1+cu102
* Gym version 0.18.0
* Stable_baselines3 1.0
* x86 architecture

### Checklist

- [v] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [v] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [v] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by nzw0301** [comment]
According to the error message, the bug is supposed to be unrelated to optuna.

**Comment by Crissman** [comment]
Closing this since bug appears unrelated to Optuna and no further clarification. Please feel free to open if there are indications this is an Optuna bug.

Thanks,
