### ISSUE TITLE
FloatingPointError due to underflow encountered in exp in TPE sampler since latest version

### ISSUE THREAD

**Issue by hugocool** [optuna/optuna#2639]
Since upgrading to the latest version optuna, an optimisation which used to work now doesn't even though it is the same dataset.
I get the same error on a different dataset and have included the code where i encounter the problem below.
The error does not happen in first ten trials, however after enough trials this error is encountered.

## Expected behavior

I expect the optuna TPE sampler to work, just like it did before.

## Environment

- Optuna version: 2.7.0
- Python version: 3.7
- OS: linux (google colab)
- xgboost version : 1.4.1

## Error messages, stack traces, or logs

```
[I 2021-05-03 20:06:30,229] Trial 41 finished with value: 58.96419669999999 and parameters: {'booster': 'gbtree', 'lambda': 0.10473082821492902, 'alpha': 0.0034424292875279952, 'subsample': 0.08381812656141696, 'max_depth': 1, 'min_child_weight': 15, 'eta': 0.33668240574729064, 'gamma': 0.003057081444431449, 'grow_policy': 'depthwise'}. Best is trial 9 with value: 55.697677600000006.
[I 2021-05-03 20:06:30,707] Trial 42 pruned. Trial was pruned at iteration 0.
[W 2021-05-03 20:06:30,716] Trial 43 failed because of the following error: FloatingPointError('underflow encountered in exp')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-22-46c8a6d0e2a1>", line 27, in objective
    "subsample": trial.suggest_float("subsample", 0, 1.0),
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 178, in suggest_float
    return self.suggest_uniform(name, low, high)
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 237, in suggest_uniform
    return self._suggest(name, distribution)
  File "/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py", line 717, in _suggest
    study, trial, name, distribution
  File "/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py", line 288, in sample_independent
    return self._sample_uniform(param_distribution, below_param_values, above_param_values)
  File "/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py", line 366, in _sample_uniform
    return self._sample_numerical(low, high, below, above)
  File "/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py", line 467, in _sample_numerical
    q=q,
  File "/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py", line 600, in _gmm_log_pdf
    return TPESampler._logsum_rows(-0.5 * mahalanobis + np.log(coefficient))
  File "/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py", line 689, in _logsum_rows
    return np.log(np.exp(x - m[:, None]).sum(axis=1)) + m
FloatingPointError: underflow encountered in exp
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-23-33764dde9087> in <module>()
      2 
      3 study = optuna.create_study(study_name=STUDY_NAME,direction=DIRECTION)
----> 4 study.optimize(objective, n_trials=N_OPTUNA_TRIALS)

13 frames
/usr/local/lib/python3.7/dist-packages/optuna/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    407             callbacks=callbacks,
    408             gc_after_trial=gc_after_trial,
--> 409             show_progress_bar=show_progress_bar,
    410         )
    411 

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     74                 reseed_sampler_rng=False,
     75                 time_start=None,
---> 76                 progress_bar=progress_bar,
     77             )
     78         else:

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    161 
    162         try:
--> 163             trial = _run_trial(study, func, catch)
    164         except Exception:
    165             raise

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    266 
    267     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 268         raise func_err
    269     return trial
    270 

/usr/local/lib/python3.7/dist-packages/optuna/_optimize.py in _run_trial(study, func, catch)
    215 
    216     try:
--> 217         value_or_values = func(trial)
    218     except exceptions.TrialPruned as e:
    219         # TODO(mamu): Handle multi-objective cases.

<ipython-input-22-46c8a6d0e2a1> in objective(trial)
     25         "lambda": trial.suggest_loguniform("lambda", 1e-7, 1.0),
     26         "alpha": trial.suggest_loguniform("alpha", 1e-7, 1.0),
---> 27         "subsample": trial.suggest_float("subsample", 0, 1.0),
     28 
     29         }

/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py in suggest_float(self, name, low, high, step, log)
    176                 return self.suggest_loguniform(name, low, high)
    177             else:
--> 178                 return self.suggest_uniform(name, low, high)
    179 
    180     def suggest_uniform(self, name: str, low: float, high: float) -> float:

/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py in suggest_uniform(self, name, low, high)
    235         self._check_distribution(name, distribution)
    236 
--> 237         return self._suggest(name, distribution)
    238 
    239     def suggest_loguniform(self, name: str, low: float, high: float) -> float:

/usr/local/lib/python3.7/dist-packages/optuna/trial/_trial.py in _suggest(self, name, distribution)
    715                 study = pruners._filter_study(self.study, trial)
    716                 param_value = self.study.sampler.sample_independent(
--> 717                     study, trial, name, distribution
    718                 )
    719 

/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py in sample_independent(self, study, trial, param_name, param_distribution)
    286 
    287         if isinstance(param_distribution, distributions.UniformDistribution):
--> 288             return self._sample_uniform(param_distribution, below_param_values, above_param_values)
    289         elif isinstance(param_distribution, distributions.LogUniformDistribution):
    290             return self._sample_loguniform(

/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py in _sample_uniform(self, distribution, below, above)
    364         low = distribution.low
    365         high = distribution.high
--> 366         return self._sample_numerical(low, high, below, above)
    367 
    368     def _sample_loguniform(

/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py in _sample_numerical(self, low, high, below, above, q, is_log)
    465             low=low,
    466             high=high,
--> 467             q=q,
    468         )
    469 

/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py in _gmm_log_pdf(self, samples, parzen_estimator, low, high, q)
    598             Z = np.sqrt(2 * np.pi) * sigmas
    599             coefficient = weights / Z / p_accept
--> 600             return TPESampler._logsum_rows(-0.5 * mahalanobis + np.log(coefficient))
    601         else:
    602             cdf_func = TPESampler._normal_cdf

/usr/local/lib/python3.7/dist-packages/optuna/samplers/_tpe/sampler.py in _logsum_rows(cls, x)
    687         x = np.asarray(x)
    688         m = x.max(axis=1)
--> 689         return np.log(np.exp(x - m[:, None]).sum(axis=1)) + m
    690 
    691     @classmethod

FloatingPointError: underflow encountered in exp
```

## Steps to reproduce

1. load data
2. define xgboost model, trial with cv metric
3. optimise hypers with 40+ trials

## Reproducible example

```python
from sklearn.datasets import load_diabetes
import pandas as pd

data = load_diabetes()
print(data.DESCR)
X = pd.DataFrame(data = data['data'],columns = data['feature_names'])
y = data['target']
X['sex'] = X['sex'].apply(lambda x: x>0)*1
X.rename(columns={"sex": "male"})

N_FOLDS = 10
XGB_OBJECTIVE = 'reg:squarederror'
XGB_EVAL_METRIC = 'rmse'
NUM_BOOST_ROUNDS=3000 #10000
EARLY_STOPPING_ROUNDS = 50 #200

N_OPTUNA_TRIALS = 100 #1000
STUDY_NAME = 'diabetes'
DIRECTION = 'minimize' #'maximize

xgb_params = {
    "objective": XGB_OBJECTIVE,
    "eval_metric": XGB_EVAL_METRIC,
    "sampling_method":'gradient_based',
    'tree_method': 'gpu_hist'
    }

import xgboost as xgb

xgb_full = xgb.DMatrix(X, label=y)  

def objective(trial):
    

    param = {
        **xgb_params,
        **{
        "booster": trial.suggest_categorical("booster", ["gbtree","dart"]),
        "lambda": trial.suggest_loguniform("lambda", 1e-7, 1.0),
        "alpha": trial.suggest_loguniform("alpha", 1e-7, 1.0),
        "subsample": trial.suggest_float("subsample", 0, 1.0),

        }
    }

    if param["booster"] == "gbtree" or param["booster"] == "dart":
        param["max_depth"] = trial.suggest_int("max_depth", 1, 9)
        param["min_child_weight"] = trial.suggest_int('min_child_weight', 1, 20)
        param["eta"] = trial.suggest_loguniform("eta", 1e-7, 1.0)
        param["gamma"] = trial.suggest_loguniform("gamma", 1e-7, 1.0)
        param["grow_policy"] = trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"])
    if param["booster"] == "dart":
        param["sample_type"] = trial.suggest_categorical("sample_type", ["uniform", "weighted"])
        param["normalize_type"] = trial.suggest_categorical("normalize_type", ["tree", "forest"])
        param["rate_drop"] = trial.suggest_loguniform("rate_drop", 1e-7, 1.0)
        param["skip_drop"] = trial.suggest_loguniform("skip_drop", 1e-7, 1.0)

    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, f"test-{XGB_EVAL_METRIC}")

    xgb_cv_results = xgb.cv(
        param,
        xgb_full,
        num_boost_round=NUM_BOOST_ROUNDS,
        early_stopping_rounds = EARLY_STOPPING_ROUNDS,
        nfold=N_FOLDS,
        callbacks=[pruning_callback],
        )

    trial.set_user_attr("n_estimators", len(xgb_cv_results))

    best_score = xgb_cv_results[f"test-{XGB_EVAL_METRIC}-mean"].values[-1]

    return best_score

import optuna

study = optuna.create_study(study_name=STUDY_NAME,direction=DIRECTION)
study.optimize(objective, n_trials=N_OPTUNA_TRIALS)


```

**Comment by zhenyokmsk** [comment]
Same problem with Optuna 2.7.0 in Conda
```
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\trial\_trial.py", line 176, in suggest_float
    return self.suggest_loguniform(name, low, high)
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\trial\_trial.py", line 291, in suggest_loguniform
    return self._suggest(name, distribution)
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\trial\_trial.py", line 716, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 290, in sample_independent
    return self._sample_loguniform(
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 377, in _sample_loguniform
    return self._sample_numerical(low, high, below, above, is_log=True)
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 462, in _sample_numerical
    log_likelihoods_above = self._gmm_log_pdf(
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 600, in _gmm_log_pdf
    return TPESampler._logsum_rows(-0.5 * mahalanobis + np.log(coefficient))
  File "C:\Users\genie\.conda\envs\keras\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 689, in _logsum_rows
    return np.log(np.exp(x - m[:, None]).sum(axis=1)) + m
FloatingPointError: underflow encountered in exp
```

**Comment by nzw0301** [comment]
@zhenyokmsk could you share the reproducible code?

**Comment by nzw0301** [comment]
@hugocool I'm sorry for the late response. Thank you for sharing the reproducible codes. I'm afraid that it takes too much time to reach 40+ trials on colab -- I cannot get the error. I'm wondering whether there is a simpler example to get the error. 

Best regards,

**Comment by not522** [comment]
I found the following code raises the same error. We need to ignore underflow using `numpy.seterr(under='ignore')`.

```python
import numpy as np
import optuna

def objective(trial):
    return trial.suggest_float("x", -10, 10)

np.seterr(under='raise')
study = optuna.create_study()
study.optimize(objective)
```

**Comment by not522** [comment]
`np.errstate` avoids this problem.

```python
import numpy as np
import optuna

def objective(trial):
    return trial.suggest_float("x", -10, 10)

study = optuna.create_study()
with np.errstate(under='ignore'):
    study.optimize(objective)
```

Let me close this issue. If the above workaround does not resolve your problem, please reopen it freely.
