### ISSUE TITLE
Trial will not be saved if database file is removed after start

### ISSUE THREAD

**Issue by pyscorcher** [optuna/optuna#2722]
If we start a trial which creates a new study (that is, also creates a new sqlite database file), and then *remove* said database file before the trial has finished, the data of that trial is lost.

## Expected behavior

I understand that for an efficient distributed training the database file needs to be created *first*, but it would make sense to create a new database file at the *end* of a trial if it doesn't exist anymore.  This would be especially helpful for trials that take very long.

## Environment

- Optuna version: 2.7
- Python version: 3.9
- OS: Ubuntu 18.04

## Error messages, stack traces, or logs

If we do remove the database file during the first trial, following error will occur at the end of said trial:
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/_optimize.py", line 244, in _run_trial
    study.tell(trial, values=values, state=state)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/study.py", line 664, in tell
    self._storage.set_trial_state(trial_id, state)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 214, in set_trial_state
    return self._flush_trial(trial_id)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 427, in _flush_trial
    return self._backend._update_trial(
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 668, in _update_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 243, in find_or_raise_by_id
    raise KeyError(NOT_FOUND_MSG)
KeyError: 'Record does not exist.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/proj/script.py", line 91, in <module>
    main()
  File "/home/user/proj/script.py", line 86, in main
    study.optimize(objective, n_trials=100)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/study.py", line 400, in optimize
    _optimize(
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/_optimize.py", line 249, in _run_trial
    study._log_completed_trial(trial, cast(List[float], values))
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/study.py", line 1014, in _log_completed_trial
    self.best_trial.number,
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 284, in get_best_trial
    return self._backend.get_best_trial(study_id)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 1112, in get_best_trial
    _directions = self.get_study_directions(study_id)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 340, in get_study_directions
    study = models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/opt/anaconda3/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 55, in find_or_raise_by_id
    raise KeyError(NOT_FOUND_MSG)
KeyError: 'Record does not exist.'

```

## Steps to reproduce

1. Create new trial witha new study with sqlite database file. Make sure the trial takes long enough.
2. Remove/Rename the database file during this trial.
3. Observe the error at the end of the trial

**Comment by nzw0301** [comment]
could you explain why do you remove the database...?

**Comment by pyscorcher** [comment]
It could be any number of reasons, maybe just an accidental deletion (e.g. with the version control system), a connection issue an issue of swapping out database files etc.

**Comment by Crissman** [comment]
I'm afraid removal of the DB is not an issue that Optuna should be able to handle. 🙇  Closing this issue.
