### ISSUE TITLE
`Checks` CI job fails with missing `toml` dependency

### ISSUE THREAD

**Issue by xadrianzetx** [optuna/optuna#2813]
Black in latest release [switched from using `toml` to `tomli`](https://github.com/psf/black/pull/2301). Since `toml` is no longer installed in `Checks` workflow, `blackdoc` will fail the CI job.

## Expected behavior

`toml` should be installed when CI job runs `pip install --progress-bar off -U .[checking]`

## Environment

- Optuna version: 2.9.0.dev0
- Python version: Any
- OS: Any

## Error messages, stack traces, or logs
In `Checks` CI job
```
Run blackdoc . --check --diff
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/bin/blackdoc", line 5, in <module>
    from blackdoc.__main__ import main
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/blackdoc/__main__.py", line 12, in <module>
    from .blackcompat import (
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/blackdoc/blackcompat.py", line 9, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```
[Example](https://github.com/optuna/optuna/pull/2810/checks?check_run_id=3088486083)

## Steps to reproduce

1.  Push the code to trigger `Checks` CI job

**Comment by xadrianzetx** [comment]
Closing, since `blackdoc` added `toml` as dependency in [latest release](https://github.com/keewis/blackdoc/releases/tag/v0.3.4).
