### ISSUE TITLE
NSGA2 _collect_parent_population picking up pruned trials

### ISSUE THREAD

**Issue by TalhaAsmal** [optuna/optuna#2853]
When running Optuna with multiple objectives (2 in my case), the NSGA2 sampler picks up pruned trials of previous generations, resulting in failure in `_dominates` due to the `trial.values` being `None`

## Expected behavior

The parent selection and subsequent parameter selection to work without throwing an error

## Environment

- Optuna version: 2.9.1
- Python version: 3.6.8
- OS: Windows-10-10.0.19041-SP0

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\study\_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\study\_optimize.py", line 194, in _run_trial
    trial = study.ask()
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\study\study.py", line 486, in ask
    trial = trial_module.Trial(self, trial_id)
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\trial\_trial.py", line 57, in __init__
    self._init_relative_params()
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\trial\_trial.py", line 67, in _init_relative_params
    study, trial, self.relative_search_space
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\samplers\_nsga2.py", line 161, in sample_relative
    study, [t for t in parent_population if t._trial_id != p0._trial_id]
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\samplers\_nsga2.py", line 302, in _select_parent
    if dominates(candidate0, candidate1, study.directions):
  File "K:\python_virtual_envs\numerai\lib\site-packages\optuna\study\_multi_objective.py", line 68, in _dominates
    assert values0 is not None
AssertionError
python-BaseException

Process finished with exit code 1
```

## Steps to reproduce

1. Use multi-objective optimizer
2. Have pruned trials
3. Run study.optimize() until failure

## Reproducible examples (optional)

```python
# python code
```

## Additional context (optional)

I'm not 100% sure, but I believe the root issue may be that pruned trials are being added to the list of `nsga2:population:<cache_key>` values in study_system_attributes table. This is then pulled in `NSGAIISampler._collect_parent_population()`  (_nsga2.py line 253) 

Not sure what the impact would be, but a potential fix is to amend line 258 to:
`population = [trials[n] for n in cached_population_numbers if trials[n].state == optuna.trial.TrialState.COMPLETE]`

**Comment by nzw0301** [comment]
I think the current pruners cannot be used with multi-objective optimisation.

**Comment by nzw0301** [comment]
As commented above, we cannot use the multi-objective function and pruning feature at the same time yet. In addition, the code has not been shared to reproduce the results. Let me close the issue, but please feel free to re-open by following the issue template.
