### ISSUE TITLE
unhashable type: 'list' by plot parallel coordinate

### ISSUE THREAD

**Issue by Zepp3** [optuna/optuna#3093]
I get this weird error that I don't receive with optuna optimizations that are quite the same and can not explain how this error occurs.

This is how  I implemented the optimization:
```
    study = optuna.create_study(storage=optuna.storages.RDBStorage("sqlite:///" + database_name + ".db"), 
                                study_name = database_name + "_study", direction="maximize", load_if_exists=True) 
    study.optimize(lambda trial: objective(trial, preprocessed_dataset, dataset_val, num_samples, database_name, *shift_numbers), n_trials)
    
    # plots of optuna optimization
    fig1 = optuna.visualization.matplotlib.plot_optimization_history(study)
    fig2 = optuna.visualization.matplotlib.plot_parallel_coordinate(study)
    fig3 = optuna.visualization.matplotlib.plot_contour(study)
    fig4 = optuna.visualization.matplotlib.plot_slice(study)
    fig5 = optuna.visualization.matplotlib.plot_param_importances(study)
    fig6 = optuna.visualization.matplotlib.plot_edf(study)
    plt.show()
```

### Environment
- Optuna version: 2.10.0
- Python version: 3.8.10
- OS: Linux-5.4.0-81-generic-x86_64-with-glibc2.29
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs
This is the error I get:

```
Traceback (most recent call last):
  File "CTGAN_noscale.py", line 286, in <module>
    run_CTGAN(num_samples, n_trials, database_name, *shift_numbers)
  File "CTGAN_noscale.py", line 243, in run_CTGAN
    fig4 = optuna.visualization.matplotlib.plot_parallel_coordinate(study)
  File "/usr/local/lib/python3.8/dist-packages/optuna/_experimental.py", line 68, in new_func
    return func(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/optuna/visualization/matplotlib/_parallel_coordinate.py", line 90, in plot_parallel_coordinate
    return _get_parallel_coordinate_plot(study, params, target, target_name)
  File "/usr/local/lib/python3.8/dist-packages/optuna/visualization/matplotlib/_parallel_coordinate.py", line 159, in _get_parallel_coordinate_plot
    values = [vocab[v] for v in values]
  File "/usr/local/lib/python3.8/dist-packages/optuna/visualization/matplotlib/_parallel_coordinate.py", line 159, in <listcomp>
    values = [vocab[v] for v in values]
TypeError: unhashable type: 'list'
```

Has anyone else already got this problem?

**Comment by nzw0301** [comment]
could you follow the issue template?

**Comment by nzw0301** [comment]
I suppose you might sample a list via `suggest_categorical`, right? As explained in the [documentation](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_categorical), we assume that `choices` should take `[None, bool, int, float, str]`.

**Comment by Zepp3** [comment]
```
    embedding_dim = trial.suggest_categorical("embedding_dim", [8, 16, 32, 64, 128])
    generator_dim = trial.suggest_categorical("generator_dim", [(16, 16), (32, 32), (64, 64), (128, 128), (256, 256)])
    discriminator_dim = trial.suggest_categorical("discriminator_dim",
                                                  [(16, 16), (32, 32), (64, 64), (128, 128), (256, 256), (512, 512)])
    generator_lr = trial.suggest_categorical("generator_lr", [0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5])
    generator_decay = trial.suggest_categorical("generator_decay", [1e-6, 1e-7, 1e-8, 1e-9, 1e-10])
    discriminator_lr = trial.suggest_categorical("discriminator_lr", [0.5, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5])
    discriminator_decay = trial.suggest_categorical("discriminator_decay",
                                                    [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10])
    batch_size = trial.suggest_categorical("batch_size", [10, 100, 1000])
    discriminator_steps = trial.suggest_int("discriminator_steps", 1, 10, 1)
    epochs = trial.suggest_categorical("epochs", [100, 1000, 10000])
```
Thank you for your answer. So the problem could be due to me passing tuples to `suggest_categorical` like in the snippet above?

**Comment by nzw0301** [comment]
As

**Comment by nzw0301** [comment]
Yes, as I explained in the previous my comment.

**Comment by himkt** [comment]
```python
# (a) list
discriminator_dims_index = trial.suggest_categorical("discriminator_dims_index", [0, 1, 2, 3, 4])
discriminator_dims = [(16, 16), (32, 32), (64, 64), (128, 128), (256, 256)][discriminator_dims_index]

# (b) dictionary
discriminator_dims_dict = {
  "small": (16, 16),  # assign a name for each dims pair
  ....,
  "large": (256, 256),
)
discriminator_dims_key = trial.suggest_categorical("discriminator_dims_key", ["smal", ..., "large"])
discriminator_dims = discriminator_dims_dict[discriminator_dims_key]
```

You can avoid the problem to suggest an index or key instead.

**Comment by nzw0301** [comment]
I suppose that sampling index/key might not be useful for visualisation that is the main concern in this issue. As a workaround, I suggest that `choices`  is converted to str's list: `["16, 16", "32,32", ...]` and transform sampled value to  the tuple of int, eg., `(16, 16)` before passing to your GANs.

**Comment by nzw0301** [comment]
As @himkt suggested, using a dictionary is a good alternative, where the key is str, `16,16` and its value is  `(16, 16)`.

**Comment by Zepp3** [comment]
Okay, thank you for your tips, they'll be very useful for me in the future.
