### ISSUE TITLE
Cannot change attributes of finished trial

### ISSUE THREAD

**Issue by thorstenwagner** [optuna/optuna#3198]
Hi,

I really like optuna, thanks for this great tool :-)

However, I get many failed trials with the following error message:
```
Traceback (most recent call last):
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/tomotwin/train_optuna.py", line 157, in objective
    trial.report(val_loss, epoch)
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/optuna/trial/_trial.py", line 597, in report
    self.storage.set_trial_intermediate_value(self._trial_id, step, value)
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 318, in set_trial_intermediate_value
    self._flush_trial(trial_id)
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 428, in _flush_trial
    return self._backend._update_trial(
  File "/u/twagner/conda-envs/tomotwin_opt/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 671, in _update_trial
    raise RuntimeError("Cannot change attributes of finished trial.")
RuntimeError: Cannot change attributes of finished trial.

```

Here are some statistics about the study:
```
Number of finished trials:  67
Pruned: 22
Completed: 12
Failed: 22
Waiting: 0
Running: 11
```
BTW: Why are running trials listed as finished trials?

Here is how I setup the study:
https://gist.github.com/thorstenwagner/bde99f26295809882ab3315ad8be0b5b

And this is my objective:
https://gist.github.com/thorstenwagner/5e39db92b0198021ee194fcf42730ae3

Can someone tell me what is wrong in my setup?

**Comment by himkt** [comment]
Hello @thorstenwagner, thank you so much for using Optuna and I'm sorry to hear that.
Does the problem occur on the single node + single process execution?
And what happens if it disables heartbeat feature on the multi node + parallel execution (=current your workload)?

I'm not familiar with GPFS at all but I couldn't find any suspicious point on your codebase except to using sqlite3 on shared filesystem. (Is it difficult to use MySQL or PostgreSQL for the experiment?)

**Comment by thorstenwagner** [comment]
Hi @himkt ,

the problem also occurs locally on my computer (running 2 processes on two GPUs). I don't have a parallel file system locally. So I don't think that the parallel file system is problem? I will try single process execution, but I don't expect the problem there.

I didn't find a way yet to make it easily reproducible. But it happens often.

On the HPC, where I run the experiments, it is indeed difficult to get MySQL working. The administrators just asked me to use hyperopt instead (which I don't want ^^).

I think I took the heartbeat option from one of the examples. To be honest, I'm not sure what it actually does. Maybe you can explain? :-)

Best,
Thorsten

**Comment by himkt** [comment]
@thorstenwagner 

Thank you for explaining, I think I understand your situation.

> The problem also occurs locally on my computer (running 2 processes on two GPUs)

Hmm, I see. I didn't reproduce the problem with a simple sample...
If you find the way to reproduce, please tell me. It would help us a lot.

> To be honest, I'm not sure what it actually does. Maybe you can explain? :-)

OK. I try to explain it. In some situation, processes running trials are killed suddenly. Typical cases are `spot instance` on AWS and `preemptive instance` on GCP. If processes are killed in such ways, trials whose states are `running` leave in the study. Heartbeat will check if each process is alive by sending a ping and finish a trial if the process doesn't respond to the signal by changing the state of the process from `running` to `fail`.

🔗 `Heartbeat` in https://github.com/optuna/optuna/releases/tag/v2.5.0.
🔗  `optuna.storages.RetryFailedTrialCallback Added` in https://github.com/optuna/optuna/releases/tag/v2.8.0

If you don't have to pay attention to the process interruption, you can simply use cached storage by the following code

```python
study = optuna.create_study(
    direction=PARAMS["general"]["minmax"],
    sampler=TPESampler(),
    pruner=MedianPruner(n_warmup_steps=N_WARMUP_STEPS),
    study_name = STUDY_NAME,
    storage=f"sqlite:///{STUDY_NAME}.db",
    load_if_exists=True
)
```

instead of

```python
storage = optuna.storages.RDBStorage(
    url=f"sqlite:///{STUDY_NAME}.db",
    engine_kwargs={
        'connect_args': {
            'timeout': 60000
        }
    },
    heartbeat_interval=1,
    failed_trial_callback=RetryFailedTrialCallback(max_retry=MAX_RETRY),
)

study = optuna.create_study(
    direction=PARAMS["general"]["minmax"],
    sampler=TPESampler(),
    pruner=MedianPruner(n_warmup_steps=N_WARMUP_STEPS),
    study_name = STUDY_NAME,
    storage=storage,
    load_if_exists=True
)
```

**Comment by thorstenwagner** [comment]
Hi, thanks for the information!

I think I need to pay attention to killed processes, because one the HPC we have a 24h time limit per process and it might be that some training configurations might take longer than 24h, which means that need to be restarted where they stop. Right?

**Comment by himkt** [comment]
It makes sense. Your situation is one of our intended case!
(I also want to know if the problem still occurs disabling heartbeat, which could be the help for the investigation)

**Comment by thorstenwagner** [comment]
How can I imagine the connection between Heartbeat and the I get? Can you maybe explain me the intuition? Can increasing it from 1 to 60 help?

**Comment by himkt** [comment]
> Can you maybe explain me the intuition?

I'm just wondering if the heartbeat is related to the problem. heartbeat is experimental and it could include some points we have to take care. And I think it doesn't matter how long heartbeat interval.

**Comment by thorstenwagner** [comment]
I will setup an experiment without heartbeat. Without heartbeat, will RetryFailedTrialCallback still work in case of in interruption by HPC? I don't think so, right?

**Comment by thorstenwagner** [comment]
Alright: 

- On HPC1 I started 6 parallel runs **without** heartbeat but with a hpc timelimit of 2h. 
- On HPC2 I started 6 parallel runs **with** heartbeat (but 60) and a HPC timelimit of 24.

**Comment by himkt** [comment]
> Without heartbeat, will RetryFailedTrialCallback still work in case of in interruption by HPC? I don't think so, right?

You're right. If you want to retry killed trials, you need heartbeat.
(So, disabling heartbeat is only for the investigation :bow:)

**Comment by thorstenwagner** [comment]
OK, both runs don't have any `Cannot change attributes of finished trial` errors.

The run on HPC1 didnt finish any job, but the reason is that I set max restarts to 3, so it was not able to finish a single training. That might also be the reason why we didnt see any `Cannot change attributes of finished trials`, because I think it happens at the end of a trial.

The run on HPC2 also has some failed runs, but the reason is here that the network got a loss of nan during training.

My conclusion so far: Too low heartbeat values leads to problems?

**Comment by thorstenwagner** [comment]
OK, both runs don't have any `Cannot change attributes of finished trial` errors.

The run on HPC1 didnt finish any job, but the reason is that I set max restarts to 3, so it was not able to finish a single training. That might also be the reason why we didnt see any `Cannot change attributes of finished trials`, because I think it happens at the end of a trial.

The run on HPC2 also has some failed runs, but the reason is here that the network got a loss of nan during training.

My preliminary conclusion so far: Too low heartbeat values leads to problems?

**Comment by thorstenwagner** [comment]
Just got the error again locally. With heartbeat 60 :-(

**Comment by himkt** [comment]
Hmm... Sorry but I don't have any idea for the cause at this time. I'll try some experiments on this weekend to reproduce.
Please share us if you find minimum reproducible code.

**Comment by thorstenwagner** [comment]
Alright, switching from sqlite to MySQL sloved the problem

But that also means, that sqlite is a problem even on non-parallelized file systems.

But with MySQL everything works fine so far :-)

I close the issue.
