### ISSUE TITLE
Trial 0 failed, because the value None could not be cast to float.

### ISSUE THREAD

**Issue by pengzhangzhi** [optuna/optuna#3361]
### Environment

- Optuna version: 2.10.0
- Python version: 3.8
- OS: linux
- (Optional) Other libraries and their versions:

### Description

Hi. I used optuna with pytorch. I followed your official example and it shows this expcetion.  I have looked up issues and stackoverflow and did not work it out. The most relevant solution is :

**Sounds like an exception in your optimization function. You should start by debugging into your model training function. When the value returned is None, it means your function is failing before it finishes. Start with some basics (`try...except`) and look into the stack trace.**
_Originally posted by @blaney83 in https://github.com/optuna/optuna/issues/2320#issuecomment-774523967_

I have the 'try .. except' on my code, which did not show any exceptions in the objective function.  I have checked my code thousand times and none of bug are discovered. It is exhausted.  I need you help!

Any suggestions would be much appreciated.

### Error messages, stack traces, or logs

```shell
[train epoch 0] MSELoss: 2.226, RMSE: 1.492: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1109/1109 [00:38<00:00, 29.02it/s]
[val epoch 0] MSELoss: 17.598, RMSE: 4.195: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:01<00:00, 89.02it/s]
run time is 0.77 min
[W 2022-03-08 00:43:33,606] Trial 0 failed, because the value None could not be cast to float.
Study statistics: 
  Number of finished trials:  1
  Number of pruned trials:  0
  Number of complete trials:  0
Best trial:
Traceback (most recent call last):
  File "search_param.py", line 94, in <module>
    trial = study.best_trial
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/optuna/study/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 311, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
```

### Steps to reproduce

Here I paste my python script.

```python

import optuna
from optuna.trial import TrialState
from utils import evaluate
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data
from STTransformer import create_model
from help_funcs import EarlyStop, print_run_time, read_config_class
from train import get_loaders, get_optim

from utils import reproducibility, train_one_epoch


@print_run_time
def objective(trial):
    """
    :param args: arg class.
    """
    try:
        args = read_config_class("arg")
        args.lr = trial.suggest_float("lr", 0.005, 0.01, log=True)
        args.batch_size = trial.suggest_categorical("batch_size",[32,62,128,256,512])
        args.epochs = trial.suggest_int("epochs",500,700,50)
        args.conv_channels = trial.suggest_int("conv_channels",32,256,32)
        args.patch_size = trial.suggest_categorical("patch_size",[2,4,8,16])
        args.close_dim = trial.suggest_categorical("close_dim",[128,64,32,256])
        args.trend_dim = trial.suggest_categorical("trend_dim",[128,64,32,256])
        args.close_depth = trial.suggest_categorical("close_depth",[1,2,3,4,5,6,7,8])
        args.trend_depth = trial.suggest_categorical("trend_depth",[1,2,3,4,5,6,7,8])
        args.close_head = trial.suggest_categorical("close_head",[1,2,3,4])
        args.trend_head = trial.suggest_categorical("trend_head",[1,2,3,4])
        args.close_mlp_dim = trial.suggest_categorical("close_mlp_dim",[128,256,512,1024])
        args.trend_mlp_dim = trial.suggest_categorical("trend_mlp_dim",[128,256,512,1024])
        device = args.device


        # save print info to log.txt

        train_loader, val_loader, test_loader = get_loaders(args)

        model = create_model(arg=args)
    

        optimizer, scheduler = get_optim(model, args)
    
        for epoch in range(args.epochs):
            # train
            train_loss, train_rmse = train_one_epoch(model=model,
                                                    optimizer=optimizer,
                                                    data_loader=train_loader,
                                                    device=device,
                                                    epoch=epoch)

            # print("train:",train_loss, train_rmse)
            scheduler.step()

            # validate
            val_loss, val_rmse,val_ape = evaluate(model=model,
                                        data_loader=val_loader,
                                        device=device,
                                        epoch=epoch)

            # print("val:", val_loss, val_rmse)

            # results = [train_loss, train_rmse, val_loss, val_rmse, optimizer.param_groups[0]["lr"]]


        trial.report(val_loss, epoch)
        if trial.should_prune():
                raise optuna.exceptions.TrialPruned()
    
    except Exception as e:
        print(e)
    return val_rmse


if __name__ == '__main__':
    
    study = optuna.create_study(direction="minimize",sampler=optuna.samplers.TPESampler())
    study.optimize(objective, n_trials=1, timeout=1)

    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

    print("Study statistics: ")
    print("  Number of finished trials: ", len(study.trials))
    print("  Number of pruned trials: ", len(pruned_trials))
    print("  Number of complete trials: ", len(complete_trials))

    print("Best trial:")
    trial = study.best_trial

    print("  Value: ", trial.value)

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))
```

**Comment by nzw0301** [comment]
Could you check `val_rmse` is not `None`?

**Comment by pengzhangzhi** [comment]
> Could you check `val_rmse` is `None`? If so, please make sure `evaluate` returns not `None` value to complete the trial.

I checked  `val_rmse`, which is not none. It is a float. I even return other variables like val_mse. It still has the same error.

**Comment by pengzhangzhi** [comment]
> Could you check `val_rmse` is `None`? If so, please make sure `evaluate` returns not `None` value to complete the trial.

I write:
```python
print("Val_RMSE:",val_rmse,type(val_rmse))
```
outputs:
```shell
Val_RMSE: 10.537247763425857 <class 'float'>
run time is 1.03 min
[W 2022-03-08 14:41:07,930] Trial 0 failed, because the value None could not be cast to float.
Study statistics: 
  Number of finished trials:  1
  Number of pruned trials:  0
  Number of complete trials:  0
Best trial:
Traceback (most recent call last):
  File "search_param.py", line 93, in <module>
    trial = study.best_trial
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/optuna/study/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 311, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
```

**Comment by nzw0301** [comment]
Yeah, I'm thinking the exact same thing. I think if `print_run_time` returns the function, the bug does not happen. Anyway, I'm glad to hear you resolve the issue 👍🏻
