### ISSUE TITLE
Can't run `create_trial` more than once when reporting multiple objective values

### ISSUE THREAD

**Issue by xadrianzetx** [optuna/optuna#3416]
### Expected behavior

I should be able to  manually create arbitrary number of trials with sequence of objective values, same as with single objective value.

### Environment

- Optuna version: 3.0.0b0.dev
- Python version: 3.8.10
- OS: Ubuntu 20.04.4
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "buggy.py", line 6, in <module>
    study.add_trial(create_trial(values=[0.0, 0.1]))
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/study/study.py", line 955, in add_trial
    self._storage.create_new_trial(self._study_id, template_trial=trial)
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 203, in create_new_trial
    self._update_cache(trial_id, study_id)
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 361, in _update_cache
    if best_trial.value is None:
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/trial/_frozen.py", line 395, in value
    raise RuntimeError(
RuntimeError: This attribute is not available during multi-objective optimization.
```

### Steps to reproduce

Minimal reproducible code
```python
from optuna.study import create_study
from optuna.trial import create_trial

study = create_study()
study.add_trial(create_trial(values=[0.0, 0.1]))  # :^)
study.add_trial(create_trial(values=[0.0, 0.1]))  # :^(
```

### Additional context (optional)

Seems like it's raised from [`_update_cache`](https://github.com/optuna/optuna/blob/d529ffe58810c2d4ac1439d98049b175e93122f7/optuna/storages/_in_memory.py#L331-L363) which does not handle trials with multiple objective values. I suspect the same error exists in redis storage. Just had a quick look, but happy to come back and fix it later.

**Comment by xadrianzetx** [comment]
Closing, caused by me forgeting to set multiple directions in study :facepalm:.

```python
from optuna.study import create_study
from optuna.trial import create_trial

study = create_study(drections=["minimize", "maximize"])
study.add_trial(create_trial(values=[0.0, 0.1]))  # :^)
study.add_trial(create_trial(values=[0.0, 0.1]))  # :^)
```
