### ISSUE TITLE
Problem with converting string to float in target feature, during study.optimize

### ISSUE THREAD

**Issue by ZetaRR** [optuna/optuna#3473]
### Environment

- Optuna version: 2.10.0
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

I have this code for making optimization with Optuna: 

```python
n_trials = 25
    def objective(trial):
      params = {
          "n_estimators": trial.suggest_int("n_estimators", 100, 900),
          "max_depth": trial.suggest_int("max_depth", 5, 15),
          "min_samples_split": trial.suggest_int("min_samples_split", 2 ,6)
      }
    
      rfc = RandomForestClassifier(**params)
      rfc.fit(X_train_res, y_train_res)
      y_pred = rfc.predict(X_test)
      score = metrics.r2_score(y_test, y_pred)
      
      return score
    
    study = optuna.create_study(study_name = "RandomForestRegressor", direction="maximize")
    study.optimize(objective, n_trials)
    
    print("Number of completed trials: {}".format(len(study.trials)))
    print("Best trial:")
    trial = study.best_trial
    
    print("\tBest Score: {}".format(trial.value))
```

Here is my y_train_res that contains "Techonology value"
```
array(['Finance & Investments', 'Technology', 'Technology', 'Technology',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Technology', 'Technology',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Technology', 'Finance & Investments', 'Finance & Investments',
       'Technology', 'Finance & Investments', 'Technology',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Technology',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Technology', 'Technology',
       'Technology', 'Technology', 'Technology', 'Finance & Investments',
       'Technology', 'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Technology',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Technology', 'Technology', 'Technology', 'Technology',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Technology', 'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Finance & Investments', 'Finance & Investments', 'Technology',
       'Technology', 'Technology', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Finance & Investments',
       'Technology', 'Finance & Investments', 'Finance & Investments',
       'Finance & Investments', 'Technology', 'Technology',
```

### Error messages, stack traces, or logs

```shell
[I 2022-04-15 01:25:07,103] A new study created in memory with name: RandomForestRegressor
[W 2022-04-15 01:25:08,508] Trial 0 failed because of the following error: ValueError("could not convert string to float: 'Technology'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-582-e81cfbdedef0>", line 14, in objective
    score = metrics.r2_score(y_test, y_pred)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_regression.py", line 790, in r2_score
    y_true, y_pred, multioutput
  File "/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_regression.py", line 95, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 746, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 857, in __array__
    return np.asarray(self._values, dtype)
ValueError: could not convert string to float: 'Technology'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-582-e81cfbdedef0> in <module>()
     17 
     18 study = optuna.create_study(study_name = "RandomForestRegressor", direction="maximize")
---> 19 study.optimize(objective, n_trials)
     20 
     21 print("Number of completed trials: {}".format(len(study.trials)))

9 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/series.py in __array__(self, dtype)
    855               dtype='datetime64[ns]')
    856         """
--> 857         return np.asarray(self._values, dtype)
    858 
    859     # ----------------------------------------------------------------------

ValueError: could not convert string to float: 'Technology'
```

### Steps to reproduce

Just during usual execution of optuna.

**Comment by nzw0301** [comment]
I think the error is from scikit-learn, not from Optuna. As in the documentation of `RandomForestClassifier`, the inputs will be transformed to float values. I suppose 
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html might be helpful proprocessing.
