### ISSUE TITLE
Parallelization using Mysql with the error of “"Can't connect to local MySQL server through socket '/tmp/mysql.sock'”

### ISSUE THREAD

**Issue by 201520906050** [optuna/optuna#3522]
### Environment

- Optuna version: 2.10.0
- Python version: 3.7.12
- OS: Linux-5.4.0-109-generic-x86_64-with-debian-buster-sid
- (Optional) Other libraries and their versions: stabe-baseline3, highway-env

### Description

 Glad to see such an extraordinary awesome tools for tuning hyperparameter ! I followed the tutorial [https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html](url) and tried the easy parallelization, but either I run my code through PyCharm or terminal output the error：
`sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
`
I installed Mysql through`sudo apt update`and`sudo apt install mysql-server`and Mysql worked fine, so i'm confused whether it's the problem of Optuna or Mysql or even something else. I pasted my whole code here for you to reproduce

### Error messages, stack traces, or logs

```shell
/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/ale_py/roms/__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()

Bad key "text.kerning_factor" on line 4 in
/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dqn_highway_optuna.py", line 197, in <module>
    storage="mysql://root@localhost/optuna")
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/optuna/study/study.py", line 1136, in create_study
    storage = storages.get_storage(storage)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/optuna/storages/__init__.py", line 31, in get_storage
    return _CachedStorage(RDBStorage(storage))
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 183, in __init__
    models.BaseModel.metadata.create_all(self.engine)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4786, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3116, in _run_ddl_visitor
    with self.begin() as conn:
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3032, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3254, in _wrap_pool_connect
    e, dialect, self
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/pami/anaconda3/envs/RL/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Steps to reproduce

1. You can either run this code through IDE or terminal.
2. stable-baseline3 is a framework of reinforcement learning, you can either install it or not since this is not the point of error.
3. highway-env is a gym environment.
```python
""" Optuna example that optimizes the hyperparameters of
a reinforcement learning agent using DQN implementation from Stable-Baselines3
on highway-environment： highway-v0 scene .
This is a simplified version of what can be found in https://github.com/DLR-RM/rl-baselines3-zoo.


from typing import Any
from typing import Dict

import gym
import optuna
from optuna.pruners import HyperbandPruner, MedianPruner
from optuna.samplers import TPESampler
from stable_baselines3 import DQN
from stable_baselines3.common.callbacks import EvalCallback
import torch
import torch.nn as nn

from stable_baselines3.common.callbacks import CallbackList
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from tqdm import tqdm, trange
from optuna.visualization import plot_slice

import highway_env

N_TRIALS = 100
N_STARTUP_TRIALS = 5
N_EVALUATIONS = 2
N_TIMESTEPS = int(4e4)
EVAL_FREQ = int(N_TIMESTEPS / N_EVALUATIONS)
N_EVAL_EPISODES = 3

ENV_ID = "CartPole-v1"

DEFAULT_HYPERPARAMS = {
    "policy": "MlpPolicy",
    "env": ENV_ID,
}

log_dir = "../dqn_log/"


def sample_dqn_params(trial: optuna.Trial) -> Dict[str, Any]:
    """
    Sampler for DQN hyperparams.

    :param trial:
    :return:
    """
    # param define
    gamma = trial.suggest_categorical("gamma", [0.9, 0.95, 0.98, 0.99, 0.995, 0.999, 0.9999])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64, 100, 128, 256, 512])
    buffer_size = trial.suggest_categorical("buffer_size", [int(1e4), int(5e4), int(1e5), int(1e6)])
    exploration_final_eps = trial.suggest_uniform("exploration_final_eps", 0, 0.2)
    exploration_fraction = trial.suggest_uniform("exploration_fraction", 0, 0.5)
    target_update_interval = trial.suggest_categorical("target_update_interval", [1, 1000, 5000, 10000, 15000, 20000])
    learning_starts = trial.suggest_categorical("learning_starts", [0, 1000, 5000, 10000, 20000])

    train_freq = trial.suggest_categorical("train_freq", [1, 4, 8, 16, 128, 256, 1000])
    subsample_steps = trial.suggest_categorical("subsample_steps", [1, 2, 4, 8])
    gradient_steps = max(train_freq // subsample_steps, 1)

    net_arch = trial.suggest_categorical("net_arch", ["tiny", "small", "medium"])

    net_arch = {"tiny": [64], "small": [64, 64], "medium": [256, 256]}[net_arch]

    hyperparams = {
        "gamma": gamma,
        "learning_rate": learning_rate,
        "batch_size": batch_size,
        "buffer_size": buffer_size,
        "train_freq": train_freq,
        "gradient_steps": gradient_steps,
        "exploration_fraction": exploration_fraction,
        "exploration_final_eps": exploration_final_eps,
        "target_update_interval": target_update_interval,
        "learning_starts": learning_starts,
        "policy_kwargs": dict(net_arch=net_arch),
    }

    # if trial.using_her_replay_buffer:
    #     hyperparams = sample_her_params(trial, hyperparams)

    return hyperparams


class TrialEvalCallback(EvalCallback):
    """Callback used for evaluating and reporting a trial."""

    def __init__(
            self,
            eval_env: gym.Env,
            trial: optuna.Trial,
            n_eval_episodes: int = 10,
            eval_freq: int = 10000,
            deterministic: bool = True,
            verbose: int = 0,
    ):

        super().__init__(
            eval_env=eval_env,
            n_eval_episodes=n_eval_episodes,
            eval_freq=eval_freq,
            deterministic=deterministic,
            verbose=verbose,
        )
        self.trial = trial
        self.eval_idx = 0
        self.is_pruned = False

    def _on_step(self) -> bool:
        COUNT = 0
        if self.eval_freq > 0 and self.n_calls % self.eval_freq == 0:
            super()._on_step()
            self.eval_idx += 1
            self.trial.report(self.last_mean_reward, self.eval_idx)
            # Prune trial if need
            if self.trial.should_prune():
                self.is_pruned = True
                return False
        return True


def objective(trial: optuna.Trial) -> float:
    kwargs = DEFAULT_HYPERPARAMS.copy()
    # Sample hyperparameters
    kwargs.update(sample_dqn_params(trial))
    # Create the RL model
    # model = DQN(**kwargs)
    model = DQN(**kwargs, tensorboard_log='../tensorboard/dqn_highway_tensorboard/')

    # Create env used for evaluation
    eval_env = gym.make(ENV_ID)


    eval_env = Monitor(eval_env, log_dir)
    eval_env = DummyVecEnv([lambda: eval_env])

    # model.load("dqn_highway.zip", env=eval_env)

    # Create the callback that will periodically evaluate
    # and report the performance
    eval_callback = TrialEvalCallback(
        eval_env, trial, n_eval_episodes=N_EVAL_EPISODES, eval_freq=EVAL_FREQ, deterministic=True
    )
    auto_save_callback = SaveOnBestTraingRewardCallback(check_freq=1000, log_dir=log_dir)

    nan_encountered = False
    try:
        with ProgressBarManager(total_timesteps=N_TIMESTEPS) as progress_callback:
            # model.learn(N_TIMESTEPS, callback=[eval_callback, progress_callback])
            model.learn(N_TIMESTEPS, callback=eval_callback)
    except AssertionError as e:
        # Sometimes, random hyperparams can generate NaN
        print(e)
        nan_encountered = True
    finally:
        # Free memory
        model.env.close()
        eval_env.close()

    # Tell the optimizer that the trial failed
    if nan_encountered:
        return float("nan")

    if eval_callback.is_pruned:
        raise optuna.exceptions.TrialPruned()

    return eval_callback.last_mean_reward


if __name__ == "__main__":
    # Set pytorch num threads to 1 for faster training
    torch.set_num_threads(1)
    sampler = TPESampler(n_startup_trials=N_STARTUP_TRIALS)
    # Do not prune before 1/3 of the max budget is used

    # pruner = HyperbandPruner(min_resource=1, max_resource=N_TIMESTEPS, reduction_factor=3)
    pruner = MedianPruner(n_startup_trials=N_STARTUP_TRIALS, n_warmup_steps=N_EVALUATIONS // 3)
    # error starts here
    study = optuna.create_study(study_name='distributed-example', sampler=sampler, pruner=pruner, direction="maximize",
                                storage="mysql://root@localhost/optuna")
    study = optuna.load_study(
        study_name="distributed-example", storage="mysql://root@localhost/optuna"
    )
    try:
        study.optimize(objective, n_trials=N_TRIALS, timeout=600, )
        # plot the which hyperparameter matters the most
        fig = optuna.visualization.plot_param_importances(study)
        # plot the which hyperparamter that Oputna tried the most frequent
        # fig = optuna.visualization.plot_slice(study)

        fig.show()

    except KeyboardInterrupt:
        pass

    print("Number of finished trials: ", len(study.trials))

    print("Best trial:")
    trial = study.best_trial

    print("  Value: ", trial.value)

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

    print("  User attrs:")
    for key, value in trial.user_attrs.items():
        print("    {}: {}".format(key, value))
```

**Comment by 201520906050** [comment]
And i think the problem is the creation of the study, as i  typed in terminal：
`optuna create-study --study-name "distributed-example" --storage "mysql://root@localhost/optuna"`
and the traceback were like that：

> [E 2022-04-28 22:28:42,149] (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

**Comment by himkt** [comment]
> I installed Mysql throughsudo apt updateandsudo apt install mysql-serverand Mysql worked fine

@201520906050 Could you please share with us to connect MySQL with `mysql` command?

**Comment by 201520906050** [comment]
> > I installed Mysql throughsudo apt updateandsudo apt install mysql-serverand Mysql worked fine
> 
> @201520906050 Could you please share with us to connect MySQL with `mysql` command? Does it work?

Just `sudo mysql`is fine or `mysql -u root -p` and it works. And I also tried another example using pymysql to connect MySQL and it also worked.

**Comment by himkt** [comment]
Hmm, I'm sorry to hear that.

What if `--storage mysql+pymysql://root@127.0.0.1/optuna`?
(Although it may not solve the problem since the message says `Can't connect to local MySQL server through socket '/tmp/mysql.sock'`...)

**Comment by 201520906050** [comment]
> 

Oh my goshhhhhh that's amazing ! I just replaced the 'localhost' with '127.0.0.1' as you've suggested, and it completely worked ! Thank u ! Sincerely !

**Comment by MaxenceBouvier** [comment]
FYI, you can also specify the path to the socket for mysql in the URI like this:
`mysql+pymysql://root@localhost/optuna?unix_socket=/var/run/mysqld/mysqld.sock`
