### ISSUE TITLE
Optuna throws errors after installation (recent)

### ISSUE THREAD

**Issue by Codeguyross** [optuna/optuna#3529]
### Expected behavior

I have been using optuna for a while and suddenly it stopped working because it will no longer import. If i start a fresh conda environment with python version 3.7,3.8 or 3.9 it all throws the same module not found on optuna. Steps to reproduce are start a fresh environment with python 3.7, 3.8, or 3.9. Install tensorflow and pandas. The try to import optuna. I have tried installing with both conda and pip. 

### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
(optunav1) python -c "import optuna; print(optuna.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "optuna.py", line 13, in <module>
    from optuna.pruners import MedianPruner
ModuleNotFoundError: No module named 'optuna.pruners'; 'optuna' is not a package

(optunav1) python -c "import platform; print(platform.python_version())"
3.7.13

(optunav1) python -c "import platform; print(platform.platform())"
Windows-10-10.0.19041-SP0

And just to absolutely confirm the right version of python is being used: 
(optunav1) C:\Users\me\Documents\optunaTest>C:\Users\user\Anaconda3\envs\optunav1\python.exe
Python 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import optuna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\me\Documents\optunaTest\optuna.py", line 13, in <module>
    from optuna.pruners import MedianPruner
ModuleNotFoundError: No module named 'optuna.pruners'; 'optuna' is not a package


Here is my conda list of installs
# packages in environment at C:\Users\user\Anaconda3\envs\optunav1:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                     eigen  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py37h2bbff1b_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alembic                   1.7.7              pyhd8ed1ab_0    conda-forge
astor                     0.8.1            py37haa95532_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
asynctest                 0.13.0                     py_0  
attrs                     21.4.0             pyhd3eb1b0_0  
autopage                  0.5.0              pyhd8ed1ab_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
blinker                   1.4              py37haa95532_0  
bottleneck                1.3.4            py37h080aedc_0  
brotlipy                  0.7.0           py37h2bbff1b_1003  
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.10.8        py37h03978a9_2    conda-forge
cffi                      1.15.0           py37h2bbff1b_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4            py37haa95532_0  
cliff                     3.10.1             pyhd8ed1ab_0    conda-forge
cmaes                     0.8.2              pyh44b312d_0    conda-forge
cmd2                      2.3.3            py37h03978a9_1    conda-forge
colorama                  0.4.4              pyhd3eb1b0_0  
colorlog                  6.6.0            py37h03978a9_1    conda-forge
cryptography              3.4.8            py37h71e12ea_0  
dataclasses               0.8                pyh6d0b6a4_7  
frozenlist                1.2.0            py37h2bbff1b_0  
gast                      0.3.3                      py_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
greenlet                  1.1.2            py37hf2a7229_2    conda-forge
grpcio                    1.42.0           py37hc60d5dd_0  
h5py                      2.10.0           py37h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.11.3           py37haa95532_0  
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          haa95532_3556  
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
libprotobuf               3.19.1               h23ce68f_0  
mako                      1.2.0              pyhd8ed1ab_1    conda-forge
markdown                  3.3.4            py37haa95532_0  
markupsafe                2.1.1            py37hcc03f2d_1    conda-forge
mkl                       2021.4.0           haa95532_640  
mkl-service               2.4.0            py37h2bbff1b_0  
mkl_fft                   1.3.1            py37h277e83a_0  
mkl_random                1.2.2            py37hf11a4ad_0  
multidict                 5.1.0            py37h2bbff1b_2  
numexpr                   2.8.1            py37hb80d3ca_0  
numpy                     1.21.5           py37h7a0a035_1  
numpy-base                1.21.5           py37hca35cd5_1  
oauthlib                  3.2.0              pyhd3eb1b0_0  
openssl                   1.1.1n               h8ffe710_0    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1  
optuna                    2.10.0             pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.3.4            py37h6214cd6_0  
pbr                       5.8.1              pyhd8ed1ab_0    conda-forge
pip                       21.2.4           py37haa95532_0  
prettytable               3.2.0              pyhd8ed1ab_0    conda-forge
protobuf                  3.19.1           py37hd77b12b_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.1.0            py37haa95532_0  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyreadline                2.1                      py37_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.13               h6244533_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
requests                  2.27.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
scipy                     1.7.3            py37h0a974cb_0  
setuptools                61.2.0           py37haa95532_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlalchemy                1.4.36           py37hcc03f2d_0    conda-forge
sqlite                    3.38.2               h2bbff1b_0  
stevedore                 3.5.0            py37h03978a9_3    conda-forge
tensorboard               2.4.0              pyhc547734_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.3.0           mkl_py37h04bc1aa_0  
tensorflow-base           2.3.0           eigen_py37h17acbac_0  
tensorflow-estimator      2.6.0              pyh7b7c402_0  
termcolor                 1.1.0            py37haa95532_1  
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.9           py37haa95532_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
win_inet_pton             1.1.0            py37haa95532_0  
wincertstore              0.2              py37haa95532_2  
wrapt                     1.13.3           py37h2bbff1b_2
```

### Steps to reproduce

Trying to only import optuna will throw the error

1. conda create -n optunav1 python=3.7
2. conda install pandas -y
3. conda install tensorflow -y
```python
# python code
```
import optuna

### Additional context (optional)

ALso, the three environment commands below will not work on windows without double quotes of the will throw and error on the space after import

python -c "import optuna; print(optuna.__version__)"
python -c "import platform; print(platform.python_version())"
python -c "import platform; print(platform.platform())"

**Comment by nzw0301** [comment]
Short answer: Rename the file name, `optuna.py` with another name except for package names.

More contexts:

Thank you for sharing the detailed information. According to the shared information, the file name looks `optuna.py`. In this case, python tries to import `MedianPruner` from `optuna.py` rather than installed `optuna`.

**Comment by Codeguyross** [comment]
Lol i didnt notice that i had done that.... Thanks
