### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NotImplementedType'

### ISSUE THREAD

**Issue by yingjianling** [optuna/optuna#3652]
### Expected behavior

No bugs reported

### Environment

- Optuna version:2.10.0
- Python version:3.8.5
- OS:Linux-4.15.0-142-generic-x86_64-with-glibc2.10
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
[W 2022-06-10 03:05:11,975] Trial 10 failed because of the following error: TypeError("int() argument must be a string, a bytes-like object or a number, not 'NotImplementedType'")
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "auto_tune.py", line 53, in objective
    model = suggest(trail, cfg_p, template)
  File "auto_tune.py", line 16, in suggest
    d[p["input"]["name"]] = suggest_method(**p["input"])
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/trial/_trial.py", line 452, in suggest_int
    return int(self._suggest(name, distribution))
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/trial/_trial.py", line 719, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py", line 436, in sample_independent
    mpe_below = _ParzenEstimator(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 67, in __init__
    low, high, q = self._calculate_parzen_bounds(dist)
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 247, in _calculate_parzen_bounds
    low = distribution.low - 0.5 * q
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 545, in __sub__
    return self._new(result)
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 562, in _new
    return Integer(result, self._trivia, raw)
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 506, in __new__
    return super().__new__(cls, value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NotImplementedType'
Traceback (most recent call last):
  File "auto_tune.py", line 75, in <module>
    main(args)
  File "auto_tune.py", line 66, in main
    study.optimize(objective, n_trials=args.n_trials)
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "auto_tune.py", line 53, in objective
    model = suggest(trail, cfg_p, template)
  File "auto_tune.py", line 16, in suggest
    d[p["input"]["name"]] = suggest_method(**p["input"])
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/trial/_trial.py", line 452, in suggest_int
    return int(self._suggest(name, distribution))
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/trial/_trial.py", line 719, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py", line 436, in sample_independent
    mpe_below = _ParzenEstimator(
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 67, in __init__
    low, high, q = self._calculate_parzen_bounds(dist)
  File "/root/anaconda3/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 247, in _calculate_parzen_bounds
    low = distribution.low - 0.5 * q
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 545, in __sub__
    return self._new(result)
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 562, in _new
    return Integer(result, self._trivia, raw)
  File "/root/anaconda3/lib/python3.8/site-packages/tomlkit/items.py", line 506, in __new__
    return super().__new__(cls, value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NotImplementedType'
```

### Steps to reproduce

1.optuna param config by toml
config_for_param.toml
```python
param = [
    {type = "int", input = {name = "p1", low = 5, high = 80}},
    {type = "int", input = {name = "p2", low = 1, high = 7}},
    {type = "float", input = {name = "p3", low = 0.4, high = 0.7}}
]
```
2.
```python
import numpy as np
from tomlkit import document,table,nl,parse,dumps
import optuna
import os, argparse
from string import Template
import subprocess
from metrics import bcubed_disturb, specialize_single_cluster
exp_dir = None
bin_path = None

def suggest(trail, cfg, template):
    suggest_tbl = {"float":trail.suggest_float,"int":trail.suggest_int,"categorical":trail.suggest_categorical}
    d = {}
    for p in cfg['param']:
        suggest_method = suggest_tbl[p["type"]]
        print(p)
        d[p["input"]["name"]] = suggest_method(**p["input"])
    return template.substitute(d)

def run():
    global exp_dir, bin_path
    cfg_path = os.path.join(exp_dir, "config_for_cluster.toml")
    cfg = parse(open(cfg_path).read())
    labels_path = cfg["labels_path"]
    masks_path = cfg["masks_path"]
    cfg["model_path"] = os.path.join(exp_dir, "model.toml")
    f = open(cfg_path,"w")
    f.write(dumps(cfg))
    f.close()

    log_path = os.path.join(exp_dir, "log.txt")
    cmd = "cd {} && {} {} > {}".format(exp_dir, bin_path, cfg_path, log_path)
    print("[AUTO_TUNE] start clustering")
    p = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE)
    print("[AUTO_TUNE] clustering done")

    preds = np.array([int(l.strip()) for l in open(os.path.join(exp_dir, "body_res.txt"),"r").readlines()])
    preds = specialize_single_cluster(preds)
    preds = specialize_single_cluster(preds, -2)
    labels = np.array([int(l.strip()) for l in open(labels_path,"r").readlines()])
    masks = np.array([int(l.strip()) for l in open(masks_path,"r").readlines()])
    precision, recall, fscore = bcubed_disturb(preds, masks, labels)
    print("[AUTO_TUNE] precision = {:.3f} recall = {:.3f} fscore = {:.3f}".format(precision, recall, fscore))
    return fscore

def objective(trail):
    global exp_dir
    f = open(os.path.join(exp_dir,"config_for_param.toml"), "r")
    cfg_p = parse(f.read())
    f.close()
    f = open(os.path.join(exp_dir,"template.toml"), "r")
    template = Template(f.read())
    f.close()
    model = suggest(trail, cfg_p, template)
    f = open(os.path.join(exp_dir,"model.toml"),"w")
    f.write(dumps(parse(model)))
    f.close()

    fscore = run()
    return fscore

def main(args):
    global exp_dir, bin_path
    exp_dir = args.exp_dir
    bin_path = args.bin_path
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=args.n_trials)
    print("best_params={} best_value={}".format(study.best_params, study.best_value))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('--exp_dir', type=str)
    parser.add_argument('--bin_path', type=str)
    parser.add_argument('--n_trials', type=int, default=100)
    args = parser.parse_args()
    main(args)
```
3.
```
python auto_tune.py --exp_dir=exp --bin_path=./run --n_trials=100
```

### Additional context (optional)
1. program return error on the 11th(Trail 10) trail.
2. Error is reported when TPESampler is used, CmaEsSampler works well.

**Comment by nzw0301** [comment]
I suppose the error does not come from Optuna. Unfortunately, the code is not reproducible since it requires some external packages and files, so we find it difficult to investigate it, I'm afraid.

**Comment by yingjianling** [comment]
The error is related to the toml passing paramters incorrectly. Thanks for replying.
