### ISSUE TITLE
The `optuna.samplers._tpe.sampler._calculate_weights_below_for_multi_objective` should return `[]` when `indices=[]`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3675]
### Expected behavior

The `optuna.samplers._tpe.sampler._calculate_weights_below_for_multi_objective` should return `[]` when `indices=[]`, but it raises an `IndexError`. 

### Environment

- Optuna version: current master https://github.com/optuna/optuna/commit/d3c53e053a18341405cdfc9587d4525fdce7494d
- Python version: 3.9
- OS: mac, linux
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
(venv) mamu@HideakinoMacBook-puro 3662 % python hoge.py
Traceback (most recent call last):
  File "/Users/mamu/Dev/pfn/code_snippets_for_optuna/3662/hoge.py", line 5, in <module>
    optuna.samplers._tpe.sampler._calculate_weights_below_for_multi_objective(
  File "/Users/mamu/Dev/pfn/optuna/optuna/samplers/_tpe/sampler.py", line 764, in _calculate_weights_below_for_multi_objective
    cvals = list(config_values.values())[0][indices]
IndexError: arrays used as indices must be of integer (or boolean) type
```

### Steps to reproduce

```python
import optuna
import numpy as np


optuna.samplers._tpe.sampler._calculate_weights_below_for_multi_objective(
    {"x": np.array([1.0, 2.0, 3.0], dtype=float)},
    [(0, [0.2, 0.5]), (0, [0.9, 0.4]), (0, [1, 1])],
    np.array([]),
)
```

**Comment by contramundum53** [comment]
Specifying `np.array([], dtype=np.int64)` as indices will correctly return `[]`.
