### ISSUE TITLE
live lock hang in suggest_float

### ISSUE THREAD

**Issue by pseudotensor** [optuna/optuna#3727]
### Expected behavior

No hang

### Environment

- Optuna version:3.0.0
- Python version:3.8.12
- OS:Linux-5.4.0-74-generic-x86_64-with-glibc2.10

### Error messages, stack traces, or logs

```shell
Current thread 0x00007f940a821740 (most recent call first):
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8315 in _rvs_scalar
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8299 in _rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 1092 in rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 133 in sample
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py", line 437 in sample_independent
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 595 in _suggest
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 156 in suggest_float
```

gdb:

```
#0  0x00007f93fd3a9578 in cephes_ndtri () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-x86_64-linux-gnu.so
#1  0x00007f93fd347bbb in __pyx_f_5scipy_7special_7_ufuncs_loop_d_d__As_d_d () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-x86_64-linux-gnu.so
#2  0x00007f940706f1b6 in trivial_two_operand_loop () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#3  0x00007f9407075078 in execute_legacy_ufunc_loop () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#4  0x00007f94070771aa in PyUFunc_GenericFunction_int () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#5  0x00007f9407078743 in ufunc_generic_call () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#6  0x0000559b8c81d0fe in _PyObject_MakeTpCall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/errors.c:219
#7  0x0000559b8c8b379b in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f93f38f7ec0, callable=0x7f93fd2d8310) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:125
#8  _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f93f38f7ec0, callable=0x7f93fd2d8310) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#9  call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559b8d80b9f0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#10 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3469
#11 0x0000559b8c8921b6 in PyEval_EvalFrameEx (throwflag=0, f=0x7f93f38f7d40) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#12 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#13 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#14 0x0000559b8c8aed57 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x559b980efbf0, callable=0x7f93fc3afc10) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#15 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559b8d80b9f0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#16 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3500
#17 0x0000559b8c890fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x559b980ef990) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#18 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#19 0x0000559b8c892388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#20 0x0000559b8c8aed57 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x559b94d4d480, callable=0x7f93fc219940) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#21 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559b8d80b9f0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#22 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3500
#23 0x0000559b8c8921b6 in PyEval_EvalFrameEx (throwflag=0, f=0x559b94d4d2c0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#24 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#25 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#26 0x0000559b8c8aee73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f93f9874800, callable=0x7f93fc21d040) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#27 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559b8d80b9f0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#28 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#29 0x0000559b8c890fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x7f93f9874640) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#30 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#31 0x0000559b8c892388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#32 0x0000559b8c8aee73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x559b94161bc8, callable=0x7f93fc21d280) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#33 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559b8d80b9f0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#34 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#35 0x0000559b8c890fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x559b94161a00) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#36 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#37 0x0000559b8c892388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#38 0x0000559b8c892a41 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:127
#39 method_vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:89
#40 0x0000559b8c806e7e in PyVectorcall_Call (kwargs=<optimized out>, tuple=<optimized out>, callable=0x7f93490c6580) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:200
#41 PyObject_Call () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:228
#42 0x0000559b8c8b052d in do_call_core (kwdict=0x7f92fc628540, callargs=0x7f93063cbf40, func=0x7f93490c6580, tstate=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:5010
#43 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3559
#44 0x0000559b8c890fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x559b972584e0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#45 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#46 0x0000559b8c892ab7 in _PyFunction_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, stack=0x559b94828e80, func=0x7f93fc94c8b0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:90
#47 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=0x559b94828e80, callable=0x7f93fc94c8b0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:127
#48 method_vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:60
#49 0x0000559b8c8afba5 in _PyObject_Vectorcall (kwnames=0x7f93f1551bd0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f93418bfb40) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#50 call_function (kwnames=0x7f93f1551bd0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#51 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3515
#52 0x0000559b8c8921b6 in PyEval_EvalFrameEx (throwflag=0, f=0x559b94828c70) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#53 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284

```
```


### Steps to reproduce

Unknown currently.    Happens frequently enough that if it was fixed it would be obvious, but not frequent enough to repro easily.  Doesn't seem to exactly repro in any case.

### Additional context (optional)

_No response_

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by pseudotensor** [comment]
@nzw0301 See above note.

**Comment by nzw0301** [comment]
How about the code that causes the error above? Otherwise, we cannot investigate this issue due to the lack of information.

**Comment by pseudotensor** [comment]
If it repro'd I've reduce the code down, but it doesn't so I don't.

I know you can't investigate, but others might have the same issue and have some insights.  It's probably a bug in scipy.

**Comment by nzw0301** [comment]
Thanks, it makes sense. Since the bug sounds stochastic and comes from TPESampler w/ scipy, it might be reproducible by fixing the random seed.

**Comment by pseudotensor** [comment]
Also hung in cat part, same underlying function:
```
Current thread 0x00007f267cd56740 (most recent call first):
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8315 in _rvs_scalar
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8299 in _rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 1092 in rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 133 in sample
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py", line 437 in sample_independent
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 595 in _suggest
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 156 in suggest_float
  File "/home/jon/h2oai.superclean/h2oaicore/models_main.py", line 6082 in get_one
  File "/home/jon/h2oai.superclean/h2oaicore/models_xgboost.py", line 478 in mutate_params
  File "/home/jon/h2oai.superclean/h2oaicore/models_main.py", line 2995 in full_mutate_params
  File "/home/jon/h2oai.superclean/h2oaicore/models_main.py", line 2981 in full_mutate_params_base
```

**Comment by pseudotensor** [comment]
```
#0  0x00007f3d952f8ec2 in PyArray_CanCastTo () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#1  0x00007f3d952f920d in PyArray_CanCastTypeTo () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#2  0x00007f3d952f966a in can_cast_scalar_to () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#3  0x00007f3d954cc7b9 in PyUFunc_ValidateCasting () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#4  0x00007f3d954cddb2 in PyUFunc_SimpleBinaryComparisonTypeResolver () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#5  0x00007f3d954abbe7 in PyUFunc_GenericFunction_int () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#6  0x00007f3d954ae743 in ufunc_generic_call () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#7  0x0000564123bef0fe in _PyObject_MakeTpCall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/errors.c:219
#8  0x0000564123bf24ed in _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0x7ffcaed9d280, callable=0x7f3d95dd2a90) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:125
#9  _PyObject_Vectorcall (kwnames=0x0, nargsf=2, args=0x7ffcaed9d280, callable=0x7f3d95dd2a90) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#10 _PyObject_FastCall (nargs=2, args=0x7ffcaed9d280, func=0x7f3d95dd2a90) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:147
#11 object_vacall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:1187
#12 0x0000564123bf2681 in PyObject_CallFunctionObjArgs (callable=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:1260
#13 0x00007f3d952c3907 in array_richcompare () from /home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
#14 0x0000564123bdc736 in do_richcompare (op=1, w=0x564123e76ce0 <small_ints+160>, v=0x7f3cb5deecb0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/object.c:726
#15 PyObject_RichCompare () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/object.c:774
#16 0x0000564123c84fc3 in cmp_outcome (w=0x564123e76ce0 <small_ints+160>, v=0x7f3cb5deecb0, op=1, tstate=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:5110
#17 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:2977
#18 0x0000564123c62fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x56412d3fab40) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#19 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#20 0x0000564123c64388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#21 0x0000564123c80d57 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5641319d8490, callable=0x7f3d8a96a700) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#22 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#23 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3500
#24 0x0000564123c641b6 in PyEval_EvalFrameEx (throwflag=0, f=0x5641319d82d0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#25 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#26 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#27 0x0000564123c80e73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f3cc1dd6a00, callable=0x7f3d8a96adc0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#28 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#29 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#30 0x0000564123c62fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x7f3cc1dd6840) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#31 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#32 0x0000564123c64388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#33 0x0000564123c80e73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x5641345889a8, callable=0x7f3d8a97e040) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#34 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#35 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#36 0x0000564123c62fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x5641345887e0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#37 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#38 0x0000564123c64388 in _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:436
#39 0x0000564123c64a41 in _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:127
#40 method_vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:89
#41 0x0000564123bd8e7e in PyVectorcall_Call (kwargs=<optimized out>, tuple=<optimized out>, callable=0x7f3cbfaca680) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:200
#42 PyObject_Call () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:228
#43 0x0000564123c8252d in do_call_core (kwdict=0x7f3c737b3c00, callargs=0x7f3c74330a40, func=0x7f3cbfaca680, tstate=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:5010
#44 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3559
#45 0x0000564123c62fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x7f3d54003ed0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#46 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#47 0x0000564123c64ab7 in _PyFunction_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, stack=0x56412f9a47d0, func=0x7f3d8b02f5e0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:90
#48 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=0x56412f9a47d0, callable=0x7f3d8b02f5e0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:127
#49 method_vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:60
#50 0x0000564123c81ba5 in _PyObject_Vectorcall (kwnames=0x7f3d7bdb4bd0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f3cbfa1e0c0)
    at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#51 call_function (kwnames=0x7f3d7bdb4bd0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#52 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3515
#53 0x0000564123c641b6 in PyEval_EvalFrameEx (throwflag=0, f=0x56412f9a45c0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#54 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#55 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#56 0x0000564123c80e73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x564132766e60, callable=0x7f3d7bdbf280) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#57 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#58 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#59 0x0000564123c641b6 in PyEval_EvalFrameEx (throwflag=0, f=0x564132766c50) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#60 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#61 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#62 0x0000564123c80e73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f3cc1dd61f8, callable=0x7f3d7bdbfd30) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#63 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#64 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#65 0x0000564123c641b6 in PyEval_EvalFrameEx (throwflag=0, f=0x7f3cc1dd6040) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:738
#66 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:284
#67 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/call.c:411
#68 0x0000564123c80e73 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f3cc257b5c8, callable=0x7f3d80b230d0) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:115
#69 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x564124b51260) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4963
#70 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:3486
#71 0x0000564123c62fa3 in PyEval_EvalFrameEx (throwflag=0, f=0x7f3cc257b420) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#72 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Python/ceval.c:4298
#73 0x0000564123c64ab7 in _PyFunction_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, stack=0x5641283f34d0, func=0x7f3d80b43790) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Objects/classobject.c:90
#74 _PyObject_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, args=0x5641283f34d0, callable=0x7f3d80b43790) at /home/conda/feedstock_root/build_artifacts/python-split_1632942402315/work/Include/cpython/abstract.h:127
---Type <return> to continue, or q <return> to quit---
```


```
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8007 in _truncnorm_ppf_scalar
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8190 in _ppf
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8316 in _rvs_scalar
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 8299 in _rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 1092 in rvs
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py", line 133 in sample
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py", line 437 in sample_independent
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 595 in _suggest
  File "/home/jon/minicondadai_py38_superclean/lib/python3.8/site-packages/optuna/trial/_trial.py", line 156 in suggest_float
```


same thing

**Comment by pseudotensor** [comment]
I'm guessing it's because I use fork multiprocessing in python and sometimes messes up scipy.  I don't think scikpy uses openmp, but maybe it uses blas.  Although I'm using pthread version of blas.
