### ISSUE TITLE
PostgreSQL issue "table studies already exists"

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#3865]
### Expected behavior

I want to create a db, then use it for storage.  Once the db exists, I expect create study to work. However, it gives the error "table studies already exists"

### Environment

- Optuna version: 2.10.0
- Python version: 3.8
- OS: Ubuntu 20.04
- (Optional) Other libraries and their versions:
- sqlalchemy 1.4.27
- sqlalchemy-utils 0.38.3

### Error messages, stack traces, or logs

```shell
OperationalError: (sqlite3.OperationalError) table studies already exists
[SQL: 
CREATE TABLE studies (
	study_id INTEGER NOT NULL, 
	study_name VARCHAR(512) NOT NULL, 
	PRIMARY KEY (study_id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Steps to reproduce

1. create a database

```python
postgresql_url = \
  'postgresql+psycopg2://postgres:postgres@localhost:5432/' + study_name
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
engine = create_engine(postgresql_url)
if not database_exists(engine.url):
    create_database(engine.url) 
```

2. set up optuna storage

```python
storage = \
  optuna.storages.RDBStorage(url = postgresql_url,
                             engine_kwargs = {'pool_size' : 20, 
                                              'max_overflow' : 0})
```
3. create the study

```python
study = optuna.create_study(study_name = study_name,
                            sampler = sampler,
                            storage = storage,
                            direction = 'maximize',
                            load_if_exists = True)
optuna.logging.set_verbosity(optuna.logging.INFO)
optuna.logging.enable_default_handler()
```

### Additional context (optional)

I have tried this process without first creating a database, and it fails with database does not exist

**Comment by nzw0301** [comment]
I'm not sure why we need to create a database manually; personally, I don't recommend it since the DB scheme is not consistent with tables created by Optuna.

> I have tried this process without first creating a database, and it fails with database does not exist

Could you share the minimal reproducible code with us?

**Comment by eafpres** [comment]
Here is a minimum example of "database does not exist' error:
```
eafpres@LAPTOP-JSLJ8BRD:~$ sudo service postgresql start
[sudo] password for eafpres:
 * Starting PostgreSQL 12 database server                                                                                                               [ OK ]
eafpres@LAPTOP-JSLJ8BRD:~$ python
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import optuna
>>> study_name = '2022-08-10_10_04_37_xgboost'
>>> postgresql_url = \
...   'postgresql+psycopg2://postgres:postgres@localhost:5432/' + study_name
>>> optuna.storages.RDBStorage(url = postgresql_url,
        ...                            engine_kwargs = {'pool_size' : 20,
...                                             'max_overflow' : 0})
Traceback (most recent call last):
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/eafpres/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "2022-08-10_10_04_37_xgboost" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eafpres/.local/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py", line 183, in __init__
    models.BaseModel.metadata.create_all(self.engine)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3109, in _run_ddl_visitor
    with self.begin() as conn:
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3025, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3246, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2100, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/eafpres/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/eafpres/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  database "2022-08-10_10_04_37_xgboost" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)
>>>
```

**Comment by nzw0301** [comment]
Thanks. I'm not familiar with postgresql, so my suggestion in https://github.com/optuna/optuna/issues/3865#issuecomment-1210096201 might be wrong. 

I think you need to create a database named `2022-08-10_10_04_37_xgboost` manually. I conformed the following code works fine;

```shell
psql -d postgre;
create database example;
```

```python
import optuna
postgresql_url = 'postgresql+psycopg2://postgres:postgres@localhost:5432/example'
optuna.storages.RDBStorage(url = postgresql_url,
    engine_kwargs = {'pool_size' : 20,
    'max_overflow' : 0})
```

I think this is not the bug.

**Comment by eafpres** [comment]
Here is my code which automatically creates the dB before creating the study, and this works reliably:
```
postgresql_url = \
  'postgresql+psycopg2://postgres:postgres@localhost:5432/' + study_name
from sqlalchemy import create_engine, MetaData
from sqlalchemy_utils import database_exists, create_database
engine = create_engine(postgresql_url)
if not database_exists(engine.url):
    create_database(engine.url)
metadata = MetaData(bind = engine)
storage = \
  optuna.storages.RDBStorage(url = postgresql_url,
                             engine_kwargs = {'pool_size' : 20, 
                                              'max_overflow' : 0})
MetaData.reflect(metadata)  
optuna.logging.set_verbosity(optuna.logging.INFO)
optuna.logging.enable_default_handler()
study = optuna.create_study(study_name = study_name,
                            sampler = sampler,
                            storage = storage,
                            direction = 'maximize',
                            load_if_exists = True)
```
  
I think this is a useful example as it avoids having to use the command line to create the dB separately, and in my case, it's nice to be able to name the dB by the study for future use and maintenance later.

**Comment by codeananda** [comment]
@eafpres the only difference between this (above) comment and the one at the top is that you include `MetaData` in the former.  Is that really all that was missing? Or am I overlooking something? If so, why does adding `MetaData` solve the issue?

**Comment by eafpres** [comment]
> @eafpres the only difference between this (above) comment and the one at the top is that you include `MetaData` in the former. Is that really all that was missing? Or am I overlooking something? If so, why does adding `MetaData` solve the issue?

Yes, I think it has something to do with how Postgresql works but I don't recall how I figured that out.
