### ISSUE TITLE
record_evaluation callback with LightGBMTunerCV fails on trial 0

### ISSUE THREAD

**Issue by rabyj** [optuna/optuna#3961]
### Expected behavior

Expected behavior: At least one trial finishes during LightGBMTunerCV.

Observed behavior: Trial 0 fails on record_evaluation callback.

### Environment

- Optuna version: 3.0.0
- Python version: 3.8.10
- OS: Linux-5.15.0-46-generic-x86_64-with-glibc2.29 (Ubuntu 20.04.5 LTS)
- lightgbm : 3.3.2

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/local/USHERBROOKE/rabj2301/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/local/USHERBROOKE/rabj2301/Projects/sources/epi_ml/epi_ml/python/test/lgbm_test.py", line 36, in <module>
    tuner.run()
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 545, in run
    self.tune_feature_fraction()
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 570, in tune_feature_fraction
    self._tune_params([param_name], len(param_values), sampler, "feature_fraction")
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 653, in _tune_params
    study.optimize(
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py", line 234, in _run_trial
    raise func_err
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 319, in __call__
    cv_results = lgb.cv(self.lgbm_params, train_set, **self.lgbm_kwargs)
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/engine.py", line 647, in cv
    cb(callback.CallbackEnv(model=cvfolds,
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/callback.py", line 137, in _callback
    _init(env)
  File "/home/local/USHERBROOKE/rabj2301/Projects/epilap/venv-epilap-pytorch/lib/python3.8/site-packages/lightgbm/callback.py", line 131, in _init
    for data_name, eval_name, _, _ in env.evaluation_result_list:
ValueError: too many values to unpack (expected 4)
```
An example of `env.evaluation_result_list` is `[('cv_agg', 'multi_logloss', 1.4147074045922856, False, 0.006446780822586096)]`

### Steps to reproduce

I pickled the data to create something reproducible that stays close to my code. The input data needs to be in the same folder.

```python
import gzip
import pathlib
import pickle

import optuna.integration.lightgbm as lgb
[input-n40.pickle.gz](https://github.com/optuna/optuna/files/9481202/input-n40.pickle.gz)

params = {
    "objective": "multiclass",
    "num_class": 4,
    "metric": "multi_logloss",
    "boosting_type": "dart",
    "seed": 42,
    "verbosity": 4,
}

with gzip.open(
    pathlib.Path(__file__).parent.resolve() / "input-n40.pickle.gz", "rb"
) as f:
    input_data = pickle.load(f)

dtrain = input_data["dtrain"]
folds = input_data["folds"]

eval_results = {}

tuner = lgb.LightGBMTunerCV(
    params,
    dtrain,
    folds=folds,
    callbacks=[lgb.record_evaluation(eval_results)],
    show_progress_bar=False,
)

tuner.run()
```

### Additional context (optional)

A more full picture context for my code, which is not that far from [lightgbm_tuner_cv.py example](https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_tuner_cv.py):
```python
    params = {
        "objective": "multiclass",
        "num_class": len(ea_handler.classes),
        "metric": "multi_logloss",
        "boosting_type": "dart",
        "seed": 42,
        "verbosity": 4,
    }

    total_data = ea_handler.create_total_data()
    folds = list(ea_handler.split(total_data))
    dtrain = lgb.Dataset(  # type: ignore
        total_data.signals, label=total_data.encoded_labels, free_raw_data=True
    )

    eval_results = {}

    tuner = lgb.LightGBMTunerCV(  # type: ignore
        params,
        dtrain,
        folds=folds,  # type: ignore
        callbacks=[
            lgb.record_evaluation(eval_results),  # type: ignore
            lgb.log_evaluation,  # type: ignore
        ],
        show_progress_bar=False,
    )

    tuner.run()
```

- Data is multiclass
- `folds` is a list of the modified output of StratifiedKFold (repeated values for oversampling, but still same domain and format), so train and test idx. k=2 in kfold.
- `free_raw_data=False` changes nothing

([github](https://github.com/rabyj/epi_ml/commit/8960351c37e5fde20735f840413f899201d9b24f#diff-e370a91fe6e07469d65071226d2066a1c8b3883f87f7c534876d9fecd8429b01R137))

An example of `env.evaluation_result_list` is `[('cv_agg', 'multi_logloss', 1.4147074045922856, False, 0.006446780822586096)]`

**Comment by nzw0301** [comment]
This is not the bug of Optuna. I think the original issue: https://github.com/microsoft/LightGBM/pull/4947, has been resolved. Note that Optuna is tested with the latest stable lightgbm, so I'm not sure Optuna's lightgbm module works with the lastest lightgbm on github works fine.
