### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by jmrichardson** [optuna/optuna#4070]
### Expected behavior

Getting a math domain error on what appears to be valid parameter suggestions (ie no 0 or negative log)

### Environment

- Python version:3.8.13
- Optuna version:3.0.2
- OS:Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17

### Error messages, stack traces, or logs

```shell
Error Message:

Traceback (most recent call last):
  File "eras.py", line 47, in <module>
    pipeline = pipeline.fit(X_train, y_train, x_test=X_test, y_test=y_test)
  File "/home/jmrichardson/fml/fml/pipelines/standard.py", line 236, in fit
    model.optimize(features, test=test_features)
  File "/home/jmrichardson/fml/fml/models/lgbm.py", line 92, in optimize
    study.optimize(partial(objective, train, test), n_trials=self.n_trials, timeout=self.timeout, show_progress_bar=True)
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/study/_optimize.py", line 187, in _run_trial
    trial = study.ask()
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/study/study.py", line 514, in ask
    trial = trial_module.Trial(self, trial_id)
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/trial/_trial.py", line 54, in __init__
    self._init_relative_params()
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/trial/_trial.py", line 63, in _init_relative_params
    self.relative_params = self.study.sampler.sample_relative(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_sampler.py", line 211, in sample_relative
    child_params = perform_crossover(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 104, in perform_crossover
    child_params = _try_crossover(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 60, in _try_crossover
    [
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 61, in <listcomp>
    numerical_transform.transform(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/_transform.py", line 117, in transform
    trans_params[bound_idx] = _transform_numerical_param(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/_transform.py", line 239, in _transform_numerical_param
    trans_param = math.log(param) if transform_log else float(param)
ValueError: math domain error
```

### Steps to reproduce

Parameter suggest in objective function:

```
params = {'n_estimators': trial.suggest_int("n_estimators", 2000, 6000),
              'num_leaves': trial.suggest_int("num_leaves", 12, 256),
              'min_child_weight': trial.suggest_float('min_child_weight', 1e-5, 1024.0, log=True),
              'learning_rate': trial.suggest_float("learning_rate", .0001, 0.02, step=.001),
              'colsample_bytree': trial.suggest_float("colsample_bytree", 0.01, 1.0),
              'subsample': trial.suggest_float("subsample", 0.01, 1.0),
              'reg_alpha': trial.suggest_float("reg_alpha", 1e-5, 1024, log=True),
              'reg_lambda': trial.suggest_float("reg_lambda", 1e-5, 1024, log=True),
              'max_depth': trial.suggest_int("max_depth", 3, 32),
              "seed": 123,
              "objective": "regression",
              "verbose": -1,
              "force_row_wise": True,
              "metric": "None"}
```

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by jmrichardson** [comment]
Hi @nzw0301 

Unfortunately I don't have reproduceable code but I believe I was able to narrow it down to enqueueing a trial with parameters out of range from trial suggestion.  For example, if I enqueue reg_alpha as 0.0 while my trial suggestion is in range (1e-5, 1024).  The enqueue does work but future suggestions does appear to include reg_alpha as 0.0 which I believe causes the error because math.log(0.0) produces the math domain error.

**Comment by nzw0301** [comment]
I'm afraid I cannot reproduce it:

```python
import optuna

def objective1(trial):
    trial.suggest_float("y", 1e-4, 10, log=True)
    return trial.suggest_float("x", 1e-4, 10, log=True)


study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(seed=2))
study.enqueue_trial({"x": 0., "y": 0.})
study.optimize(objective1, n_trials=20)
```

**Comment by jmrichardson** [comment]
Hi @nzw0301 

I think it may be related to the dataset in terms of when this may occur.  My dataset has a low signal to noise ratio and 1M rows, 1200 features.  The first and enqueue is the best parameter set I've found and I am thinking it's likely that Optuna may be trying to use the parameters of the enqueue because it has the best performance.  Also, the error happens around the 100 to 200 trials typically which takes a considerable amount of time.  Since I updated the enqueue to be 1e-5 instead of 0 the issue hasn't happened again.  I also put a try,except block around math.log and verified the parameter is 0 when the error occurred.

**Comment by toshihikoyanase** [comment]
I may miss the point, but I found that the error occurred in the crossover of NSGAIISampler.
Could you tell us which crossover class you used, please?

```console
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_sampler.py", line 211, in sample_relative
    child_params = perform_crossover(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 104, in perform_crossover
    child_params = _try_crossover(
  File "/home/jmrichardson/anaconda3/envs/fml/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 60, in _try_crossover
    [
```

**Comment by not522** [comment]
I found the following code reproduce the error.

```python
import optuna

def objective1(trial):
    trial.suggest_float("y", 1e-4, 10, log=True)
    return trial.suggest_float("x", 1e-4, 10, log=True)


study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(seed=2, population_size=2))
study.enqueue_trial({"x": 0., "y": 0.})
study.optimize(objective1, n_trials=20)
```
