### ISSUE TITLE
Make storages pickalable

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#4087]
### Motivation

Currently, some storages are pickalable, but others are not. Specifically, 
- `InMemoryStorage` and `RDBStorage` are pickalable.
- `RedisStorage` and `JournalStorage` are not pickalable.

As a result, the following code will not work in certain environments for `RedisStorage` and `JournalStorage`, but work for `RDBStorage`. This is a variant of the test of `test_multiprocess` in `tests/storage_tests/test_with_server.py`.

```python
import argparse
from concurrent.futures import ProcessPoolExecutor
from typing import Sequence, Tuple

import numpy as np
import redis

import optuna

SQLITE_URL = "sqlite:///test.db"
REDIS_URL = "redis://localhost:6379"
JOURNAL_FILE = "JOURNAL_FILE"


def f(x: float, y: float) -> float:
    return (x - 3) ** 2 + y


def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -10, 10)
    y = trial.suggest_float("y", -10, 10)
    trial.report(x, 0)
    trial.report(y, 1)
    trial.set_user_attr("x", x)
    trial.set_system_attr("y", y)
    return f(x, y)


def run_optimize(args: Tuple[str, str]) -> None:
    study_name = args[0]
    storage = args[1]
    # Create a study
    study = optuna.load_study(study_name=study_name, storage=storage)
    # Run optimization
    study.optimize(objective, n_trials=20)


def _check_trials(trials: Sequence[optuna.trial.FrozenTrial]) -> None:
    # Check trial states.
    assert all(trial.state == optuna.trial.TrialState.COMPLETE for trial in trials)

    # Check trial values and params.
    assert all("x" in trial.params for trial in trials)
    assert all("y" in trial.params for trial in trials)
    assert all(
        np.isclose(
            np.asarray([trial.value for trial in trials]),
            [f(trial.params["x"], trial.params["y"]) for trial in trials],
            atol=1e-4,
        ).tolist()
    )

    # Check intermediate values.
    assert all(len(trial.intermediate_values) == 2 for trial in trials)
    assert all(trial.params["x"] == trial.intermediate_values[0] for trial in trials)
    assert all(trial.params["y"] == trial.intermediate_values[1] for trial in trials)

    # Check attrs.
    assert all(
        np.isclose(
            [trial.user_attrs["x"] for trial in trials],
            [trial.params["x"] for trial in trials],
            atol=1e-4,
        ).tolist()
    )
    assert all(
        np.isclose(
            [trial.system_attrs["y"] for trial in trials],
            [trial.params["y"] for trial in trials],
            atol=1e-4,
        ).tolist()
    )


def get_storage(storage_mode: str) -> optuna.storages.BaseStorage:
    if storage_mode == "sqlite":
        return optuna.storages.RDBStorage(SQLITE_URL)
    elif storage_mode == "redis":
        r = redis.Redis.from_url(REDIS_URL)
        r.flushdb()
        return optuna.storages.RedisStorage(REDIS_URL)
    elif storage_mode == "journal":
        return optuna.storages.JournalStorage(optuna.storages.JournalFileStorage(JOURNAL_FILE))
    elif storage_mode == "journal-redis":
        return optuna.storages.JournalStorage(optuna.storages.JournalRedisStorage(REDIS_URL))
    else:
        assert False, f"Invalid storage mode {storage_mode}"


def test(storage_mode: str):
    storage = get_storage(storage_mode)

    n_workers = 8
    study_name = "TEST"
    try:
        optuna.delete_study(storage=storage, study_name=study_name)
    except Exception as e:
        print(e)
    optuna.create_study(storage=storage, study_name=study_name)
    with ProcessPoolExecutor(n_workers) as pool:
        pool.map(run_optimize, [(study_name, storage)] * n_workers)

    study = optuna.load_study(study_name=study_name, storage=storage)

    trials = study.trials
    assert len(trials) == n_workers * 20

    _check_trials(trials)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("storage_mode", type=str)
    args = parser.parse_args()
    
    test(args.storage_mode)

```

### RDB storage
```
(venv) mamu@HideakinoMacBook-puro journal-redis % python multi-process-test.py sqlite       
[I 2022-10-19 17:59:18,544] A new study created in RDB with name: TEST
[I 2022-10-19 17:59:20,739] Trial 1 finished with value: 8.992824728849602 and parameters: {'x': 5.680388609277751, 'y': 1.8083416321036871}. Best is trial 1 with value: 8.992824728849602.
[I 2022-10-19 17:59:20,788] Trial 2 finished with value: 111.61880208257256 and parameters: {'x': -7.654819792233378, 'y': -1.9063827223955876}. Best is trial 1 with value: 8.992824728849602.
...
[I 2022-10-19 17:59:27,853] Trial 159 finished with value: -9.070786177669167 and parameters: {'x': 3.733918319937146, 'y': -9.60942227800853}. Best is trial 115 with value: -9.889245427539054.
```

### Redis storage
```
(venv) mamu@HideakinoMacBook-puro journal-redis % python multi-process-test.py redis 
/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py:99: ExperimentalWarning: RedisStorage is experimental (supported from v1.4.0). The interface can change in the future.
  return optuna.storages.RedisStorage(REDIS_URL)
'No such study TEST.'
[I 2022-10-19 18:00:00,940] A new study created in Redis with name: TEST
Traceback (most recent call last):
  File "/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py", line 135, in <module>
    test(args.storage_mode)
  File "/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py", line 124, in test
    assert len(trials) == n_workers * 20
AssertionError
```

### Journal storage
```
(venv) mamu@HideakinoMacBook-puro journal-redis % python multi-process-test.py journal 
/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py:101: ExperimentalWarning: JournalStorage is experimental (supported from v3.1.0). The interface can change in the future.
  return optuna.storages.JournalStorage(optuna.storages.JournalFileStorage(JOURNAL_FILE))
[I 2022-10-19 18:00:16,609] A new study created in Journal with name: TEST
Traceback (most recent call last):
  File "/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py", line 135, in <module>
    test(args.storage_mode)
  File "/Users/mamu/Dev/pfn/code_snippets_for_optuna/journal-redis/multi-process-test.py", line 124, in test
    assert len(trials) == n_workers * 20
AssertionError
```

I think one of the standard use cases would be to perform such a multi-process optimization of the study. I suggest making `RedisStorage` and `JournalStorage` pickalable like `RDBStorage`.

### Description

- Make `optuna.storages.RedisStorage` pickalable.
- Make `optuna.storages.JournalStorage` pickalable. The `optuna.storages.JournalFileStorage` and some "lock" classes are already pickalable, so we don't have to do anything for that.
- After https://github.com/optuna/optuna/pull/4086, make `optuna.storages.JournalRedisStorage` pickalable. 

### Alternatives (optional)

We can avoid the above error by creating the storage object in the spawned process as follows.

```python
def run_optimize(args: Tuple[str, str]) -> None:
    study_name = args[0]
    storage_mode = args[1]  # Assume this is not a storage class, but a name to specify it.
    
    # Create a storage
    if storage_mode == "redis":
        storage = optuna.storages.RedisStorage(REDIS_URL)
    elif ...

    # Create a study
    study = optuna.load_study(study_name=study_name, storage=storage)
    # Run optimization
    study.optimize(objective, n_trials=20)
```

**Comment by shu65** [comment]
I think that this issue was solved by https://github.com/optuna/optuna/pull/4130 https://github.com/optuna/optuna/pull/4135 https://github.com/optuna/optuna/pull/4139

**Comment by HideakiImamura** [comment]
Thanks! Let me close this issue.
