### ISSUE TITLE
Failed to run perform_crossover: convert the type of params for categorical suggestions

### ISSUE THREAD

**Issue by trajepl** [optuna/optuna#4192]
### Expected behavior

![image](https://user-images.githubusercontent.com/13343117/202695100-f5e0953e-56e2-4178-b7e8-47b9843f7448.png)
Here are my search spaces where I set all the bool parameter as categorical suggestions. Just observed that it will crash in **trial 49**  both for single objective optimization or multi objectives optimization.

Looks that when it run into perform_crossover, **the date type of bool will be converted to string.**, then the processing failed at _is_contained checking.  The sampler is **"NSGAIISampler"**
![image](https://user-images.githubusercontent.com/13343117/202694596-57dbf97c-6960-4a98-bc2d-8d9eabae25e6.png)

### Environment

- Optuna version: 3.0.2
- Python version: 3.8.14
- OS: Ubunti 18.04
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
best id: 31 best_accuracy: -inf, best_latency: inf
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/jiapli/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/jiapli/workspace/olive2/examples/auto_tuner/optuna experiments.py", line 214, in <module>
    dump_experiments(item[0], exp_times=5, n_trials=100, exp=eval_sampler_for_single_objective, static=item[1])
  File "/home/jiapli/workspace/olive2/examples/auto_tuner/optuna experiments.py", line 207, in dump_experiments
    rls.append(exp(samplers, json_fn=fn, static=static, n_trials=n_trials))
  File "/home/jiapli/workspace/olive2/examples/auto_tuner/optuna experiments.py", line 170, in eval_sampler_for_single_objective
    study.optimize(objective, n_trials=n_trials, callbacks=[_callback])
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/study/_optimize.py", line 187, in _run_trial
    trial = study.ask()
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/study/study.py", line 514, in ask
    trial = trial_module.Trial(self, trial_id)
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/trial/_trial.py", line 54, in __init__
    self._init_relative_params()
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/trial/_trial.py", line 63, in _init_relative_params
    self.relative_params = self.study.sampler.sample_relative(
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/samplers/nsgaii/_sampler.py", line 211, in sample_relative
    child_params = perform_crossover(
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 115, in perform_crossover
    if _is_contained(image.png, search_space):
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/samplers/nsgaii/_crossover.py", line 160, in _is_contained
    if not param_distribution._contains(param_distribution.to_internal_repr(param)):
  File "/home/jiapli/venv/lib/python3.8/site-packages/optuna/distributions.py", line 516, in to_internal_repr
    raise ValueError(f"'{param_value_in_external_repr}' not in {self.choices}.")
ValueError: 'True' not in (False, True).
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by nzw0301** [comment]
Is this issue duplicated with https://github.com/optuna/optuna/issues/3982? If so, the bug is fixed on the master branch.

**Comment by trajepl** [comment]
Oh, thanks, the duplicated issue. Could you help tell that when will we have the release? 

The bug existed till in 3.0.2.
