### ISSUE TITLE
"TypeError: Object of type int64 is not JSON serializable" in LightGBMTunerCV

### ISSUE THREAD

**Issue by yyoshiaki** [optuna/optuna#4209]
### Expected behavior

LightGBMTunerCV raised an error in JSON dump.the 

### Environment

- Optuna version:2.10.1
- Python version:3.9.2
- OS:Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-glibc2.17
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
[W 2022-11-24 11:01:53,972] Trial 0 failed because of the following error: TypeError('Object of type int64 is not JSON serializable')
Traceback (most recent call last):
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 341, in __call__
    self._postprocess(trial, elapsed_secs, average_iteration_time)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 279, in _postprocess
    trial.set_system_attr(_LGBM_PARAMS_KEY, json.dumps(self.lgbm_params))
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
Traceback (most recent call last):
  File "/home/yyasumizu/TCRBERT/src/tcr-bert/221108_pretrained_lgbm_subsample_optuna.py", line 215, in <module>
    tuner.run()
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 546, in run
    self.tune_feature_fraction()
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 571, in tune_feature_fraction
    self._tune_params([param_name], len(param_values), sampler, "feature_fraction")
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 654, in _tune_params
    study.optimize(
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 341, in __call__
    self._postprocess(trial, elapsed_secs, average_iteration_time)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/site-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 279, in _postprocess
    trial.set_system_attr(_LGBM_PARAMS_KEY, json.dumps(self.lgbm_params))
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/yyasumizu/anaconda3/envs/tcrbert/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
feature_fraction, val_score: 0.671225:  14%|##############                                                                                    | 1/7 [13:52:37<83:15:45, 49957.55s/it]
```

### Steps to reproduce

```python
FOLD = 5
NUM_ROUND = 10000
VERBOSE_EVAL = 1
NUM_CLASS = 10

folds = StratifiedKFold(n_splits=FOLD, shuffle=True, random_state=42)

lgb_train = lgb.Dataset(X_train, y_train)

params = {'objective': 'multiclass',
        'metric': 'multi_logloss',
        'num_class': NUM_CLASS,
        'boosting_type': 'gbdt',
        'deterministic':True, 
        'force_row_wise':True
        } 
        
tuner = lgb.LightGBMTunerCV(params, lgb_train, 
    verbose_eval=100, num_boost_round=NUM_ROUND, early_stopping_rounds=100, 
    folds=folds)
    
tuner.run()
```

### Additional context (optional)

 I could solve the error by adding an encoder in `optuna/integration/_lightgbm_tuner/optimize.py` .

```
class MyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)

...

trial.set_system_attr(_LGBM_PARAMS_KEY, json.dumps(self.lgbm_params, cls=MyEncoder))
```

**Comment by nzw0301** [comment]
Could you share the minimal reproducible code?

**Comment by yyoshiaki** [comment]
I created a rep for the reproduction. 
https://github.com/yyoshiaki/reproduce_json_error

**Comment by nzw0301** [comment]
Thanks! Due to the security concern on `pickle`, I've modified the code without the pickled dataset as follows:

```python
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
import optuna.integration.lightgbm as lgb

iris = load_iris()
X_train = iris.data
y_train = iris.target
lgb_train = lgb.Dataset(X_train, y_train)

FOLD = 5
NUM_ROUND = 10000
VERBOSE_EVAL = 1
NUM_CLASS = y_train.max() + 1

folds = StratifiedKFold(n_splits=FOLD, shuffle=True, random_state=42)

lgb_train = lgb.Dataset(X_train, y_train)

params = {'objective': 'multiclass',
        'metric': 'multi_logloss',
        'num_class': NUM_CLASS,
        'boosting_type': 'gbdt',
        'deterministic':True,
        'force_row_wise':True
        }

tuner = lgb.LightGBMTunerCV(params, lgb_train,
    verbose_eval=100, num_boost_round=NUM_ROUND, early_stopping_rounds=100,
    folds=folds)

tuner.run()
```

**Comment by yyoshiaki** [comment]
Okay, Thank you! I fixed my repo as well.

**Comment by nzw0301** [comment]
To fix the issue, we might need to replace with `y_train.max() + 1` with 
```python
NUM_CLASS = len(np.unique(y_train))
```

**Comment by yyoshiaki** [comment]
Thank you very much, it was totally my fault.
