### ISSUE TITLE
Run wrongly marked as failed while still running

### ISSUE THREAD

**Issue by raphaelavalos** [optuna/optuna#4234]
### Expected behavior

Hello,

I am using optuna on a cluster. In my (pretty standard) setting, each job connects to a remote database with optuna to get one set of hyper-parameters, run the experiment and report the result to optuna. The results are also tracked by Weight&Biases.

For some unknown reason **optuna falsely detects some jobs as failed** (as reported by `optuna-dashboard`), while they are still running. Usually this happens at the beginning. Once the job finishes correctly, it tries to report the result to optuna which raises an exception as a failed job can't be updated.

I have tried the following versions of optuna: 3.0.0a2, 3.0.3, 3.0.4.

The error message, which is the consequence of updating a failed run, corresponds to optuna 3.0.0a2, but I am seeing the same behavior of runs wrongly marked as failed on the new version.

### Environment

- Optuna version: 3.0.4
- Python version: 3.9
- OS: Linux

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "/path_to_code/code.py", line 346, in <module>
    search(parameters, parameters.get('study_name', 'study'), parameters.get('n_trials', 1))
  File "/path_to_code/code.py", line 324, in search
    return optimize_hyperparameters(study_name, parameters['env_name'], optimize_trial, n_trials=n_trials)
  File "/path_to_code/code.py", line 61, in optimize_hyperparameters
    return study.optimize(optimize_trial, n_trials=n_trials)
  File "/venv_path/lib/python3.9/site-packages/optuna/study/study.py", line 387, in optimize
    _optimize(
  File "/venv_path/lib/python3.9/site-packages/optuna/study/_optimize.py", line 68, in _optimize
    _optimize_sequential(
  File "/venv_path/lib/python3.9/site-packages/optuna/study/_optimize.py", line 162, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/venv_path/lib/python3.9/site-packages/optuna/study/_optimize.py", line 238, in _run_trial
    study.tell(trial, values=values, state=state)
  File "/venv_path/lib/python3.9/site-packages/optuna/study/study.py", line 662, in tell
    self._storage.set_trial_values(trial_id, values)
  File "/venv_path/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 283, in set_trial_values
    self._backend.set_trial_values(trial_id, values=values)
  File "/venv_path/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 765, in set_trial_values
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/venv_path/lib/python3.9/site-packages/optuna/storages/_base.py", line 722, in check_trial_is_updatable
    raise RuntimeError(
RuntimeError: Trial#750 has already finished and can not be updated.
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by c-bata** [comment]
Thank you for using Optuna! Could you share minimal reproducible codes with us?

**Comment by raphaelavalos** [comment]
I think I have figured it out, this was due to a too strict heartbeat interval.

Original code:
```python
storage = optuna.storages.RDBStorage(
        database_url,
        engine_kwargs=engine_kwargs,
        heartbeat_interval=60,
        grace_period=120,
        failed_trial_callback=RetryFailedTrialCallback(),
    )
```

Changing `grace_period` from `120` to `3600` fixed it for me. You don't need to increase it that much but for my use case this is perfect.
