### ISSUE TITLE
PytorchLightning RuntimeError

### ISSUE THREAD

**Issue by kongqi404** [optuna/optuna#4421]
### Expected behavior

when try run pytorchlightning example.py,i get an error:
RuntimeError: The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.

### Environment

- Optuna version:3.0.5
- Python version:Python version:3.10.8
- OS:Linux-5.4.0-100-generic-x86_64-with-glibc2.35
- (Optional) Other libraries and their versions:
- pytorch lightning version:1.8.3.post1

### Error messages, stack traces, or logs

```shell
Trial 0 failed because of the following error: RuntimeError('The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.')
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/root/autodl-tmp/example.py", line 138, in objective
    trainer.fit(model, datamodule=datamodule)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    verify_loop_configurations(self)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 53, in verify_loop_configurations
    _check_deprecated_callback_hooks(trainer)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 221, in _check_deprecated_callback_hooks
    raise RuntimeError(
RuntimeError: The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.
Traceback (most recent call last):
  File "/root/autodl-tmp/example.py", line 157, in <module>
    study.optimize(objective, n_trials=100, timeout=600)
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 234, in _run_trial
    raise func_err
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/root/autodl-tmp/example.py", line 138, in objective
    trainer.fit(model, datamodule=datamodule)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    verify_loop_configurations(self)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 53, in verify_loop_configurations
    _check_deprecated_callback_hooks(trainer)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 221, in _check_deprecated_callback_hooks
    raise RuntimeError(
RuntimeError: The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.
```

### Steps to reproduce

1.run example.py
```python
python example.py
```

**Comment by nzw0301** [comment]
Could you use the latest optuna? It should resolve the error.

**Comment by kongqi404** [comment]
> Could you use the latest optuna? It should resolve the error.

After updating, the problem still occurs：
```
root@autodl-container-6b9011bf9e-cc5c5d05:~/autodl-tmp# python3 -c 'import optuna; print(f"- Optuna version:{optuna.__version__}")'
- Optuna version:3.1.0
root@autodl-container-6b9011bf9e-cc5c5d05:~/autodl-tmp# python3 example.py 
[I 2023-02-15 12:09:21,698] A new study created in memory with name: no-name-1c885990-590e-4c81-a926-507dc98ef931
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[W 2023-02-15 12:09:21,756] Trial 0 failed with parameters: {'n_layers': 3, 'dropout': 0.2250779640392501, 'n_units_l0': 6, 'n_units_l1': 4, 'n_units_l2': 7} because of the following error: RuntimeError('The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.').
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/root/autodl-tmp/example.py", line 138, in objective
    trainer.fit(model, datamodule=datamodule)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    verify_loop_configurations(self)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 53, in verify_loop_configurations
    _check_deprecated_callback_hooks(trainer)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 221, in _check_deprecated_callback_hooks
    raise RuntimeError(
RuntimeError: The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.
[W 2023-02-15 12:09:21,757] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/root/autodl-tmp/example.py", line 157, in <module>
    study.optimize(objective, n_trials=100, timeout=600)
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/study.py", line 425, in optimize
    _optimize(
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/root/miniconda3/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/root/autodl-tmp/example.py", line 138, in objective
    trainer.fit(model, datamodule=datamodule)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    verify_loop_configurations(self)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 53, in verify_loop_configurations
    _check_deprecated_callback_hooks(trainer)
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 221, in _check_deprecated_callback_hooks
    raise RuntimeError(
RuntimeError: The `on_init_start` callback hook was deprecated in v1.6 and is no longer supported as of v1.8.
```

**Comment by nzw0301** [comment]
Thank you for sharing the version info. I meant latest version of the master branch, not latest stable.

**Comment by kongqi404** [comment]
> Thank you for sharing the version info. I meant the latest version of the master branch, not latest stable (`3.1.0`):
> 
> ```shell
> git clone git@github.com:optuna/optuna.git
> cd optuna
> pip install -e .
> ```

Thanks, this error has been resolved.
