### ISSUE TITLE
OptunaSearchCV.error_score not working

### ISSUE THREAD

**Issue by jckkvs** [optuna/optuna#4557]
### Expected behavior

In my understanding, OptunaSearchCV's error_score is a setting for ignoring errors during fit.

sklearn's GridSearchCV can also set error_score.

For example, the n_components of PLSRegression need to be changed according to the dataset, so I think it is necessary to carefully set the maximum value of param_range or param_distributions.

Here, I verified the operation of GridSearchCV and OptunaSearchCV.

Is this by design, or is it a bug that behaves differently than expected?

I would have expected the best_params_ to be sought even if param_distributions were specified in numbers greater than n_features and some trials were not possible.

### Environment

- Optuna version:3.1.0
- Python version:3.10
- OS:windows 10
- sklearn version:1.2.1

### Error messages, stack traces, or logs

```shell
[I 2023-03-30 11:47:51,179] A new study created in memory with name: no-name-537777eb-4267-4ec4-90a0-c178cbbe369e
[W 2023-03-30 11:47:51,194] Trial 0 failed with parameters: {'n_components': 189} because of the following error: ValueError('\nAll the 10 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score=\'raise\'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n10 fits failed with the following error:\nTraceback (most recent call last):\n  File "C:\\Users\\11665307\\Anaconda3\\envs\\py310\\lib\\site-packages\\sklearn\\model_selection\\_validation.py", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File "C:\\Users\\11665307\\Anaconda3\\envs\\py310\\lib\\site-packages\\sklearn\\cross_decomposition\\_pls.py", line 660, in fit\n    super().fit(X, Y)\n  File "C:\\Users\\11665307\\Anaconda3\\envs\\py310\\lib\\site-packages\\sklearn\\cross_decomposition\\_pls.py", line 251, in fit\n    raise ValueError(\nValueError: `n_components` upper bound is 100. Got 189 instead. Reduce `n_components`.\n').
Traceback (most recent call last):
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\optuna\integration\sklearn.py", line 230, in __call__
    scores = cross_validate(
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 285, in cross_validate
    _warn_or_raise_about_fit_failures(results, error_score)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 367, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\cross_decomposition\_pls.py", line 660, in fit
    super().fit(X, Y)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\cross_decomposition\_pls.py", line 251, in fit
    raise ValueError(
ValueError: `n_components` upper bound is 100. Got 189 instead. Reduce `n_components`.

[W 2023-03-30 11:47:51,195] Trial 0 failed with value None.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [15], in <module>
----> 1 opcv.fit(X,y)

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\integration\sklearn.py:900, in OptunaSearchCV.fit(self, X, y, groups, **fit_params)
    880 objective = _Objective(
    881     self.estimator,
    882     self.param_distributions,
   (...)
    892     self.scorer_,
    893 )
    895 _logger.info(
    896     "Searching the best hyperparameters using {} "
    897     "samples...".format(_num_samples(self.sample_indices_))
    898 )
--> 900 self.study_.optimize(
    901     objective,
    902     n_jobs=self.n_jobs,
    903     n_trials=self.n_trials,
    904     timeout=self.timeout,
    905     callbacks=self.callbacks,
    906 )
    908 _logger.info("Finished hyperparemeter search!")
    910 if self.refit:

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\study\study.py:425, in Study.optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    321 def optimize(
    322     self,
    323     func: ObjectiveFuncType,
   (...)
    330     show_progress_bar: bool = False,
    331 ) -> None:
    332     """Optimize an objective function.
    333 
    334     Optimization is done by choosing a suitable set of hyperparameter values from a given
   (...)
    422             If nested invocation of this method occurs.
    423     """
--> 425     _optimize(
    426         study=self,
    427         func=func,
    428         n_trials=n_trials,
    429         timeout=timeout,
    430         n_jobs=n_jobs,
    431         catch=tuple(catch) if isinstance(catch, Iterable) else (catch,),
    432         callbacks=callbacks,
    433         gc_after_trial=gc_after_trial,
    434         show_progress_bar=show_progress_bar,
    435     )

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\study\_optimize.py:66, in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     64 try:
     65     if n_jobs == 1:
---> 66         _optimize_sequential(
     67             study,
     68             func,
     69             n_trials,
     70             timeout,
     71             catch,
     72             callbacks,
     73             gc_after_trial,
     74             reseed_sampler_rng=False,
     75             time_start=None,
     76             progress_bar=progress_bar,
     77         )
     78     else:
     79         if n_jobs == -1:

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\study\_optimize.py:163, in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    160         break
    162 try:
--> 163     frozen_trial = _run_trial(study, func, catch)
    164 finally:
    165     # The following line mitigates memory problems that can be occurred in some
    166     # environments (e.g., services that use computing containers such as GitHub Actions).
    167     # Please refer to the following PR for further details:
    168     # https://github.com/optuna/optuna/pull/325.
    169     if gc_after_trial:

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\study\_optimize.py:251, in _run_trial(study, func, catch)
    244         assert False, "Should not reach."
    246 if (
    247     frozen_trial.state == TrialState.FAIL
    248     and func_err is not None
    249     and not isinstance(func_err, catch)
    250 ):
--> 251     raise func_err
    252 return frozen_trial

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\study\_optimize.py:200, in _run_trial(study, func, catch)
    198 with get_heartbeat_thread(trial._trial_id, study._storage):
    199     try:
--> 200         value_or_values = func(trial)
    201     except exceptions.TrialPruned as e:
    202         # TODO(mamu): Handle multi-objective cases.
    203         state = TrialState.PRUNED

File ~\Anaconda3\envs\py310\lib\site-packages\optuna\integration\sklearn.py:230, in _Objective.__call__(self, trial)
    228     scores = self._cross_validate_with_pruning(trial, estimator)
    229 else:
--> 230     scores = cross_validate(
    231         estimator,
    232         self.X,
    233         self.y,
    234         cv=self.cv,
    235         error_score=self.error_score,
    236         fit_params=self.fit_params,
    237         groups=self.groups,
    238         return_train_score=self.return_train_score,
    239         scoring=self.scoring,
    240     )
    242 self._store_scores(trial, scores)
    244 return trial.user_attrs["mean_test_score"]

File ~\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py:285, in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    265 parallel = Parallel(n_jobs=n_jobs, verbose=verbose, pre_dispatch=pre_dispatch)
    266 results = parallel(
    267     delayed(_fit_and_score)(
    268         clone(estimator),
   (...)
    282     for train, test in cv.split(X, y, groups)
    283 )
--> 285 _warn_or_raise_about_fit_failures(results, error_score)
    287 # For callabe scoring, the return type is only know after calling. If the
    288 # return type is a dictionary, the error scores can now be inserted with
    289 # the correct key.
    290 if callable(scoring):

File ~\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py:367, in _warn_or_raise_about_fit_failures(results, error_score)
    360 if num_failed_fits == num_fits:
    361     all_fits_failed_message = (
    362         f"\nAll the {num_fits} fits failed.\n"
    363         "It is very likely that your model is misconfigured.\n"
    364         "You can try to debug the error by setting error_score='raise'.\n\n"
    365         f"Below are more details about the failures:\n{fit_errors_summary}"
    366     )
--> 367     raise ValueError(all_fits_failed_message)
    369 else:
    370     some_fits_failed_message = (
    371         f"\n{num_failed_fits} fits failed out of a total of {num_fits}.\n"
    372         "The score on these train-test partitions for these parameters"
   (...)
    376         f"Below are more details about the failures:\n{fit_errors_summary}"
    377     )

ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\cross_decomposition\_pls.py", line 660, in fit
    super().fit(X, Y)
  File "C:\Users\11665307\Anaconda3\envs\py310\lib\site-packages\sklearn\cross_decomposition\_pls.py", line 251, in fit
    raise ValueError(
ValueError: `n_components` upper bound is 100. Got 189 instead. Reduce `n_components`.
```

### Steps to reproduce

1.
2.
3.
```
from sklearn.model_selection import GridSearchCV
from optuna.integration import OptunaSearchCV
from sklearn.cross_decomposition import PLSRegression
from sklearn.datasets import make_regression
from optuna.distributions import IntDistribution
import numpy as np

X,y = make_regression()
model = PLSRegression()
param_grid = {"n_components":[5,10,20,105, 200]}
gscv = GridSearchCV(model, param_grid, error_score=np.nan)
gscv.fit(X,y)
print(gscv.best_params_)
>>>{'n_components': 20}

param_distributions = {"n_components": IntDistribution(1,200)}
opcv = OptunaSearchCV(model, param_distributions, error_score=np.nan)
opcv.fit(X,y)
>>> ValueError: 
>>> All the 5 fits failed.
print(opcv.best_params_)
>>> NotFittedError      
```

**Comment by nzw0301** [comment]
Thank you for reporting the issue. For completeness, I've copied the shared code without console prefix `>>>`:
```python
from sklearn.model_selection import GridSearchCV
from optuna.integration import OptunaSearchCV
from sklearn.cross_decomposition import PLSRegression
from sklearn.datasets import make_regression
from optuna.distributions import IntDistribution
import numpy as np

X,y = make_regression()
model = PLSRegression()
param_grid = {"n_components":[5,10,20,105, 200]}
gscv = GridSearchCV(model, param_grid, error_score=np.nan)
gscv.fit(X,y)
print(gscv.best_params_)
# >>>{'n_components': 20}

param_distributions = {"n_components": IntDistribution(1,200)}
opcv = OptunaSearchCV(model, param_distributions, error_score=np.nan)
opcv.fit(X,y)

print(opcv.best_params_)
```
