### ISSUE TITLE
Can not save study with sqlite3  but in memory works

### ISSUE THREAD

**Issue by TTK95** [optuna/optuna#4584]
### Expected behavior

I can't save my study with sqlite3 file path. But with :memroy: it works:

```
import logging
import sys
import optuna
# Add stream handler of stdout to show the messages
optuna.logging.get_logger("optuna").addHandler(logging.StreamHandler(sys.stdout))
study_name = "example-study"  # Unique identifier of the study.
storage_name = "sqlite:///:memory:"
study = optuna.create_study(study_name=study_name, storage=storage_name)
A new study created in RDB with name: example-study
A new study created in RDB with name: example-study
[I 2023-04-06 10:00:27,398] A new study created in RDB with name: example-study
```

But I want to store my study not in memory.

### Environment

- Optuna version: 2.10.1
- Python version: 3.10.4
- OS: Ubuntu 22.04.2 LTS
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "/snap/pycharm-professional/331/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 10, in <module>
  File "/home/tte/anaconda3/envs/ISEAnet/lib/python3.10/site-packages/optuna/study/study.py", line 1136, in create_study
    storage = storages.get_storage(storage)
  File "/home/tte/anaconda3/envs/ISEAnet/lib/python3.10/site-packages/optuna/storages/__init__.py", line 31, in get_storage
    return _CachedStorage(RDBStorage(storage))
  File "/home/tte/anaconda3/envs/ISEAnet/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 187, in __init__
    self._version_manager.check_table_schema_compatibility()
  File "/home/tte/anaconda3/envs/ISEAnet/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 1310, in check_table_schema_compatibility
    current_version = self.get_current_version()
  File "/home/tte/anaconda3/envs/ISEAnet/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 1337, in get_current_version
    assert version is not None
AssertionError
```

### Steps to reproduce

1. try example from doc
2. Error
```python
import logging
import sys

import optuna

# Add stream handler of stdout to show the messages
optuna.logging.get_logger("optuna").addHandler(logging.StreamHandler(sys.stdout))
study_name = "example-study"  # Unique identifier of the study.
storage_name = "sqlite:///{}.db".format(study_name)
study = optuna.create_study(study_name=study_name, storage=storage_name)
```

**Comment by nzw0301** [comment]
I could not reproduce the error. Could you run the code with the latest Optuna?

**Comment by TTK95** [comment]
If I use the latest Optuna, I cant use the PyTorchLightningPruningCallback with Lightning 2.0.0. I found this working version and would like to use it until the latest Optuna version fixed this other issue.

**Comment by nzw0301** [comment]
Please re-open the issue if the problem happens with the latest Optuna since this repo does not develop Optuna 2.x anymore. Pytorch-Lightning too fastly introduces backward breaking changes, which causes this slow support by Optuna.   Thank you for your understanding.
