### ISSUE TITLE
XGBoostPruningCallback errors out when called with `validation-logloss` metric

### ISSUE THREAD

**Issue by shivance** [optuna/optuna#4634]
### Expected behavior

Optuna should be able to search best hyperparameters for the xgboost model used

### Environment

- Optuna version: 3.1.0
- Python version: 3.7
- OS: Ubuntu
- (Optional) Other libraries and their versions: Using Kaggle Kernels

### Error messages, stack traces, or logs

```shell
[I 2023-04-25 18:57:51,090] A new study created in memory with name: no-name-4c75aa43-aced-473b-86d3-859fc46936a1
[W 2023-04-25 18:57:51,138] Trial 0 failed with parameters: {} because of the following error: KeyError('validation-logloss').
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_27/3631932161.py", line 28, in objective
    callbacks=[optuna.integration.XGBoostPruningCallback(trial, "validation-logloss")])
  File "/opt/conda/lib/python3.7/site-packages/xgboost/core.py", line 575, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py", line 1411, in fit
    callbacks=callbacks,
  File "/opt/conda/lib/python3.7/site-packages/xgboost/core.py", line 575, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/xgboost/training.py", line 182, in train
    if cb_container.after_iteration(bst, i, dtrain, evals):
  File "/opt/conda/lib/python3.7/site-packages/xgboost/callback.py", line 247, in after_iteration
    for c in self.callbacks)
  File "/opt/conda/lib/python3.7/site-packages/xgboost/callback.py", line 247, in <genexpr>
    for c in self.callbacks)
  File "/opt/conda/lib/python3.7/site-packages/optuna/integration/xgboost.py", line 69, in after_iteration
    current_score = evaluation_results[self._observation_key]
KeyError: 'validation-logloss'
[W 2023-04-25 18:57:51,140] Trial 0 failed with value None.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_27/3631932161.py in <module>
     35 
     36 study = optuna.create_study(direction="minimize")
---> 37 study.optimize(objective, n_trials=5)

/opt/conda/lib/python3.7/site-packages/optuna/study/study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    432             callbacks=callbacks,
    433             gc_after_trial=gc_after_trial,
--> 434             show_progress_bar=show_progress_bar,
    435         )
    436 

/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     74                 reseed_sampler_rng=False,
     75                 time_start=None,
---> 76                 progress_bar=progress_bar,
     77             )
     78         else:

/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    161 
    162         try:
--> 163             frozen_trial = _run_trial(study, func, catch)
    164         finally:
    165             # The following line mitigates memory problems that can be occurred in some

/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py in _run_trial(study, func, catch)
    249         and not isinstance(func_err, catch)
    250     ):
--> 251         raise func_err
    252     return frozen_trial
    253 

/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py in _run_trial(study, func, catch)
    198     with get_heartbeat_thread(trial._trial_id, study._storage):
    199         try:
--> 200             value_or_values = func(trial)
    201         except exceptions.TrialPruned as e:
    202             # TODO(mamu): Handle multi-objective cases.

/tmp/ipykernel_27/3631932161.py in objective(trial)
     26     model_xgb.fit(dev_X, dev_y, early_stopping_rounds=0,
     27                  eval_set=[(val_X, val_y)], verbose=1000,
---> 28                  callbacks=[optuna.integration.XGBoostPruningCallback(trial, "validation-logloss")])
     29 
     30     y_pred = model_xgb.predict_proba(val_X)

/opt/conda/lib/python3.7/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    573         for k, arg in zip(sig.parameters, args):
    574             kwargs[k] = arg
--> 575         return f(**kwargs)
    576 
    577     return inner_f

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)
   1409             verbose_eval=verbose,
   1410             xgb_model=model,
-> 1411             callbacks=callbacks,
   1412         )
   1413 

/opt/conda/lib/python3.7/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    573         for k, arg in zip(sig.parameters, args):
    574             kwargs[k] = arg
--> 575         return f(**kwargs)
    576 
    577     return inner_f

/opt/conda/lib/python3.7/site-packages/xgboost/training.py in train(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks, custom_metric)
    180             break
    181         bst.update(dtrain, i, obj)
--> 182         if cb_container.after_iteration(bst, i, dtrain, evals):
    183             break
    184 

/opt/conda/lib/python3.7/site-packages/xgboost/callback.py in after_iteration(self, model, epoch, dtrain, evals)
    245             self._update_history(metric_score, epoch)
    246         ret = any(c.after_iteration(model, epoch, self.history)
--> 247                   for c in self.callbacks)
    248         return ret
    249 

/opt/conda/lib/python3.7/site-packages/xgboost/callback.py in <genexpr>(.0)
    245             self._update_history(metric_score, epoch)
    246         ret = any(c.after_iteration(model, epoch, self.history)
--> 247                   for c in self.callbacks)
    248         return ret
    249 

/opt/conda/lib/python3.7/site-packages/optuna/integration/xgboost.py in after_iteration(self, model, epoch, evals_log)
     67                         evaluation_results[key] = scores[-1]
     68 
---> 69             current_score = evaluation_results[self._observation_key]
     70             self._trial.report(current_score, step=epoch)
     71             if self._trial.should_prune():

KeyError: 'validation-logloss'
```

### Steps to reproduce

```python
import xgboost as xgb
import optuna

X = df_train[features]
y = df_train[target]

def objective(trial):
    
    dev_X, val_X, dev_y, val_y = train_test_split(X, y)

    xgb_params = {
                'n_estimators': 1000,
                'learning_rate': 0.01,
                'max_depth': 3,
                'subsample': 0.8,
                'colsample_bytree': 0.1,
                'n_jobs': -1,
                'eval_metric': 'mlogloss',
                'objective': 'multi:softprob',
                'tree_method': 'hist',
                'random_state': 42,
            }

    model_xgb = xgb.XGBClassifier(**xgb_params)

    model_xgb.fit(dev_X, dev_y, early_stopping_rounds=0,
                 eval_set=[(val_X, val_y)], verbose=1000,
                 callbacks=[optuna.integration.XGBoostPruningCallback(trial, "validation-logloss")])
    
    y_pred = model_xgb.predict_proba(val_X)
#     map3 = MAP3Metric(y_pred_xgb).mapk_score(val_y)
    score = log_loss(val_y, y_pred)
    
    return score

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=5)
```

### Additional context (optional)

)

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us? The dataset definition is missing.
