### ISSUE TITLE
ValueError: Expected a parent with PyTorchLightningPruningCallback

### ISSUE THREAD

**Issue by AhmetZamanis** [optuna/optuna#4689]
### Expected behavior

Hi, I have an issue with `PyTorchLightningPruningCallback`. I'm not sure if it's related to an already known issue, but I installed Optuna from the master branch as directed in #4499 , and it did not solve it. I was able to find an apparent workaround, which I'll share last.

The issue occurs when I try to perform an Optuna study with a Lightning model, and pass a `PyTorchLightningPruningCallback` to the `Trainer`'s list of `callbacks`. The study immediately terminates at trial 0, with the error `ValueError: Expected a parent`. The traceback is shared below.

### Environment

- Optuna version: 3.2.0.dev0 (installed from master branch)
- Python version: 3.10.8
- OS: Windows-10-10.0.22621-SP0
- pytorch-lightning version: 2.0.1.post0

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "<string>", line 25, in objective_nn
  File "<string>", line 54, in validate_nn
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\utilities\argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 421, in __init__
    self._callback_connector.on_trainer_init(
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 79, in on_trainer_init
    _validate_callbacks_list(self.trainer.callbacks)
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 252, in _validate_callbacks_list
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 252, in <listcomp>
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\utilities\model_helpers.py", line 34, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent
[W 2023-05-17 15:36:51,065] Trial 0 failed with value None.
ValueError: Expected a parent
```

### Steps to reproduce

The function `validate_nn`, referenced in the traceback above, is a custom validation function I use in my Optuna objective (`objective_nn`) to report the CV score for a trial. It works with no issues when `PyTorchLightningPruningCallback` is not added to the list of callbacks. The code below is only the relevant portion of `validate_nn`, but let me know if I need to share the code for the entire function, the Optuna objective & study.

```python
import optuna
from optuna.integration.pytorch_lightning import PyTorchLightningPruningCallback
import torch, torchvision, torchmetrics
import lightning.pytorch as pl

callbacks = []
callback_pruner = PyTorchLightningPruningCallback(trial, monitor = "val_avg_precision")
callbacks.append(callback_pruner)

# Create trainer
trainer = pl.Trainer(
      max_epochs = 500,
      log_every_n_steps = 5,
      accelerator = "gpu", devices = "auto", precision = "16-mixed", 
      callbacks = callbacks,
      enable_model_summary = False, 
      logger = True,
      enable_progress_bar = False, 
      enable_checkpointing = False
    )
  
# Create & train model
model = SeluDropoutModel(hyperparams_dict = hyperparams_dict)
trainer.fit(model, train_loader, val_loader)   
```

The error itself happens after I create the Optuna study, and call `study.optimize()`.

### Additional context (optional)

I found a similar issue discussed [here](https://github.com/ray-project/ray/issues/33426), with Ray's `TuneReportCallback`. It's suggested the issue stems from Lightning's change from the project structure `lightning_pytorch` to `pytorch.lightning` in version 2.0.

 A [workaround](https://github.com/ray-project/ray/issues/33426#issuecomment-1481951889) is suggested at the end of the discussion, which I adapted to Optuna with the following code:
```python
class OptunaPruning(PyTorchLightningPruningCallback, pl.Callback):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```
With this custom version of the callback, I can perform the study without errors, with pruning apparently working as intended.

**Comment by nzw0301** [comment]
The current Optuna doesn't support PyTorch-lightning 2.0 as described by https://github.com/optuna/optuna/issues/4524. 

Thank you for sharing your workaround. It would be helpful to resolve the issue.

**Comment by HideakiImamura** [comment]
Currently, our pytorch lightning integration supports PyTorch-lightning 2.0, but our unit-tests don't support it as https://github.com/optuna/optuna/issues/4524. So, we need to work on this issue.

**Comment by HideakiImamura** [comment]
Could you try the latest optuna, i.e., 3.3.0.dev?

**Comment by AhmetZamanis** [comment]
I'll try it and get back as soon as I can.

**Comment by AhmetZamanis** [comment]
Update: I uninstalled Optuna and reinstalled the 3.3.0.dev version from the master branch, and confirmed it with
`print(f"- Optuna version:{optuna.__version__}").`
I re-ran the same code, replacing my workaround version of the callback with the default `PyTorchLightningPruningCallback`. I still seem to be getting the same error. I am sharing the callback below (I think it's the same as before).
```python
Traceback (most recent call last):
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "<string>", line 25, in objective_nn
  File "<string>", line 54, in validate_nn
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\utilities\argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 421, in __init__
    self._callback_connector.on_trainer_init(
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 79, in on_trainer_init
    _validate_callbacks_list(self.trainer.callbacks)
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 252, in _validate_callbacks_list
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\trainer\connectors\callback_connector.py", line 252, in <listcomp>
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "C:\Users\PC\DOCUME~1\Work\DATASC~1\GitHub\USEDCA~1\venv\lib\site-packages\lightning\pytorch\utilities\model_helpers.py", line 34, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent
[W 2023-06-22 14:05:47,561] Trial 0 failed with value None.
ValueError: Expected a parent
```
The Python, Windows, Lightning versions and the virtual environment are all the same as before. The workaround I previously shared still works fine.

**Comment by Alnusjaponica** [comment]
Hi, I found a similar issue, https://github.com/Lightning-AI/lightning/issues/17485, and this says that using two different import style causes the error. Currently, 
```
import pytorch_lightning as pl
```
is used in Optuna library and [example code](https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_lightning_simple.py) which uses the same style keeps working too. Does changing importing style
```
import lightning.pytorch as pl
```
to
```
import pytorch_lightning as pl
```
solves your problem?

**Comment by AhmetZamanis** [comment]
That does work, but I originally reported the issue because I believed the `lighting.pytorch` import was to be the default in the future, and `pytorch_lightning` was being phased out. Turns out that's also partially wrong, according to [this post](https://github.com/Lightning-AI/lightning/discussions/16688#discussioncomment-4927515). TLDR; they suggest using `pip install lightning, import lightning as L` in the future.

I guess this is not an "issue" but more of a "warning", so I'll go ahead and close it. Thanks to all.

**Comment by Alnusjaponica** [comment]
Thanks for the reference. We are going to discuss backward compatibility and try to update them.
