### ISSUE TITLE
Can't upgrade MySQL database schema from v2.6.0.a → v3.0.0.a

### ISSUE THREAD

**Issue by a7brusco** [optuna/optuna#4878]
### Expected behavior

Upgrading the database schema from v2.6.0.a → v3.0.0.a with `optuna storage upgrade --storage <mysql_database>`

### Environment

- Optuna version: 3.3.0
- Python version: 3.10.9
- OS: Windows-10-10.0.19045-SP0
- (Optional) Other libraries and their versions: `mysqlclient==2.2.0`

### Error messages, stack traces, or logs

```shell
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade v2.6.0.a -> v3.0.0.a, unify existing distributions to {int,float} distribution
d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\distributions.py:598: FutureWarning: IntUniformDistribution has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :class:`~optuna.distributions.IntDistribution` instead.
  return cls(**json_dict["attributes"])
d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\distributions.py:598: FutureWarning: UniformDistribution has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :class:`~optuna.distributions.FloatDistribution` instead.
  return cls(**json_dict["attributes"])
ERROR [sqlalchemy.pool.impl.NullPool] Error closing cursor
Traceback (most recent call last):
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\query.py", line 2830, in __iter__
    yield from result  # type: ignore
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 2199, in _safe_close_cursor
    cursor.close()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 103, in close
    self._discard()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 89, in _discard
    self._result.discard()
MySQLdb.OperationalError: (2006, '')
Traceback (most recent call last):
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1934, in _exec_single_context
    self.dialect.do_executemany(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\dialects\mysql\mysqldb.py", line 175, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 250, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 250, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self._discard()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.
MySQLdb.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path   
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\antoine.brusco\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code  
    exec(code, run_globals)
  File "D:\Git\NeuralNetworkInternship\src_v2\apps\tmp.py", line 17, in <module>
    storage.upgrade()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\storages\_rdb\storage.py", line 956, in upgrade
    self._version_manager.upgrade()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\storages\_rdb\storage.py", line 1131, in upgrade
    alembic_command.upgrade(config, "head")
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\command.py", line 382, in upgrade
    script.run_env()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\script\base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\util\pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\util\pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\storages\_rdb\alembic\env.py", line 79, in <module>
    run_migrations_online()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\optuna\storages\_rdb\alembic\env.py", line 73, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\runtime\environment.py", line 922, in run_migrations
    self.get_context().run_migrations(**kw)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\alembic\runtime\migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "D:\Git\NeuralNetworkInternship\.venv\optuna_env\Lib\site-packages\optuna\storages\_rdb\alembic\versions\v3.0.0.a.py", line 169, in upgrade
    raise e
  File "D:\Git\NeuralNetworkInternship\.venv\optuna_env\Lib\site-packages\optuna\storages\_rdb\alembic\versions\v3.0.0.a.py", line 162, in upgrade
    persist(session, distributions)
  File "D:\Git\NeuralNetworkInternship\.venv\optuna_env\Lib\site-packages\optuna\storages\_rdb\alembic\versions\v3.0.0.a.py", line 141, in persist
    session.bulk_save_objects(distributions)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\session.py", line 4412, in bulk_save_objects
    self._bulk_save_mappings(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\session.py", line 4582, in _bulk_save_mappings
    with util.safe_reraise():
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\session.py", line 4563, in _bulk_save_mappings
    bulk_persistence._bulk_update(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\bulk_persistence.py", line 332, in _bulk_update
    persistence._emit_update_statements(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\orm\persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    return meth(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\engine\base.py", line 1934, in _exec_single_context
    self.dialect.do_executemany(
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\sqlalchemy\dialects\mysql\mysqldb.py", line 175, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 250, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 250, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self._discard()
  File "d:\Git\NeuralNetworkInternship\.venv\optuna_env\lib\site-packages\MySQLdb\cursors.py", line 95, in _discard
    while con.next_result() == 0:  # -1 means no more data.
sqlalchemy.exc.ProgrammingError: (MySQLdb.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: UPDATE trial_params SET distribution_json=%s WHERE trial_params.param_id = %s]
[parameters: [('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 1), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, 
"low": 2, "high": 10}}', 2), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 3), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 4), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 5), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 6), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 7), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 1, "low": 2, "high": 10}}', 8)  ... displaying 10 of 5000 total bound parameter sets ...  ('{"name": "IntDistribution", "attributes": {"log": false, "step": 2, "low": 20, "high": 512}}', 4999), ('{"name": "IntDistribution", "attributes": {"log": false, "step": 2, "low": 20, "high": 22050}}', 5000)]]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Steps to reproduce

1. Upgrade the database schema using either the CLI (`optuna storage upgrade --storage <URL>`) or the code below
```python
from optuna.storages import RDBStorage

user = <db_user> # all permissions granted
password = <user_pswd>
host = <db_url>
port = <usually_3306>
db = <name_of_db>

optuna_db = f"mysql://{user}:{password}@{host}:{port}/{db}"
storage = RDBStorage(optuna_db, skip_compatibility_check=True)
storage.upgrade()
```

### Additional context (optional)

I'm using a fairly heavy database, since I've been using Optuna for some time.
I backed up my database before trying to upgrade it, and the `.sql` file weights 500 MB of data.
I also tried to update the database progressively (starting with Optuna version 3.0.0 until the last one) but the result is the same for Optuna 3.0.0.

**Comment by a7brusco** [comment]
Find a bit of time to debug that !

**Comment by a7brusco** [comment]
Find a bit of time to debug that !

After a lot of tries, I've managed to migrate the database (quick remember, my database is pretty huge).

I've commented the block of code here: https://github.com/optuna/optuna/blob/c21fe6253343950f31d9ae0bc13be384236335e6/optuna/storages/_rdb/alembic/versions/v3.0.0.a.py#L161-L163

I suppose during the migration to the schema 3.0.0a, I've reached the 5000 rows to update (the 5000 corresponds to the max `BATCH_SIZE` value set at the beginning of the script).
I didn't really understand why that first batch couldn't be updated properly, tho.

Commenting those lines above disabled the batch update process, the migration is done on all rows simultaneously, so it's a bit long (like around 5 min) but it's working.

**Comment by KirtiPriya07** [comment]
do u still need help?

**Comment by a7brusco** [comment]
Not really, I've got it working with the small workaround I've described.
