### ISSUE TITLE
Optuna hyperparameter search does not handle CUDA memory allocator, reducing maximum batch size

### ISSUE THREAD

**Issue by azagajewski** [optuna/optuna#4934]
### Expected behavior

When I hyperparemeter tune a keras deep learning model using study.optimize on a GPU, I expect the memory performance to be the same compared when I train without tuning - for example, if I can load a batch size of 8 without optuna, I expect to be able to load a batch size of 8 with optuna. This is not the case - using optuna I can only reliably load a batch size of 2. 

### Environment

- Optuna version: 3.3.0
- Python version: 3.10.2
- OS: Linux-5.15.0-1027-aws-x86_64-with-glibc2.31
- (Optional) Other libraries and their versions:
- Tensorflow: 2.13.0

### Error messages, stack traces, or logs

```shell
[W 2023-09-15 15:44:38,812] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/tensorflow/python/ops/variable_scope.py", line 2840, in variable_creator_scope
    yield
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/cli.py", line 119, in main
    harness.tune_parameters()
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 388, in tune_parameters
    study.optimize(objective_wrapper, n_trials=trials)   
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/study.py", line 442, in optimize
    _optimize(
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 386, in <lambda>
    objective_wrapper = lambda trial: optuna_objective(trial, lr_range=lr_range, bs_range=bs_range) #Configure objective with correct bounds
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 362, in optuna_objective
    history = self.train(optimizer = optimizer, learning_rate = learning_rate, batch_size = batch_size, epochs = epochs, output_dir = output_dir, callbacks = prune_callback) #Parse other training parameters from outer scope
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 336, in train
    return self.model.fit(training_dataset, validation_data=validation_dataset, epochs=epochs, callbacks=callbacks, verbose=2)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 550, in safe_patch_function
    patch_function.call(call_original, *args, **kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 168, in call
    return cls().__call__(original, *args, **kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 179, in __call__
    raise e
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 172, in __call__
    return self._patch_implementation(original, *args, **kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 230, in _patch_implementation
    result = super()._patch_implementation(original, *args, **kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/tensorflow/__init__.py", line 1268, in _patch_implementation
    history = original(inst, *args, **kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 533, in call_original
    return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 468, in call_original_fn_with_event_logging
    original_fn_result = original_fn(*og_args, **og_kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 530, in _original_fn
    original_result = original(*_og_args, **_og_kwargs)
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:

Detected at node 'encoder/conv4_block16_1_conv/Conv2D' defined at (most recent call last):
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/bin/vae", line 8, in <module>
      sys.exit(main())
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/cli.py", line 119, in main
      harness.tune_parameters()
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 388, in tune_parameters
      study.optimize(objective_wrapper, n_trials=trials)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/study.py", line 442, in optimize
      _optimize(
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
      _optimize_sequential(
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
      frozen_trial = _run_trial(study, func, catch)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
      value_or_values = func(trial)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 386, in <lambda>
      objective_wrapper = lambda trial: optuna_objective(trial, lr_range=lr_range, bs_range=bs_range) #Configure objective with correct bounds
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 362, in optuna_objective
      history = self.train(optimizer = optimizer, learning_rate = learning_rate, batch_size = batch_size, epochs = epochs, output_dir = output_dir, callbacks = prune_callback) #Parse other training parameters from outer scope
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 336, in train
      return self.model.fit(training_dataset, validation_data=validation_dataset, epochs=epochs, callbacks=callbacks, verbose=2)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 550, in safe_patch_function
      patch_function.call(call_original, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 168, in call
      return cls().__call__(original, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 172, in __call__
      return self._patch_implementation(original, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 230, in _patch_implementation
      result = super()._patch_implementation(original, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/tensorflow/__init__.py", line 1268, in _patch_implementation
      history = original(inst, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 533, in call_original
      return call_original_fn_with_event_logging(_original_fn, og_args, og_kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 468, in call_original_fn_with_event_logging
      original_fn_result = original_fn(*og_args, **og_kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/mlflow/utils/autologging_utils/safety.py", line 530, in _original_fn
      original_result = original(*_og_args, **_og_kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 480, in train_step
      total_loss, reconstruction_loss, kl_loss = self._compute_losses(data)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 457, in _compute_losses
      [z,z_mean,z_log_var] = self(data)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 569, in __call__
      return super().__call__(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/cellularimagingvae/vae.py", line 447, in call
      z, z_mean, z_log_var = self.encoder(imgs) #Encode and sample
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/training.py", line 569, in __call__
      return super().__call__(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/functional.py", line 512, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/functional.py", line 669, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py", line 290, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "/nfs_home/users/aezw/.conda/envs/VAE_dev2/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py", line 262, in convolution_op
      return tf.nn.convolution(
Node: 'encoder/conv4_block16_1_conv/Conv2D'
OOM when allocating tensor with shape[12,67,67,128] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node encoder/conv4_block16_1_conv/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_105301]
```

### Steps to reproduce

Hard to reproduce because it's running on a 4xV100 AWS node, and reproducing this in any case requires a GPU.

### Additional context (optional)

Most relevant part of the traceback copied in issue, full error log attached. Running from "train" downwards produces no issue. Running on AWS 4xV100 node. 

[error_log.log](https://github.com/optuna/optuna/files/12646693/error_log.log)

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by azagajewski** [comment]
@nzw0301 I made a minimal reproducible example in colab, which takes the CIFAR-100 and a small CNN, trains it first outside optuna nicely, and then has optuna call the same training function as part of the objective, leading to an OOM error when allocating tensors to the GPU. If you run it on the free T4 GPU runtime it should reproduce nicely.

https://colab.research.google.com/drive/11HU5H_R3skwkx5sgRrRkpS4yrO7ad7yi?usp=sharing

**Comment by nzw0301** [comment]
Thanks. This is not Optuna's bug. https://stackoverflow.com/questions/51005147/keras-release-memory-after-finish-training-process/52354943#52354943 would be a solution.
