### ISSUE TITLE
running optuna sometimes results in sql3lite.OperationError, database is locked

### ISSUE THREAD

**Issue by dyhan316** [optuna/optuna#4994]
### Expected behavior

Sometimes (not always) while running optuna, I get an error. 

This did not occur in another server, so I believe this might be an environment problem? (I don't know much about sql, is there anything I can do to analyze more about this situation?) 

### Environment

- Optuna version: optuna                    3.3.0                    pypi_0    pypi
- Python version: python                    3.10.4               h12debd9_0 
- OS: Linux (?)
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Initially, it gives me the following error (but still runs the training)

===training==== 
 16 Training epoch : 0: 100%|██████████| 159/159 [02:36<00:00,  1.01it/s] 
 17 ===validation==== 
 18 Validation Epoch : 0:   0%|          | 0/17 [00:00<?, ?it/s]Exception in thread Thread-1 (_record_heartbeat): 
 19 Traceback (most recent call last): 
 20   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context 
 21     self.dialect.do_execute( 
 22   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute 
 23     cursor.execute(statement, parameters) 
 24 sqlite3.OperationalError: database is locked 
 25 The above exception was the direct cause of the following exception: 
 26 Traceback (most recent call last): 
 27   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session 
 28     session.commit() 
 29   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1923, in commit 
 30     trans.commit(_to_root=True) 
 31   File "<string>", line 2, in commit 
 32   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go 
 33     ret_value = fn(self, *arg, **kw) 
 34   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1239, in commit 
 35     self._prepare_impl() 
 36   File "<string>", line 2, in _prepare_impl 
 37   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go 
 38     ret_value = fn(self, *arg, **kw) 
 39   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl 
 40     self.session.flush() 
 41   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4179, in flush 
 42     self._flush(objects) 
 43   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4314, in _flush 
 44     with util.safe_reraise(): 
 45   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__ 
 46     raise exc_value.with_traceback(exc_tb) 
 47   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush 
 48     flush_context.execute() 
 49   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute 
 50     rec.execute(self) 
 51   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute 
 52     util.preloaded.orm_persistence.save_obj( 
 53   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj 
 54     _emit_update_statements( 
 55   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements 
 56     c = connection.execute( 
 57   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute 
 58     return meth( 
 59   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection 
 60     return connection._execute_clauseelement( 
 61   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement 
 62     ret = self._execute_context( 
 63   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context 
 64     return self._exec_single_context( 
 65   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context 
 66     self._handle_dbapi_exception( 
 67   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception 
 68     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e 
 69   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context 
 70     self.dialect.do_execute( 
 71   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute 
 72     cursor.execute(statement, parameters) 
 73 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked 
 74 [SQL: UPDATE trial_heartbeats SET heartbeat=? WHERE trial_heartbeats.trial_heartbeat_id = ?] 
 75 [parameters: ('2023-10-03 06:30:50.000000', 1)] 
 76 (Background on this error at: https://sqlalche.me/e/20/e3q8) 
 77 The above exception was the direct cause of the following exception: 
 78 Traceback (most recent call last): 
 79   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/threading.py", line 1009, in _bootstrap_inner 
 80     self.run() 
 81   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/threading.py", line 946, in run 
 82     self._target(*self._args, **self._kwargs) 
 83   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_heartbeat.py", line 131, in _record_heartbeat 
 84     heartbeat.record_heartbeat(trial_id) 
 85   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_cached_storage.py", line 262, in record_heartbeat 
 86     self._backend.record_heartbeat(trial_id) 
 87   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 974, in record_heartbeat 
 88     with _create_scoped_session(self.scoped_session, True) as session: 
 89   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/contextlib.py", line 142, in __exit__ 
 90     next(self.gen) 
 91   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 90, in _create_scoped_session 
 92     raise optuna.exceptions.StorageInternalError(message) from e 
 93 optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
 94 Validation Epoch : 0: 100%|██████████| 17/17 [00:19<00:00,  1.15s/it] 
 95 Epoch [1/300] Training loss = 9.7080  Validation loss = 9.6877  lr = 0.0001  time = 176.1613 
 96 ========= 
 97 training_loss :  9.70797349873533 
 98 ===training==== 
 99 Training epoch : 1: 100%|██████████| 159/159 [02:24<00:00,  1.10it/s] 
100 ===validation==== 
101 Validation Epoch : 1: 100%|██████████| 17/17 [00:11<00:00,  1.43it/s] 
102 Epoch [2/300] Training loss = 9.6878  Validation loss = 9.6879  lr = 0.0001  time = 333.0040 
103 ========= 
104 training_loss :  9.687833375356885 
105 EarlyStopping counter: 1 out of 30 
106 ===training==== 
107 Training epoch : 2: 100%|██████████| 159/159 [02:21<00:00,  1.12it/s] 
108 ===validation==== 
109 Validation Epoch : 2: 100%|████████
```

Then, it throws the following error after some epochs are done
```
===validation==== 
318 Validation Epoch : 11:  35%|███▌      | 6/17 [00:03<00:06,  1.74it/s]] 
319 Validation Epoch : 11:  59%|█████▉    | 10/17 [00:05<00:03,  1.77it/s] 
320 Validation Epoch : 11:  76%|███████▋  | 13/17 [00:07<00:02,  1.69it/s] 
321 Validation Epoch : 11:  94%|█████████▍| 16/17 [00:09<00:00,  1.69it/s] 
322 ValueError: Cannot tell a FAIL trial.{frozen_trial.state.name} trial.")ages/optuna/study/_tell.py", line 115, in _tell_with_warningentialbleediate_value_without_commitalready finished and can not be updated.'). 
323 Epoch [12/300] Training loss = 9.4615  Validation loss = 9.4458  lr = 0.0001  time = 1886.7891 
324 ========= 
325 Trial 0 failed with parameters: {'learning_rate': 0.0001, 'weight_decay': 5e-05} because of the following error: RuntimeError('Trial#0 has already finished and can not be updated.'). 
326 Traceback (most recent call last): 
327   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial 
328     value_or_values = func(trial) 
329   File "/home01/x2519a02/copy_from_SDCC/VAE_ADHD/yAwareContrastiveLearning/main_multilabel_DALI_optuna.py", line 314, in objective 
330     model.pretraining_yaware() 
331   File "/home01/x2519a02/copy_from_SDCC/VAE_ADHD/yAwareContrastiveLearning/yAwareContrastiveLearning_multilabel_DALI_optuna.py", line 311, in pretraining_yaware 
332     self.trial.report(val_loss, epoch) #undo if trial is not needed 
333   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/trial/_trial.py", line 501, in report 
334     self.storage.set_trial_intermediate_value(self._trial_id, step, value) 
335   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_cached_storage.py", line 192, in set_trial_intermediate_value 
336     self._backend.set_trial_intermediate_value(trial_id, step, intermediate_value) 
337   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 683, in set_trial_intermediate_value 
338     self._set_trial_intermediate_value_without_commit( 
339   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 695, in _set_trial_intermediate_value_without_commit 
340     self.check_trial_is_updatable(trial_id, trial.state) 
341   File "/scratch/x2519a02/.conda/envs/CL_MRI_2/lib/python3.10/site-packages/optuna/storages/_base.py", line 626, in check_trial_is_updatable 
342     raise RuntimeError( 
343 RuntimeError: Trial#0 has already finished and can not be updated. 
344 Trial 0 failed with value None. 
345 ValueError: Cannot tell a FAIL trial.{frozen_trial.state.name} trial.")ages/optuna/study/_tell.py", line 115, in _tell_with_warningentialbleediate_value_without_commitalready finished and can not be updated.').
```
(the optuna values are not logged (intermediate values are not saved to the db))
```


### Steps to reproduce

I believe that this problem is not related to the code itself as it worked on another server. But if requested I will try to find a way to reproduce it! (I don't know much about sql.. sorry)

### Additional context (optional)

_No response_

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us? I think this is not supposed to be a bug according to the error message.

**Comment by c-bata** [comment]
As @nzw0301 shared the FAQ, SQLite3 does not support a high level of concurrency. Please increase the timeout value (Note that you cannot avoid this error since SQLite3 does not provide infinite blocking).
