### ISSUE TITLE
BruteForceSampler fails to resume study when run fails

### ISSUE THREAD

**Issue by liukidar** [optuna/optuna#5097]
### Expected behavior

When running a study using BruteForceSampler, if any run fails (for example for out of memory errors) and the study is interrupted before completion of all the possible trials, we should be able to start the study again and resume from where we stopped (by simpling starting the program again).

### Environment

- Optuna version:3.4.0
- Python version:3.11.4
- OS:Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.17
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
[I 2023-11-07 09:09:52,541] A new study created in memory with name: no-name-67f1e9f8-0564-4b63-8b9d-515b5887aaff
Using parameters: {'x': 'a', 'y': 1}
[I 2023-11-07 09:09:52,543] Trial 0 finished with value: 98.0 and parameters: {'x': 'a', 'y': 1}. Best is trial 0 with value: 98.0.
Using parameters: {'x': 'a', 'y': 2}
[I 2023-11-07 09:09:52,566] Trial 1 finished with value: 99.0 and parameters: {'x': 'a', 'y': 2}. Best is trial 0 with value: 98.0.
Using parameters: {'x': 'a', 'y': 7}
[I 2023-11-07 09:09:52,579] Trial 2 finished with value: 104.0 and parameters: {'x': 'a', 'y': 7}. Best is trial 0 with value: 98.0.
Using parameters: {'x': 'a', 'y': 9}
[I 2023-11-07 09:09:52,592] Trial 3 finished with value: 106.0 and parameters: {'x': 'a', 'y': 9}. Best is trial 0 with value: 98.0.
Using parameters: {'x': 'c'}
[I 2023-11-07 09:09:52,604] Trial 4 finished with value: 109.0 and parameters: {'x': 'c'}. Best is trial 0 with value: 98.0.
Using parameters: {'x': 'a', 'y': 6}
[I 2023-11-07 09:09:52,617] Trial 5 finished with value: 103.0 and parameters: {'x': 'a', 'y': 6}. Best is trial 0 with value: 98.0.
[W 2023-11-07 09:09:52,628] Trial 6 failed with parameters: {} because of the following error: FileNotFoundError().
Traceback (most recent call last):
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/home/projects/pc-optimization/optuna_test.py", line 6, in objective_that_fails
    raise FileNotFoundError()
FileNotFoundError
[W 2023-11-07 09:09:52,630] Trial 6 failed with value None.
param_name mismatch: x != None. Children: {0: _TreeNode(param_name='y', children={0: _TreeNode(param_name=None, children=None), 1: _TreeNode(param_name=None, children={}), 2: _TreeNode(param_name=None, children={}), 3: _TreeNode(param_name=None, children=None), 4: _TreeNode(param_name=None, children=None), 5: _TreeNode(param_name=None, children=None), 6: _TreeNode(param_name=None, children={}), 7: _TreeNode(param_name=None, children={}), 8: _TreeNode(param_name=None, children=None), 9: _TreeNode(param_name=None, children={})}), 1: _TreeNode(param_name=None, children=None), 2: _TreeNode(param_name=None, children={})}


Trying second optimization:


[W 2023-11-07 09:09:52,642] Trial 7 failed with parameters: {} because of the following error: ValueError("param_name mismatch: x != None. Children: {0: _TreeNode(param_name='y', children={0: _TreeNode(param_name=None, children=None), 1: _TreeNode(param_name=None, children={}), 2: _TreeNode(param_name=None, children={}), 3: _TreeNode(param_name=None, children=None), 4: _TreeNode(param_name=None, children=None), 5: _TreeNode(param_name=None, children=None), 6: _TreeNode(param_name=None, children={}), 7: _TreeNode(param_name=None, children={}), 8: _TreeNode(param_name=None, children=None), 9: _TreeNode(param_name=None, children={})}), 1: _TreeNode(param_name=None, children=None), 2: _TreeNode(param_name=None, children={})}").
Traceback (most recent call last):
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/home/projects/pc-optimization/optuna_test.py", line 19, in objective_that_cant_fail
    x = trial.suggest_categorical('x', ['a', 'b', 'c'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/trial/_trial.py", line 405, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/trial/_trial.py", line 630, in _suggest
    param_value = self.study.sampler.sample_independent(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 203, in sample_independent
    self._populate_tree(tree, (t for t in trials if t.number != trial.number), trial.params)
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 172, in _populate_tree
    leaf.set_leaf()
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 54, in set_leaf
    self.expand(None, [])
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 47, in expand
    raise ValueError(f"param_name mismatch: {self.param_name} != {param_name}. Children: {self.children}")
ValueError: param_name mismatch: x != None. Children: {0: _TreeNode(param_name='y', children={0: _TreeNode(param_name=None, children=None), 1: _TreeNode(param_name=None, children={}), 2: _TreeNode(param_name=None, children={}), 3: _TreeNode(param_name=None, children=None), 4: _TreeNode(param_name=None, children=None), 5: _TreeNode(param_name=None, children=None), 6: _TreeNode(param_name=None, children={}), 7: _TreeNode(param_name=None, children={}), 8: _TreeNode(param_name=None, children=None), 9: _TreeNode(param_name=None, children={})}), 1: _TreeNode(param_name=None, children=None), 2: _TreeNode(param_name=None, children={})}
[W 2023-11-07 09:09:52,644] Trial 7 failed with value None.
Traceback (most recent call last):
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/home/projects/pc-optimization/optuna_test.py", line 37, in <module>
    study.optimize(objective_that_cant_fail, n_trials=100, n_jobs=1, gc_after_trial=True)
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_optimize.py", line 212, in _run_trial
    frozen_trial = _tell_with_warning(
                   ^^^^^^^^^^^^^^^^^^^
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/study/_tell.py", line 174, in _tell_with_warning
    study.sampler.after_trial(study, frozen_trial, state, values)
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 226, in after_trial
    self._populate_tree(
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 172, in _populate_tree
    leaf.set_leaf()
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 54, in set_leaf
    self.expand(None, [])
  File "/jmain02/home/J2AD009/ttl04/lxp14-ttl04/.conda/envs/pcax/lib/python3.11/site-packages/optuna/samplers/_brute_force.py", line 47, in expand
    raise ValueError(f"param_name mismatch: {self.param_name} != {param_name}. Children: {self.children}")
ValueError: param_name mismatch: x != None. Children: {0: _TreeNode(param_name='y', children={0: _TreeNode(param_name=None, children=None), 1: _TreeNode(param_name=None, children={}), 2: _TreeNode(param_name=None, children={}), 3: _TreeNode(param_name=None, children=None), 4: _TreeNode(param_name=None, children=None), 5: _TreeNode(param_name=None, children=None), 6: _TreeNode(param_name=None, children={}), 7: _TreeNode(param_name=None, children={}), 8: _TreeNode(param_name=None, children=None), 9: _TreeNode(param_name=None, children={})}), 1: _TreeNode(param_name=None, children=None), 2: _TreeNode(param_name=None, children={})}
```

### Steps to reproduce

1. Run a study using BruteForceSampler
2. Interrupt the study after a run has failed
3. Try to resume the study. The study will crash when the sampler tries to create the trials tree

```python
import optuna
import random

def objective_that_fails(trial: optuna.Trial):
    if random.randint(0, 5) == 0:
        raise FileNotFoundError()
    
    x = trial.suggest_categorical('x', ['a', 'b', 'c'])
    if x == 'a':
        y = trial.suggest_int('y', 0, 9)
    else:
        y = 10
    
    print("Using parameters:", trial.params)
    
    return ord(x) + y / 100.0

def objective_that_cant_fail(trial: optuna.Trial):
    x = trial.suggest_categorical('x', ['a', 'b', 'c'])
    if x == 'a':
        y = trial.suggest_int('y', 0, 9)
    else:
        y = 10
    
    print("Using parameters:", trial.params)
    
    return ord(x) + y / 100.0

if __name__ == '__main__':
    study = optuna.create_study(sampler=optuna.samplers.BruteForceSampler())
    try:
        study.optimize(objective_that_fails, n_trials=100, n_jobs=1, gc_after_trial=True)
    except Exception as e:
        print(e)

    print("\n\nTrying second optimization:\n\n")
    study.optimize(objective_that_cant_fail, n_trials=100, n_jobs=1, gc_after_trial=True)
    
    print(study.best_params)
    print(study.best_value)
    print(study.best_trial)
```
The above code results in the before mentioned error: as soon as you sample a 0 the first optimization crashes and you cannot resume it.

### Additional context (optional)

- In the log I also print the children of the node that caused the error, not sure if this is helpful;
- the trial crashed because of oom error and wasn't able to sample any parameter I think (if I try to print the trial parameters via study.get_trials i get {})

**Comment by nzw0301** [comment]
Thank you for reporting the bug. If possible, could you share the minimal reproducible code block with us for smooth investigation?

**Comment by liukidar** [comment]
> Thank you for reporting the bug. If possible, could you share the minimal reproducible code block with us for smooth investigation?

Yes, I will edit this post with the code (as soon as I manage to reproduce it on a small scale). I actually have an update, so I'm not sure if i should edit the main post or not. It seems that the bruteforce sampler crashes immediately after a run fails, not when you resume the study. It's is quite difficult to tell as I'm running ~100 studies in parallel, but it seems that one failed for OOM and caused all the other processes to start failing because of the bruteforce sampler error.

**Comment by liamd101** [comment]
Hi! I'm also running in to the exact same issue with the BruteForceSampler. Commenting out the lines you mentioned (which are now [193](https://github.com/optuna/optuna/blob/1925ca1a051b3bf11819478b65d830de614774b2/optuna/samplers/_brute_force.py#L193) and [221](https://github.com/optuna/optuna/blob/1925ca1a051b3bf11819478b65d830de614774b2/optuna/samplers/_brute_force.py#L221) in `samplers/_brute_force.py`) did fix the issue; however, this feels like a hacky workaround
