### ISSUE TITLE
(sqlite3.DatabaseError) database disk image is malformed

### ISSUE THREAD

**Issue by kirilllzaitsev** [optuna/optuna#5385]
### Expected behavior

This is the error I started getting recently with no changes to the optuna-related logic:
```
[I 2024-04-05 13:15:50,120] A new study created in RDB with name: 2024-04-05_13-15-42_opt_f1
[I 2024-04-05 13:15:53,308] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
[I 2024-04-05 13:15:56,245] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
[I 2024-04-05 13:15:58,303] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session
    yield session
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 778, in get_trial
    frozen_trial = self._build_frozen_trial_from_trial_model(trial_model)
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 872, in _build_frozen_trial_from_trial_model
    params = sorted(trial.params, key=lambda p: p.param_id)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 967, in _load_for_state
    return self._emit_lazyload(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1130, in _emit_lazyload
    result = session.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT trial_params.param_id AS trial_params_param_id, trial_params.trial_id AS trial_params_trial_id, trial_params.param_name AS trial_params_param_name, trial_params.param_value AS trial_params_param_value, trial_params.distribution_json AS trial_params_distribution_json 
FROM trial_params 
WHERE ? = trial_params.trial_id]
[parameters: (54,)]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```
`optuna_studies.db` is the corresponding DB file which stays at 0 Kb.

Previous [issue](https://github.com/optuna/optuna/issues/815) discussed the problem in the context of NFS. I'm wondering if there are generic troubleshooting steps for this DB-related error, as I'm not aware of any NFS-related hardware changes.

### Environment

- Optuna version:3.5.0
- Python version:3.10.13
- OS:Linux-5.15.0-101-generic-x86_64-with-glibc2.31

### Error messages, stack traces, or logs

```shell
[I 2024-04-05 13:15:50,120] A new study created in RDB with name: 2024-04-05_13-15-42_opt_f1
[I 2024-04-05 13:15:53,308] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
[I 2024-04-05 13:15:56,245] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
[I 2024-04-05 13:15:58,303] Using an existing study with name '2024-04-05_13-15-42_opt_f1' instead of creating a new one.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session
    yield session
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 778, in get_trial
    frozen_trial = self._build_frozen_trial_from_trial_model(trial_model)
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 872, in _build_frozen_trial_from_trial_model
    params = sorted(trial.params, key=lambda p: p.param_id)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 967, in _load_for_state
    return self._emit_lazyload(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1130, in _emit_lazyload
    result = session.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT trial_params.param_id AS trial_params_param_id, trial_params.trial_id AS trial_params_trial_id, trial_params.param_name AS trial_params_param_name, trial_params.param_value AS trial_params_param_value, trial_params.distribution_json AS trial_params_distribution_json 
FROM trial_params 
WHERE ? = trial_params.trial_id]
[parameters: (54,)]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```
```


### Steps to reproduce

The same code that worked previously is now producing the error.

### Additional context (optional)

_No response_

**Comment by nzw0301** [comment]
Could you share the minimal reproducible code? Can you explain why the your code loads the database three times?

**Comment by kirilllzaitsev** [comment]
@nzw0301 here are the outlines of some key components:
```
def run_study():
    now = dt.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    study_name = f"{now}_{args.opt_study_prefix}_{args.opt_target_metrics}"
    pool_args = [(args, run_pipe, study_name) for _ in range(args.opt_n_jobs)]
    with mp.Pool(args.opt_n_jobs) as pool:
        results = pool.starmap(_run_study, pool_args)

    study = optuna.load_study(study_name=study_name, storage=args.opt_storage)

    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

def _run_study():
    study = optuna.create_study(
        direction=direction,
        pruner=pruner,
        study_name=study_name,
        storage=args.opt_storage,
        load_if_exists=True,
    )
    objective = functools.partial(optuna_objective, args=args, run_pipe=run_pipe)
    study.optimize(objective, n_trials=args.opt_n_trials, timeout=None)
```
The database is loaded simultaneously from several parallel processes

**Comment by nzw0301** [comment]
Can you try to create a database only single process or thread first rather than create simultaneously?

**Comment by kirilllzaitsev** [comment]
@nzw0301 yes, I put the `create_study` in front and here is the log:
```
[I 2024-04-07 08:23:56,860] A new study created in RDB with name: 2024-04-07_08-23-56_opt_f1
Overriding hyperparameters with group: v12_64_opt
Overriding centroid_weight with 0.35
Overriding occupancy_threshold with 0.6
Overriding pos_weight with 5.5
Overriding start_mae_from_n_epoch with 0
Overriding lr with 0.001
Overriding lr_decay with 0.998
[I 2024-04-07 08:24:26,352] Using an existing study with name '2024-04-07_08-23-56_opt_f1' instead of creating a new one.
[I 2024-04-07 08:24:26,394] Using an existing study with name '2024-04-07_08-23-56_opt_f1' instead of creating a new one.
[I 2024-04-07 08:24:26,468] Using an existing study with name '2024-04-07_08-23-56_opt_f1' instead of creating a new one.
[I 2024-04-07 08:24:26,516] Using an existing study with name '2024-04-07_08-23-56_opt_f1' instead of creating a new one.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 73, in _create_scoped_session
    yield session
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 778, in get_trial
    frozen_trial = self._build_frozen_trial_from_trial_model(trial_model)
  File "/opt/miniconda3/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 872, in _build_frozen_trial_from_trial_model
    params = sorted(trial.params, key=lambda p: p.param_id)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1121, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 967, in _load_for_state
    return self._emit_lazyload(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1130, in _emit_lazyload
    result = session.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/miniconda3/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT trial_params.param_id AS trial_params_param_id, trial_params.trial_id AS trial_params_trial_id, trial_params.param_name AS trial_params_param_name, trial_params.param_value AS trial_params_param_value, trial_params.distribution_json AS trial_params_distribution_json 
FROM trial_params 
WHERE ? = trial_params.trial_id]
[parameters: (54,)]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
```

**Comment by nzw0301** [comment]
Thanks. https://stackoverflow.com/questions/30596633/multiple-threads-and-sqlite-database-disk-image-is-malformed looks similar. Indeed, As noted in https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html, sqlite storage with parallel execution is not ideal setting. Can you use MySQL or another storage?

**Comment by kirilllzaitsev** [comment]
I could set up another storage. The question of how it worked before under the same environment remains a mystery. Maybe some hardware maintenance I am not aware of updated some sqlite-related packages

**Comment by nzw0301** [comment]
Maybe at least not related to optuna I suppose.
