### ISSUE TITLE
from optuna.integration.xgboost import XGBoostPruningCallback  error ModuleNotFoundError: No module named 'optuna_integration'

### ISSUE THREAD

**Issue by ammoniaca** [optuna/optuna#5429]
### Expected behavior

I am following the textbook examples. I installed Optuna ver. 3.6.1 and xgboost ver 2.0.3 in Python 3.10. 

When I try to load the following form I always get the following error :

from optuna.integration.xgboost import XGBoostPruningCallback

--------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Alessandro\PycharmProjects\optunaXgboosErrorTest\main.py", line 1, in <module>
    from optuna.integration.xgboost import XGBoostPruningCallback
  File "C:\Users\Alessandro\PycharmProjects\optunaXgboosErrorTest\venv\lib\site-packages\optuna\integration\xgboost.py", line 1, in <module>
    from optuna_integration.xgboost import XGBoostPruningCallback
ModuleNotFoundError: No module named 'optuna_integration'

### Environment

- Optuna version: 3.6.1
- Python version: Python 3.10
- OS: Wndows 11
- (Optional) Other libraries and their versions:  xgboost ver 2.0.3

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Alessandro\PycharmProjects\optunaOptimization\venv\lib\site-packages\optuna\integration\xgboost.py", line 1, in <module>
    from optuna_integration.xgboost import XGBoostPruningCallback
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'optuna_integration'
```

### Steps to reproduce

1. from optuna.integration.xgboost import XGBoostPruningCallback (just one line in main.py)
2.
3.
```python
# python code
```

**Comment by ammoniaca** [comment]
solution: install 

pip install optuna-integration

**Comment by nzw0301** [comment]
So this is not a bug. This is expected behaviour from optuna 3.6.
