### ISSUE TITLE
Cannot build the document on Mac

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#5463]
## Problem
I cannot build the document on my MacBook, and my colleagues also cannot. It might be the problem due to the dependencies, but I have no exact idea how to fix this. Concretely, the build stops at the execution of `optuna.visualization.matplotlib.plot_terminator_improvement`.

## What should be done
 The following command should be finished without any errors.
```bash
cd docs
make html
```

## Environment
Chip: Apple M2
OS: Sonoma 14.4.1
Python: 3.9.6
Optuna: current master https://github.com/optuna/optuna/commit/98d44447cb557a7654ea92f5ea94059c2d2fc2b1
Sphinx : 7.3.7

## Log

```
(venv) mamu@hideakis-mbp docs % make html
Running Sphinx v7.3.7
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
[autosummary] generating autosummary for: faq.rst, index.rst, installation.rst, license_thirdparty.rst, privacy.rst, reference/artifacts.rst, reference/cli.rst, reference/distributions.rst, reference/exceptions.rst, reference/generated/optuna.TrialPruned.rst, ..., tutorial/20_recipes/007_optuna_callback.rst, tutorial/20_recipes/008_specify_params.rst, tutorial/20_recipes/009_ask_and_tell.rst, tutorial/20_recipes/010_reuse_best_trial.rst, tutorial/20_recipes/011_journal_storage.rst, tutorial/20_recipes/012_artifact_tutorial.rst, tutorial/20_recipes/013_wilcoxon_pruner.rst, tutorial/20_recipes/index.rst, tutorial/20_recipes/sg_execution_times.rst, tutorial/index.rst
... (omitted)
[I 2024-05-28 15:49:13,556] Trial 29 finished with value: 0.3988888888888889 and parameters: {'reg_alpha': 3.678682178991996, 'reg_lambda': 0.3774170267659814, 'num_leaves': 149, 'colsample_bytree': 0.41211293837374274, 'subsample': 0.6490900435795488, 'subsample_freq': 7, 'min_child_samples': 70}. Best is trial 27 with value: 0.3314285714285714.
<string>:27: ExperimentalWarning:

plot_terminator_improvement is experimental (supported from v3.2.0). The interface can change in the future.

/Users/mamu/Work-and-Study/optuna/optuna/visualization/_terminator_improvement.py:131: ExperimentalWarning:

RegretBoundEvaluator is experimental (supported from v3.2.0). The interface can change in the future.

/Users/mamu/Work-and-Study/optuna/optuna/visualization/_terminator_improvement.py:136: ExperimentalWarning:

CrossValidationErrorEvaluator is experimental (supported from v3.2.0). The interface can change in the future.

  0%|                                                                                     | 0/30 [00:00<?, ?it/s]make: *** [html] Segmentation fault: 11
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by HideakiImamura** [comment]
@gen740 tells me that if we call `make clean`, then the build hangs.

**Comment by gen740** [comment]
It seems that this issue has been unexpectedly resolved due to the changes in #5545.

**Comment by nzw0301** [comment]
I cannot also build the document on Mac.

The warning message are as follows:

```
...
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] reference/samplers/generated/optuna.samplers.intersection_search_space
WARNING: autodoc: failed to import class 'IntersectionSearchSpace' from module 'optuna.samplers'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 397, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'optuna.samplers' has no attribute 'IntersectionSearchSpace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 207, in import_object
    obj = attrgetter(obj, mangled_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 343, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 2835, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 413, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: IntersectionSearchSpace
 [autodoc.import_object]
WARNING: autodoc: failed to import function 'intersection_search_space' from module 'optuna.samplers'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 397, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'optuna.samplers' has no attribute 'intersection_search_space'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 207, in import_object
    obj = attrgetter(obj, mangled_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 343, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 2835, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/optuna-312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 413, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: intersection_search_space
 [autodoc.import_object]
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/nzw0301/Documents/oss/optuna/docs/source/reference/samplers/generated/optuna.samplers.IntersectionSearchSpace.rst: WARNING: document isn't included in any toctree
/Users/nzw0301/Documents/oss/optuna/docs/source/reference/samplers/generated/optuna.samplers.intersection_search_space.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
copying assets...
```



- python: 3.12.0
- Optuna: https://github.com/optuna/optuna/commit/a5d9e9650ddaffe5c29331cc6a023895656870e6
- Mac: M3 MBP
- OS: Sonoma 14.6.1


Docs related dependencies:

```
 pip list | grep -i sphi
Sphinx                             8.1.3
sphinx-copybutton                  0.5.2
sphinx-gallery                     0.18.0
sphinx-plotly-directive            0.1.3
sphinx-rtd-theme                   3.0.1
sphinxcontrib-applehelp            1.0.8
sphinxcontrib-devhelp              1.0.6
sphinxcontrib-htmlhelp             2.1.0
sphinxcontrib-jquery               4.1
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.7
sphinxcontrib-serializinghtml      1.1.10
```

**Comment by nzw0301** [comment]
I realised that `make clean` does not remove `docs/source/reference/samplers/generated`. I'll send a pull request.
