### ISSUE TITLE
Parallelization with Postgresql

### ISSUE THREAD

**Issue by jvrodrisan** [optuna/optuna#5582]
### Expected behavior

When using PostgreSQL as the RDBS storage, under a study in which I run 15 executions on parallel, from time to time an execution fails with the following error 
```python
RuntimeError('Trial#4582 has already finished and can not be updated.').
``` 

### Environment

- Optuna version: 3.6.1
- Python version: 3.12.3
- OS:macOS-14.5-x86_64-i386-64bit

### Error messages, stack traces, or logs

```shell
[W 2024-07-15 07:21:29,321] Trial 4582 failed with parameters: {} because of the following error: RuntimeError('Trial#4582 has already finished and can not be updated.').
Traceback (most recent call last):
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/Users/jyck/workspace/algo-trading/vectorbt/main_optimizer_cryptos_v4_flash_trades_long_short_slcash_support_safeTrades_checkpastWF_oldtls_MultiTF_light.py", line 1404, in run_strategy
    asset_parameters[i]= trial.suggest_int(i, _params_yaml[i][0], _params_yaml[i][1], step=_params_yaml[i][2])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/trial/_trial.py", line 326, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/trial/_trial.py", line 625, in _suggest
    elif self._is_relative_param(name, distribution):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/trial/_trial.py", line 657, in _is_relative_param
    if name not in self.relative_params:
                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/trial/_trial.py", line 73, in relative_params
    self._relative_params = self.study.sampler.sample_relative(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/samplers/nsgaii/_sampler.py", line 257, in sample_relative
    study._storage.set_trial_system_attr(trial._trial_id, _GENERATION_KEY, generation)
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/storages/_cached_storage.py", line 198, in set_trial_system_attr
    self._backend.set_trial_system_attr(trial_id, key=key, value=value)
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/storages/_rdb/storage.py", line 739, in set_trial_system_attr
    self._set_trial_system_attr_without_commit(session, trial_id, key, value)
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/storages/_rdb/storage.py", line 745, in _set_trial_system_attr_without_commit
    self.check_trial_is_updatable(trial_id, trial.state)
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/storages/_base.py", line 626, in check_trial_is_updatable
    raise RuntimeError(
RuntimeError: Trial#4582 has already finished and can not be updated.
[W 2024-07-15 07:21:29,324] Trial 4582 failed with value None.
Traceback (most recent call last):
  File "/Users/jyck/workspace/algo-trading/vectorbt/main_optimizer_cryptos_v4_flash_trades_long_short_slcash_support_safeTrades_checkpastWF_oldtls_MultiTF_light.py", line 2281, in <module>
    hyp_opt.run_optimizer()
  File "/Users/jyck/workspace/algo-trading/vectorbt/main_optimizer_cryptos_v4_flash_trades_long_short_slcash_support_safeTrades_checkpastWF_oldtls_MultiTF_light.py", line 2105, in run_optimizer
    study.optimize(self.run_strategy, gc_after_trial=True,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/_optimize.py", line 208, in _run_trial
    frozen_trial = _tell_with_warning(
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/jyck/.pyenv/versions/anaconda3-2023.03/envs/py312/lib/python3.12/site-packages/optuna/study/_tell.py", line 115, in _tell_with_warning
    raise ValueError(f"Cannot tell a {frozen_trial.state.name} trial.")
ValueError: Cannot tell a FAIL trial.
```

### Steps to reproduce

Run any study with high level of transactions and running parallel executions (15) under PostgreSQL (v.16)

### Additional context (optional)

I had to switch from mariaDB to PostgreSQL as every time the computer crashes under workload or for any reason, MariaDB optuna db gets corrupted. MariaDB works ok for parallel jobs, however for postgresql it seems this level of concurrency (15 threads or different executions) is too much and I get the above error. I tried to change the isolation level and increase the deadlock timeout to 2s from 1s, but I get the same result. Is there any recommended config for postgresql for this scenario?

**Comment by not522** [comment]
Thank you for the bug report. We are aware of a similar error with the heartbeat feature (#5470). Could you let us know if you are using heartbeat in your case?

**Comment by jvrodrisan** [comment]
Hi, thanks for the reply. Yes, I am using heartbeat in my case too, I have not tried to modify the value, but right now the interval is set to 60 as per some examples in the documentation.

**Comment by not522** [comment]
We have recently made a fix that reduces the occurrence of this problem (#5431), so it may be resolved in the latest release. Could you try `optuna==4.0.0b0`?

**Comment by jvrodrisan** [comment]
Sure, I have switched to the 4.0.0b0 branch and will report back if I find this issue again during the current study.

**Comment by jvrodrisan** [comment]
Morning, since I switched to the 4.0.0b0 the issue has not occurred again, from my side it seems it is working fine now and this issue can be closed. Should appear again, I will report it back, thanks for all your help!!!

**Comment by not522** [comment]
Thank you!
Let me close this issue. If the problem reoccurs, please feel free to reopen it.
