### ISSUE TITLE
Postgres connection drops after ~one hour of inactivity

### ISSUE THREAD

**Issue by ziadloo** [optuna/optuna#5600]
### Expected behavior

The connection should be kept alive no matter how long it's been inactive. Or, there must be a retry mechanism implemented.

### Environment

- Optuna version: 3.6.1
- Python version: 3.10.13
- OS: Linux-6.6.40-1-MANJARO-x86_64-with-glibc2.39
- psycopg2: Version: 2.9.9
- PostgreSQL 16.3

### Error messages, stack traces, or logs

```shell
INFO:root:Timing Info: ds_fetch : 14.60ms, model_fwd : 36.66ms, crit_fwd : 0.45ms, bwd : 1.29ms, optim : 0.29ms, metrics : 1.24ms, train_total : 21081.21ms, test_total : 1672.35ms
Traceback (most recent call last):
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 72, in _create_scoped_session
    yield session
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 776, in get_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_rdb/models.py", line 254, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2754, in one_or_none
    return self._iter().one_or_none()  # type: ignore
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = %(trial_id_1)s]
[parameters: {'trial_id_1': 843}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_optimize.py", line 208, in _run_trial
    frozen_trial = _tell_with_warning(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_tell.py", line 106, in _tell_with_warning
    frozen_trial = _get_frozen_trial(study, trial)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_tell.py", line 40, in _get_frozen_trial
    return study._storage.get_trial(trial_id)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_cached_storage.py", line 213, in get_trial
    return self._backend.get_trial(trial_id)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 775, in get_trial
    with _create_scoped_session(self.scoped_session) as session:
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 90, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mehran/Documents/GitHub/gtn_applications/./search_upstream.py", line 276, in <module>
    search()
  File "/home/mehran/Documents/GitHub/gtn_applications/./search_upstream.py", line 259, in search
    study.optimize(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/mehran/.conda/envs/pytorch/lib/python3.10/site-packages/optuna/study/_optimize.py", line 240, in _run_trial
    assert False, "Should not reach."
AssertionError: Should not reach.
```

### Steps to reproduce

1. Create a python file with the following code and a `.env` file with Postgres credentials in it.
2. Run the code
3. Be patient (it's set to wait for one hour and 15 minutes)
```python
import optuna
import time
import random
from dotenv import load_dotenv


def objective(trial):
    trial.suggest_int("dummy", 0, 10)
    time.sleep(int(3600 * 1.25))
    for epoch in range(40):
        loss = random.random()
        trial.report(loss, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()


study = optuna.create_study(
    storage=f"postgresql+psycopg2://{os.getenv('POSTGRES_USERNAME')}:{os.getenv('POSTGRES_PASSWORD')}@{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DB')}",
    # storage=f"postgresql://{os.getenv('POSTGRES_USERNAME')}:{os.getenv('POSTGRES_PASSWORD')}@{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DB')}",
    study_name="Connection failure",
)
study.optimize(objective, n_trials=10)
```

### Additional context (optional)

My use case is composed of an upstream and a downstream training. While the optimization is targeting the upstream model, I cannot evaluate it unless it's trained for a few epochs and then used for training a downstream model. Only then I can call the `trial.report()` to report back to Optuna. And this takes a long time (more than an hour) and by then the Postgres connection is lost and as a result, the whole process fails.

BTW, I tested with MySQL and SQLite and so far, they are not facing the same problem.

**Comment by AMJasser** [comment]
@ziadloo I am facing the same problem. Any workarounds?

**Comment by ziadloo** [comment]
I switched to MySQL

**Comment by mukhamux** [comment]
You can try this:

```python
import optuna
from optuna.storages import RDBStorage
import os

url = f"postgresql+psycopg2://{os.getenv('POSTGRES_USERNAME')}:{os.getenv('POSTGRES_PASSWORD')}@{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DB')}"

study = optuna.create_study(
    storage=RDBStorage(url=url, engine_kwargs={'pool_recycle': 60}),
    study_name="Connection failure",
)
```


There could be many sources of your problem, such as whether you have a proxy in front of the database or whether you launched the database on a localhost, and also with what parameters your database is launched. The proposed solution allows alchemy to update the connection every 60 minutes, which should eliminate (or at least reduce) network problems. More details: https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_recycle
