### ISSUE TITLE
Optuna cannot multithread on sklearn Pipeline with multiple ColumnTransformers referencing column names

### ISSUE THREAD

**Issue by vkarakcheev** [optuna/optuna#5646]
### Expected behavior

Optuna optimization executed on sklearn `Pipeline` with _multiple_ `ColumnTransformer`s crashes when `n_jobs` ≠ 1 and the `transformers` argument of `ColumnTransformer`s references column _names_. But works fine when `n_jobs` = 1 _or_ when `transformers` argument of `ColumnTransformer`s references column _indices_.

### Environment

- OS: Windows-10-10.0.19045-SP0
- Python version: 3.11.7
- Optuna version: 3.6.1
- Sklearn version: 1.5.0
- Pandas version: 2.1.4

### Error messages, stack traces, or logs

```shell
[W 2024-08-28 12:09:53,378] Trial 0 failed with parameters: {'est__alpha': 2.3247620494647703, 'est__l1_ratio': 0.6976340871751063} because of the following error: ValueError('Specifying the columns using strings is only supported for dataframes.').
Traceback (most recent call last):
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\utils\_indexing.py", line 338, in _get_column_indices
    all_columns = X.columns
                  ^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'columns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\optuna\study\_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Temp\ipykernel_11588\885295757.py", line 46, in objective
    model.fit(X, y)
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\pipeline.py", line 472, in fit
    Xt = self._fit(X, y, routed_params)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\pipeline.py", line 409, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\joblib\memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\pipeline.py", line 1329, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 969, in fit_transform
    self._validate_column_callables(X)
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py", line 536, in _validate_column_callables
    transformer_to_input_indices[name] = _get_column_indices(X, columns)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SC13015\AppData\Local\Anaconda3\Lib\site-packages\sklearn\utils\_indexing.py", line 340, in _get_column_indices
    raise ValueError(
ValueError: Specifying the columns using strings is only supported for dataframes.
[W 2024-08-28 12:09:53,382] Trial 0 failed with value None.
```

### Steps to reproduce

```python
import pandas as pd

from sklearn import set_config
from sklearn.base import clone
from sklearn.datasets import load_iris
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import ElasticNet

from optuna import create_study

iris = load_iris()
X = pd.DataFrame(iris['data'], columns=iris['feature_names'])
y = pd.Series(iris['target']).rename('iris type')

set_config(transform_output='pandas')

transf_params = dict(
    remainder='passthrough',
    verbose_feature_names_out=False,
    force_int_remainder_cols=False,
)

# Works only when n_jobs=1
sc1_cols = ['sepal length (cm)', 'sepal width (cm)']
sc2_cols = ['petal length (cm)', 'petal width (cm)']

# Works with any n_jobs
# sc1_cols = [0, 1]
# sc2_cols = [2, 3]

pipe = Pipeline([
    ('scl', ColumnTransformer([('sc1', StandardScaler(), sc1_cols)], **transf_params)), 
    ('sc2', ColumnTransformer([('sc2', MinMaxScaler(), sc2_cols)], **transf_params)), 
    ('est', ElasticNet())
])

def objective(trial):
    params = dict(
        est__alpha=trial.suggest_float('est__alpha', 1e-3, 1e3, log=True),
        est__l1_ratio=trial.suggest_float('est__l1_ratio', 0, 1),
    )
    
    model = clone(pipe).set_params(**params)
    model.fit(X, y)

    return model.score(X, y)
    
study = create_study(direction='maximize')
study.optimize(objective, n_trials=1, n_jobs=-1, show_progress_bar=True)
```

**Comment by kAIto47802** [comment]
@vkarakcheev 

Thank you for reporting.
However, this doesn't seem to be an issue with Optuna itself; it appears to be a problem with scikit-learn. The same error occurs in the following code, which does not using Optuna:

```py
from concurrent.futures import ThreadPoolExecutor

import pandas as pd
from sklearn import set_config
from sklearn.base import clone
from sklearn.datasets import load_iris
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import ElasticNet

iris = load_iris()
X = pd.DataFrame(iris['data'], columns=iris['feature_names'])
y = pd.Series(iris['target']).rename('iris type')

set_config(transform_output='pandas')

transf_params = dict(
    remainder='passthrough',
    verbose_feature_names_out=False,
    force_int_remainder_cols=False,
)

# Works only when n_jobs=1
sc1_cols = ['sepal length (cm)', 'sepal width (cm)']
sc2_cols = ['petal length (cm)', 'petal width (cm)']

pipe = Pipeline([
    ('scl', ColumnTransformer([('sc1', StandardScaler(), sc1_cols)], **transf_params)), 
    ('sc2', ColumnTransformer([('sc2', MinMaxScaler(), sc2_cols)], **transf_params)), 
    ('est', ElasticNet())
])

def f():
    params = dict(
        est__alpha=0.01,
        est__l1_ratio=0.5,
    )
    
    model = clone(pipe).set_params(**params)
    model.fit(X, y)

    return model.score(X, y)

with ThreadPoolExecutor(max_workers=8) as executor:
    results = []
    for _ in range(8):
        results.append(executor.submit(f))

print(results[0].result())
```


Also, as shown in [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html), Optuna supports parallel optimization by running multiple optimization scripts with an RDB or journal storage.
If you follow this approach, such errors should not occur.
