### ISSUE TITLE
AttributeError is raised when using RDB storage.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#938]
## Reproducible examples (optional)

```python
import optuna

# Define a simple 2-dimensional objective function whose minimum value is -1 when (x, y) = (0, -1).
def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', [-1, 0, 1])
    return x**2 + y


if __name__ == '__main__':
    # Let us minimize the objective function above.
    print('Running 10 trials...')
    study = optuna.create_study(storage="sqlite:///db.sqlite3")
    study.optimize(objective, n_trials=10)
    print('Best value: {} (params: {})\n'.format(study.best_value, study.best_params))
```

## Expected behavior

tag: v1.1.0

```console
$ git co v1.1.0
$ python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 14:05:57,875] A new study created with name: no-name-a2889f9d-79d7-40cc-aff4-f4021183b6aa
[I 2020-02-18 14:05:57,977] Finished trial#0 resulted in value: 78.25382960871015. Current best value is 78.25382960871015 with parameters: {'x': -8.78941577175128, 'y': 1}.
[I 2020-02-18 14:05:58,067] Finished trial#1 resulted in value: 1601.2080527969047. Current best value is 78.25382960871015 with parameters: {'x': -8.78941577175128, 'y': 1}.
[I 2020-02-18 14:05:58,159] Finished trial#2 resulted in value: 155.3355136572432. Current best value is 78.25382960871015 with parameters: {'x': -8.78941577175128, 'y': 1}.
[I 2020-02-18 14:05:58,252] Finished trial#3 resulted in value: 4928.445801453334. Current best value is 78.25382960871015 with parameters: {'x': -8.78941577175128, 'y': 1}.
[I 2020-02-18 14:05:58,349] Finished trial#4 resulted in value: 5494.046052713425. Current best value is 78.25382960871015 with parameters: {'x': -8.78941577175128, 'y': 1}.
[I 2020-02-18 14:05:58,451] Finished trial#5 resulted in value: 7.806334896764313. Current best value is 7.806334896764313 with parameters: {'x': -2.793981907021646, 'y': 0}.
[I 2020-02-18 14:05:58,540] Finished trial#6 resulted in value: 3581.7294062867. Current best value is 7.806334896764313 with parameters: {'x': -2.793981907021646, 'y': 0}.
[I 2020-02-18 14:05:58,633] Finished trial#7 resulted in value: 6157.892248662727. Current best value is 7.806334896764313 with parameters: {'x': -2.793981907021646, 'y': 0}.
[I 2020-02-18 14:05:58,729] Finished trial#8 resulted in value: 538.9770074142994. Current best value is 7.806334896764313 with parameters: {'x': -2.793981907021646, 'y': 0}.
[I 2020-02-18 14:05:58,824] Finished trial#9 resulted in value: 2453.3913002520094. Current best value is 7.806334896764313 with parameters: {'x': -2.793981907021646, 'y': 0}.
Best value: 7.806334896764313 (params: {'x': -2.793981907021646, 'y': 0})
```

## Error log

rev: 7344ee0f

```console
$ git co master
$ rm db.sqlite3 | true && python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 14:06:51,506] A new study created with name: no-name-32a1bb2f-64c7-4faa-8834-0bbdbaff508b
[I 2020-02-18 14:06:51,635] Finished trial#0 resulted in value: 2420.888780807176. Current best value is 2420.888780807176 with parameters: {'x': -49.192365066208964, 'y': 1}.
[I 2020-02-18 14:06:51,746] Finished trial#1 resulted in value: 145.24171551709355. Current best value is 145.24171551709355 with parameters: {'x': 12.093044096384233, 'y': -1}.
[I 2020-02-18 14:06:51,857] Finished trial#2 resulted in value: 1.014598248626613. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:51,957] Finished trial#3 resulted in value: 8577.24930691218. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,068] Finished trial#4 resulted in value: 8417.027436775961. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,181] Finished trial#5 resulted in value: 319.0475577707139. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,288] Finished trial#6 resulted in value: 4.4949007058993296. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,391] Finished trial#7 resulted in value: 2865.4595762936938. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,500] Finished trial#8 resulted in value: 2027.0173870485705. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
[I 2020-02-18 14:06:52,605] Finished trial#9 resulted in value: 7283.744078340451. Current best value is 1.014598248626613 with parameters: {'x': -0.12082321228395188, 'y': 1}.
Best value: 1.014598248626613 (params: {'x': -0.12082321228395188, 'y': 1})

Exception ignored in: <function RDBStorage.__del__ at 0x130bd7ca0>
Traceback (most recent call last):
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 943, in __del__
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 932, in remove_session
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/scoping.py", line 94, in remove
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1298, in close
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1334, in _close_impl
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1352, in expunge_all
AttributeError: 'NoneType' object has no attribute 'InstanceState'

```

## Environment

- Optuna version: 1.2.0 (master branch, rev: 7344ee0f).
- Python version: 3.8.1
- OS: macOS
- (Optional) Other libraries and their versions:

## Steps to reproduce

1. Optimize with RDB storage backend.

**Comment by c-bata** [comment]
It seems this bug is raised after https://github.com/optuna/optuna/pull/844

```
(venv) $ git co 30af1355
M       examples/quadratic_simple.py
Previous HEAD position was cd817d1e Merge pull request #911 from crcrpar/update-pip
HEAD is now at 30af1355 Merge pull request #908 from PhilipMay/trial_level_check
(venv) $ rm db.sqlite3 | true && python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 14:18:39,980] A new study created with name: no-name-c5ef350a-25ec-462d-b6b3-6cae135b3fb9
[I 2020-02-18 14:18:40,087] Finished trial#0 resulted in value: 3058.1549513541045. Current best value is 3058.1549513541045 with parameters: {'x': 55.30962801677575, 'y': -1}.
[I 2020-02-18 14:18:40,185] Finished trial#1 resulted in value: 96.08993051580472. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,275] Finished trial#2 resulted in value: 618.0581139165189. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,371] Finished trial#3 resulted in value: 1532.5848089465755. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,466] Finished trial#4 resulted in value: 5188.737521831831. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,561] Finished trial#5 resulted in value: 577.7065396403286. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,655] Finished trial#6 resulted in value: 6688.73314729496. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,745] Finished trial#7 resulted in value: 929.0835295526541. Current best value is 96.08993051580472 with parameters: {'x': 9.853422274306766, 'y': -1}.
[I 2020-02-18 14:18:40,844] Finished trial#8 resulted in value: 76.34434773834195. Current best value is 76.34434773834195 with parameters: {'x': -8.680112196183984, 'y': 1}.
[I 2020-02-18 14:18:40,938] Finished trial#9 resulted in value: 1.0097016216824755. Current best value is 1.0097016216824755 with parameters: {'x': 1.00483910238529, 'y': 0}.
Best value: 1.0097016216824755 (params: {'x': 1.00483910238529, 'y': 0})

(venv) $ git co cfea20f9
M       examples/quadratic_simple.py
Previous HEAD position was 30af1355 Merge pull request #908 from PhilipMay/trial_level_check
HEAD is now at cfea20f9 Merge pull request #844 from crcrpar/progressbar-for-study
(venv) $ rm db.sqlite3 | true && python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 14:18:51,353] A new study created with name: no-name-4b5f5873-6f72-49ba-a9d1-290ac64e5082
[I 2020-02-18 14:18:51,470] Finished trial#0 resulted in value: 1681.81462860948. Current best value is 1681.81462860948 with parameters: {'x': 41.022123648215484, 'y': -1}.
[I 2020-02-18 14:18:51,569] Finished trial#1 resulted in value: 8376.517387109296. Current best value is 1681.81462860948 with parameters: {'x': 41.022123648215484, 'y': -1}.
[I 2020-02-18 14:18:51,675] Finished trial#2 resulted in value: 5813.480720592612. Current best value is 1681.81462860948 with parameters: {'x': 41.022123648215484, 'y': -1}.
[I 2020-02-18 14:18:51,776] Finished trial#3 resulted in value: 5476.058251314253. Current best value is 1681.81462860948 with parameters: {'x': 41.022123648215484, 'y': -1}.
[I 2020-02-18 14:18:51,884] Finished trial#4 resulted in value: 1652.5255859008655. Current best value is 1652.5255859008655 with parameters: {'x': 40.6389663488242, 'y': 1}.
[I 2020-02-18 14:18:51,980] Finished trial#5 resulted in value: 2274.629884259408. Current best value is 1652.5255859008655 with parameters: {'x': 40.6389663488242, 'y': 1}.
[I 2020-02-18 14:18:52,092] Finished trial#6 resulted in value: 178.93354137000273. Current best value is 178.93354137000273 with parameters: {'x': -13.413930869435802, 'y': -1}.
[I 2020-02-18 14:18:52,195] Finished trial#7 resulted in value: 1684.4453435827525. Current best value is 178.93354137000273 with parameters: {'x': -13.413930869435802, 'y': -1}.
[I 2020-02-18 14:18:52,294] Finished trial#8 resulted in value: 7099.341109192361. Current best value is 178.93354137000273 with parameters: {'x': -13.413930869435802, 'y': -1}.
[I 2020-02-18 14:18:52,391] Finished trial#9 resulted in value: 1685.2518766152984. Current best value is 178.93354137000273 with parameters: {'x': -13.413930869435802, 'y': -1}.
Best value: 178.93354137000273 (params: {'x': -13.413930869435802, 'y': -1})

Exception ignored in: <function RDBStorage.__del__ at 0x128c68af0>
Traceback (most recent call last):
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 940, in __del__
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 929, in remove_session
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/scoping.py", line 94, in remove
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1298, in close
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1334, in _close_impl
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1352, in expunge_all
AttributeError: 'NoneType' object has no attribute 'InstanceState'
```

**Comment by c-bata** [comment]
I reverted #844 at.
https://github.com/optuna/optuna/compare/master...c-bata:revert-progress-bar?expand=1

Then I confirmed this bug will be fixed.

```
 $ python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 14:34:18,302] A new study created with name: no-name-619e8388-6226-41d9-b201-fc13dd147d92
[I 2020-02-18 14:34:18,420] Finished trial#0 resulted in value: 568.4444380586791. Current best value is 568.4444380586791 with parameters: {'x': 23.842072855745556, 'y': 0}.
[I 2020-02-18 14:34:18,526] Finished trial#1 resulted in value: 9608.563683132954. Current best value is 568.4444380586791 with parameters: {'x': 23.842072855745556, 'y': 0}.
[I 2020-02-18 14:34:18,626] Finished trial#2 resulted in value: 2665.7008834874155. Current best value is 568.4444380586791 with parameters: {'x': 23.842072855745556, 'y': 0}.
[I 2020-02-18 14:34:18,724] Finished trial#3 resulted in value: 2313.1181453002596. Current best value is 568.4444380586791 with parameters: {'x': 23.842072855745556, 'y': 0}.
[I 2020-02-18 14:34:18,828] Finished trial#4 resulted in value: 277.9179507326905. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
[I 2020-02-18 14:34:18,921] Finished trial#5 resulted in value: 6208.017621044886. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
[I 2020-02-18 14:34:19,021] Finished trial#6 resulted in value: 2707.573368315614. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
[I 2020-02-18 14:34:19,127] Finished trial#7 resulted in value: 9413.829420721542. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
[I 2020-02-18 14:34:19,229] Finished trial#8 resulted in value: 5821.467082715411. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
[I 2020-02-18 14:34:19,328] Finished trial#9 resulted in value: 2329.103214093981. Current best value is 277.9179507326905 with parameters: {'x': -16.67087132493951, 'y': 0}.
Best value: 277.9179507326905 (params: {'x': -16.67087132493951, 'y': 0})

```

**Comment by toshihikoyanase** [comment]
I failed to reproduce this problem when I used docker as follows:

938.py
```python
import optuna

# Define a simple 2-dimensional objective function whose minimum value is -1 when (x, y) = (0, -1).
def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', [-1, 0, 1])
    return x**2 + y


if __name__ == '__main__':
    # Let us minimize the objective function above.
    print('Running 10 trials...')
    study = optuna.create_study(storage="sqlite:///db.sqlite3")
    study.optimize(objective, n_trials=10)
    print('Best value: {} (params: {})\n'.format(study.best_value, study.best_params))
```

```console
$ docker run -v $(pwd)/:/var/examples --rm -it python:3.8.1 /bin/bash

# pip install git+https://github.com/optuna/optuna.git@7344ee0fcdddb28b18a292e63caea425ae08da95
# python 938.py
```

Could you share more information about your environment such as the output of `pip freeze`?

**Comment by c-bata** [comment]
Hmm... Here is the results of `pip freeze`.

```
(venv) $ pip freeze
alabaster==0.7.12
alembic==1.3.2
appnope==0.1.0
attrs==19.3.0
autopep8==1.5
Babel==2.8.0
backcall==0.1.0
certifi==2019.11.28
chardet==3.0.4
cliff==2.18.0
cma==2.7.0
cmd2==0.8.9
colorlog==4.1.0
decorator==4.4.1
docutils==0.16
entrypoints==0.3
flake8==3.7.9
idna==2.8
imagesize==1.2.0
ipdb==0.12.3
ipython==7.12.0
ipython-genutils==0.2.0
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
lightgbm==2.3.1
Mako==1.1.0
MarkupSafe==1.1.1
mccabe==0.6.1
mock==3.0.5
more-itertools==8.2.0
numpy==1.18.1
-e git+git@github.com:c-bata/optuna.git@697138a718a5dbcb61e16f5cec7fc97343b7c3de#egg=optuna
packaging==20.1
pandas==1.0.0
parso==0.6.1
pbr==5.4.4
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prettytable==0.7.2
prompt-toolkit==3.0.3
ptyprocess==0.6.0
py==1.8.1
pyaml==19.12.0
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.5.2
pyparsing==2.4.6
pyperclip==1.7.0
pytest==5.3.5
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
PyYAML==5.3
requests==2.22.0
scikit-learn==0.22.1
scikit-optimize==0.7.1
scipy==1.4.1
six==1.14.0
snowballstemmer==2.0.0
Sphinx==2.4.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
SQLAlchemy==1.3.12
stevedore==1.31.0
tqdm==4.41.1
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.1.8
```

**Comment by toshihikoyanase** [comment]
Thank you for your swift reply! I'll check further details.

**Comment by c-bata** [comment]
@toshihikoyanase I can confirm no exceptions are raised if I created a new venv environment.

```
$ python3.8 -m venv venv2
$ source venv2/bin/activate
(venv2) $ pip install .

...

Successfully installed Mako-1.1.1 MarkupSafe-1.1.1 PrettyTable-0.7.2 PyYAML-5.3 alembic-1.4.0 cliff-2.18.0 cmd2-0.8.9 colorlog-4.1.0 joblib-0.14.1 numpy-1.18.1 optuna-1.1.0 pbr-5.4.4 pyparsing-2.4.6 pyperclip-1.7.0 python-dateutil-2.8.1 python-editor-1.0.4 scipy-1.4.1 six-1.14.0 sqlalchemy-1.3.13 stevedore-1.32.0 tqdm-4.42.1 wcwidth-0.1.8
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv2) $ python -V
Python 3.8.1
(venv2) $ python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 16:50:24,514] A new study created with name: no-name-86f3d954-6f2b-4540-bbdd-df0c302c0444
[I 2020-02-18 16:50:24,619] Finished trial#0 resulted in value: 1626.0444213022997. Current best value is 1626.0444213022997 with parameters: {'x': 40.32424111254048, 'y': 0}.
[I 2020-02-18 16:50:24,713] Finished trial#1 resulted in value: 1.6777229077466216. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:24,802] Finished trial#2 resulted in value: 30.697306136158364. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:24,895] Finished trial#3 resulted in value: 395.5597316809886. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:24,990] Finished trial#4 resulted in value: 889.734852280411. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:25,082] Finished trial#5 resulted in value: 3890.6321503599734. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:25,173] Finished trial#6 resulted in value: 3631.870486699689. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:25,264] Finished trial#7 resulted in value: 6687.296597543083. Current best value is 1.6777229077466216 with parameters: {'x': -1.6363749288432103, 'y': -1}.
[I 2020-02-18 16:50:25,366] Finished trial#8 resulted in value: 1.015079498066978. Current best value is 1.015079498066978 with parameters: {'x': 1.4195349583814334, 'y': -1}.
[I 2020-02-18 16:50:25,456] Finished trial#9 resulted in value: 1200.474290445185. Current best value is 1.015079498066978 with parameters: {'x': 1.4195349583814334, 'y': -1}.
Best value: 1.015079498066978 (params: {'x': 1.4195349583814334, 'y': -1})

(venv2) $ source venv/bin/activate
(venv) $ python -V
Python 3.8.1
(venv) $ python examples/quadratic_simple.py 
Running 10 trials...
[I 2020-02-18 16:50:53,977] A new study created with name: no-name-a76d8ac5-3371-479d-b83c-ad72d5daf096
[I 2020-02-18 16:50:54,101] Finished trial#0 resulted in value: 5988.238887225546. Current best value is 5988.238887225546 with parameters: {'x': 77.37725045015199, 'y': 1}.
[I 2020-02-18 16:50:54,204] Finished trial#1 resulted in value: 9658.622090646928. Current best value is 5988.238887225546 with parameters: {'x': 77.37725045015199, 'y': 1}.
[I 2020-02-18 16:50:54,318] Finished trial#2 resulted in value: 119.38217690089748. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,423] Finished trial#3 resulted in value: 645.4622578266325. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,530] Finished trial#4 resulted in value: 8567.044816249627. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,642] Finished trial#5 resulted in value: 484.264351615369. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,753] Finished trial#6 resulted in value: 2491.0462037579155. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,865] Finished trial#7 resulted in value: 1255.575908955518. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:54,977] Finished trial#8 resulted in value: 4064.031060162669. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
[I 2020-02-18 16:50:55,085] Finished trial#9 resulted in value: 2155.044381490174. Current best value is 119.38217690089748 with parameters: {'x': -10.97188119243448, 'y': -1}.
Best value: 119.38217690089748 (params: {'x': -10.97188119243448, 'y': -1})

Exception ignored in: <function RDBStorage.__del__ at 0x129e1edc0>
Traceback (most recent call last):
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 943, in __del__
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 932, in remove_session
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/scoping.py", line 94, in remove
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1298, in close
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1334, in _close_impl
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.8/site-packages/SQLAlchemy-1.3.12-py3.8-macosx-10.15-x86_64.egg/sqlalchemy/orm/session.py", line 1352, in expunge_all
AttributeError: 'NoneType' object has no attribute 'InstanceState'

```

**Comment by toshihikoyanase** [comment]
@c-bata I'm not fully sure but `prompt_toolkit` may be related to this issue. When I uninstalled it from your list of libraries, AttributeError is not raised.

**Comment by c-bata** [comment]
Thank you for your investigation. I guess `prompt_toolkit` is installed with iPython or ipdb that are not dependencies of Optuna. I close this.

**Comment by c-bata** [comment]
I closed but I wonder that someone will report the same issue because `prompt_toolkit` is in dependencies in `jupyter`. Hmm...
